'use strict';
const $=id=>document.getElementById(id),val=id=>Number($(id).value),fmt=(x,d=4)=>Number(x).toLocaleString('id-ID',{maximumFractionDigits:d});
const sci=x=>Number(x).toExponential(3);
// Ideal solutions at 25 C. Charge balance includes water throughout titration.
function acidPH(total,ka,strong=0){let lo=-16,hi=2;for(let i=0;i<180;i++){const m=(lo+hi)/2,h=10**m;const residual=h+strong-1e-14/h-total*ka/(ka+h);if(residual>0)hi=m;else lo=m}return -(lo+hi)/2}
function strongPH(excess){const root=Math.hypot(excess,2e-7);const h=excess>=0?(excess+root)/2:2e-14/(root-excess);return -Math.log10(h)}
function concentration(a,k,n,t){return n===0?Math.max(0,a-k*t):n===1?a*Math.exp(-k*t):a/(1+k*a*t)}
function eqSolve(a,b,c,k){let lo=-c,hi=Math.min(a,b);for(let i=0;i<100;i++){const x=(lo+hi)/2;if(c+x-k*(a-x)*(b-x)>0)hi=x;else lo=x}const x=(lo+hi)/2;return {x,a:a-x,b:b-x,c:c+x}}
function gasEq(v,t){const k=.1*Math.exp(-57200/8.314*(1/t-1/298));let lo=-.05,hi=1;for(let i=0;i<100;i++){const x=(lo+hi)/2;if((.1+2*x)**2-k*v*(1-x)>0)hi=x;else lo=x}const x=(lo+hi)/2;return{k,a:1-x,b:.1+2*x}}
function titration(v,weak){const totalV=(25+v)/1000,total=.0025/totalV,na=.1*v/1000/totalV;return weak?acidPH(total,1.8e-5,na):strongPH(total-na)}
function choose(id,label,options){const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');s.id=id;options.forEach(([v,t])=>s.add(new Option(t,v)));l.append(s);$('controls').append(l);s.addEventListener('change',update)}
function plot(points,xLabel,yLabel,yMin,yMax){const xmin=points[0][0],xmax=points[points.length-1][0];if(yMin===undefined){yMin=0;yMax=Math.max(...points.map(p=>p[1]))||1}const coords=points.map(([x,y])=>(45+350*(x-xmin)/(xmax-xmin))+','+(190-155*(y-yMin)/(yMax-yMin))).join(' ');return '<svg viewBox="0 0 430 245" role="img" aria-label="Grafik '+yLabel+' terhadap '+xLabel+'"><path d="M45 30V190H400" fill="none" stroke="#a1a1aa"/><polyline points="'+coords+'" fill="none" stroke="#a78bfa" stroke-width="3"/><g fill="#fafafa" font-size="11"><text x="45" y="218">'+fmt(xmin)+' → '+fmt(xmax)+' '+xLabel+'</text><text x="45" y="18">'+yLabel+': '+fmt(yMin)+' → '+fmt(yMax)+'</text></g></svg>'}
function bars(rows){const max=Math.max(...rows.map(r=>Math.abs(r[1])),1e-12);return rows.map(([name,n])=>'<p>'+name+': <b>'+fmt(n)+'</b></p><div class="track"><i style="width:'+100*Math.abs(n)/max+'%"></i></div>').join('')}
function setup(){if(TOPIC.sim==='ph')choose('kind','Jenis zat',[['strong-acid','Asam kuat monoprotik'],['weak-acid','Asam lemah monoprotik'],['strong-base','Basa kuat monobasa'],['weak-base','Basa lemah monobasa']]);if(TOPIC.sim==='titration')choose('kind','Asam analit',[['strong','HCl (kuat)'],['weak','CH₃COOH (Ka=1,8×10⁻⁵)']]);if(TOPIC.sim==='hydrolysis')choose('kind','Garam',[['neutral','NaCl'],['acetate','CH₃COONa'],['ammonium','NH₄Cl']]);update()}
let lastResult='';
function update(){let text='',visual='';const s=TOPIC.sim;
if(s==='calor'){const ql=val('mass')*4.18*val('delta'),qc=val('capacity')*val('delta'),qr=-(ql+qc),dh=qr/(1000*val('amount'));text='q larutan='+fmt(ql)+' J; q kalorimeter='+fmt(qc)+' J; q reaksi='+fmt(qr/1000)+' kJ; ΔH molar='+fmt(dh)+' kJ/mol. '+(qr<0?'Eksoterm.':qr>0?'Endoterm.':'Tidak ada perubahan kalor dalam model.');visual=bars([['q larutan (J)',ql],['q kalorimeter (J)',qc],['q reaksi (J)',qr]])}
if(s==='hess'){const f=val('factor')*val('direction'),d1=-110.5*f,d2=-283*f,bond=val('eh')+val('ec')-2*val('ehc');text='Lintasan karbon: ΔH₁='+fmt(d1)+' kJ; ΔH₂='+fmt(d2)+' kJ; ΔH total='+fmt(d1+d2)+' kJ. Reaksi '+(f>0?'maju':'balik')+', pengali '+Math.abs(f)+'. Contoh terpisah H₂+Cl₂→2HCl: ΔH≈'+fmt(bond)+' kJ.';visual=bars([['Tahap 1 (kJ)',d1],['Tahap 2 (kJ)',d2],['Total (kJ)',d1+d2]])}
if(s==='arrhenius'){const t=val('temperature'),ea=(50-val('lowering'))*1000,k=1e7*Math.exp(-ea/(8.314*t)),reference=1e7*Math.exp(-50000/(8.314*300));text='Ea='+fmt(ea/1000)+' kJ/mol; k='+sci(k)+' s⁻¹. Dibanding kondisi 300 K tanpa katalis: '+fmt(k/reference)+' kali. A dianggap tetap; ΔH dan K kesetimbangan tidak berubah oleh katalis.';visual=plot(Array.from({length:51},(_,i)=>[280+i*2,Math.log10(1e7*Math.exp(-ea/(8.314*(280+i*2))))]),'T (K)','log₁₀ k',-4,3)}
if(s==='rate'){const a=val('initial'),k=val('constant'),n=val('order'),t=val('time'),at=concentration(a,k,n,t),half=n===0?a/2/k:n===1?Math.log(2)/k:1/k/a;const units=['M/s','s⁻¹','M⁻¹s⁻¹'][n];text='[A]t='+fmt(at)+' M; laju awal='+fmt(k*a**n)+' M/s; laju saat t='+fmt(at===0?0:k*at**n)+' M/s; t½='+fmt(half)+' s; satuan k='+units+'. Menggandakan A awal mengalikan laju awal '+2**n+' kali.';visual=plot(Array.from({length:101},(_,i)=>[i,concentration(a,k,n,i)]),'t (s)','[A] (M)',0,a)}
if(s==='equilibrium'){const a=val('a'),b=val('b'),c=val('c'),k=val('k'),q=c/a/b,e=eqSolve(a,b,c,k);text='Q awal='+fmt(q)+'; K='+fmt(k)+'; arah '+(Math.abs(q-k)<1e-9?'sudah setimbang':q<k?'kanan':'kiri')+'. x='+fmt(e.x)+' M; [A]eq='+fmt(e.a)+' M; [B]eq='+fmt(e.b)+' M; [C]eq='+fmt(e.c)+' M; Q akhir='+fmt(e.c/e.a/e.b)+'.';visual=bars([['A setimbang (M)',e.a],['B setimbang (M)',e.b],['C setimbang (M)',e.c]])}
if(s==='shift'){const v=val('volume'),t=val('temp'),e=gasEq(v,t);text='Kc model='+fmt(e.k,6)+'; n(N₂O₄)='+fmt(e.a)+' mol; n(NO₂)='+fmt(e.b)+' mol; [NO₂]='+fmt(e.b/v)+' M; fraksi mol NO₂='+fmt(e.b/(e.a+e.b))+'; tekanan total ideal='+fmt((e.a+e.b)*.082057*t/v)+' atm. K acuan ilustratif, bukan data eksperimen.';visual=bars([['N₂O₄ (mol)',e.a],['NO₂ (mol)',e.b]])}
if(s==='ph'){const c=10**val('logc'),k=10**(-val('pka')),kind=$('kind').value,base=kind.endsWith('base'),p=kind.startsWith('strong')?strongPH(c):acidPH(c,k),ph=base?14-p:p;text='C='+sci(c)+' M; '+(base?'Kb':'Ka')+' zat lemah='+sci(k)+'; pH='+fmt(ph)+'; pOH='+fmt(14-ph)+'; [H₃O⁺]='+sci(10**(-ph))+' M. Model ideal25°C; konstanta zat lemah tidak dipakai untuk zat kuat.';visual=plot(Array.from({length:71},(_,i)=>{const x=-8+i/10,y=kind.startsWith('strong')?strongPH(10**x):acidPH(10**x,k);return[x,base?14-y:y]}),'log₁₀ C','pH',0,14)}
if(s==='titration'){const v=val('vb'),weak=$('kind').value==='weak',p=titration(v,weak);text='V NaOH='+fmt(v)+' mL; V ekuivalen=25 mL; pH='+fmt(p)+'. '+(v<25?'Sebelum ekuivalen.':v===25?'Tepat ekuivalen.':'Sesudah ekuivalen.')+' Rentang indikator: metil jingga3,1–4,4; fenolftalein8,2–10.';visual=plot(Array.from({length:201},(_,i)=>[i/4,titration(i/4,weak)]),'V NaOH (mL)','pH',0,14)}
if(s==='buffer'){const ha=val('ha'),salt=val('salt'),added=val('added'),p=acidPH((ha+salt)/100,1.8e-5,(salt+added)/100),left=ha-added,right=salt+added;const ratio=left>0&&right>0;const approx=ratio?-Math.log10(1.8e-5)+Math.log10(right/left):null;text='pH neraca kesetimbangan='+fmt(p)+'. '+(ratio?'Mol stoikiometris setelah netralisasi: HA='+fmt(left)+' mmol, A⁻='+fmt(right)+' mmol; pH pendekatan rasio='+fmt(approx)+'.':'Kapasitas pasangan terlampaui/komponen habis: jangan gunakan rumus rasio mol.')+' Volume dianggap tetap100mL; perubahan aktual ditentukan kesetimbangan.';visual=plot(Array.from({length:101},(_,i)=>{const x=-25+i*.5;return[x,acidPH((ha+salt)/100,1.8e-5,(salt+x)/100)]}),'Tambahan (mmol; −asam,+basa)','pH',0,14)}
if(s==='hydrolysis'){const c=10**val('logc'),kind=$('kind').value,k=1e-14/1.8e-5,p=kind==='neutral'?7:kind==='acetate'?acidPH(c,1.8e-5,c):acidPH(c,k);text='C='+sci(c)+' M; pH='+fmt(p)+'. '+(kind==='neutral'?'NaCl: tidak ada hidrolisis berarti dalam model.':'Konstanta hidrolisis='+sci(k)+'. '+(kind==='acetate'?'Asetat membentuk OH⁻.':'Amonium membentuk H₃O⁺.'))+' Suhu25°C, aktivitas didekati konsentrasi.';visual=plot(Array.from({length:51},(_,i)=>{const x=-6+i/10,C=10**x;return[x,kind==='neutral'?7:kind==='acetate'?acidPH(C,1.8e-5,C):acidPH(C,k)]}),'log₁₀ C garam','pH',0,14)}
lastResult=text;$('result').textContent=text;$('visual').innerHTML=visual;document.querySelectorAll('[data-value]').forEach(e=>e.textContent=$(e.dataset.value).value);
}
function save(){if(window.PortalSubmission?.isFinal())return;try{const d={};document.querySelectorAll('[data-answer]').forEach(e=>d[e.id]=e.value);localStorage.setItem(STORAGE_KEY,JSON.stringify(d));$('draft-status').textContent='Draf tersimpan pada perangkat.'}catch(_){$('draft-status').textContent='Draf belum tersimpan. Penyimpanan browser tidak tersedia.'}}
function start(){setup();try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');Object.entries(d).forEach(([id,v])=>{if($(id)&&$(id).hasAttribute('data-answer'))$(id).value=v})}catch(_){}$('student-date').value=new Date().toLocaleDateString('id-ID');document.querySelectorAll('[data-answer]').forEach(e=>e.addEventListener('input',save));document.querySelectorAll('#controls input').forEach(e=>e.addEventListener('input',update));$('record').onclick=()=>{if(window.PortalSubmission?.isFinal()||$('lks-observasi').disabled)return;const inputs=[...$('controls').querySelectorAll('input,select')].map(e=>e.id+'='+e.value).join('; ');$('lks-observasi').value+=($('lks-observasi').value?'\n\n':'')+inputs+'\n'+lastResult;save()};}
document.addEventListener('DOMContentLoaded',start);

