'use strict';
const $=id=>document.getElementById(id), fmt=(v,d=3)=>Number(v).toLocaleString('id-ID',{maximumFractionDigits:d});
const val=id=>Number($(id).value), sel=id=>$(id).value;
function choose(id,label,options){const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');s.id=id;options.forEach(([v,t])=>s.add(new Option(t,v)));l.append(s);$('controls').append(l);s.addEventListener('change',update)}
function bars(items){return '<div class="bars">'+items.map(([label,n,max])=>'<div>'+label+' <b>'+fmt(n)+'</b><div class="track"><i style="width:'+Math.max(0,Math.min(100,100*n/max))+'%"></i></div></div>').join('')+'</div>'}
const reactions=[{label:'H₂ + O₂ → H₂O',names:['H₂','O₂','H₂O'],atoms:[{H:2},{O:2},{H:2,O:1}],split:2,min:[2,1,2]},{label:'CH₄ + O₂ → CO₂ + H₂O',names:['CH₄','O₂','CO₂','H₂O'],atoms:[{C:1,H:4},{O:2},{C:1,O:2},{H:2,O:1}],split:2,min:[1,2,1,2]},{label:'Fe + O₂ → Fe₂O₃',names:['Fe','O₂','Fe₂O₃'],atoms:[{Fe:1},{O:2},{Fe:2,O:3}],split:2,min:[4,3,2]}];
const cations=[['Na',1,'natrium',false],['Mg',2,'magnesium',false],['Ca',2,'kalsium',false],['Al',3,'aluminium',false],['Fe',2,'besi(II)',false],['Fe',3,'besi(III)',false],['NH₄',1,'amonium',true]];
const anions=[['Cl',1,'klorida',false],['O',2,'oksida',false],['OH',1,'hidroksida',true],['NO₃',1,'nitrat',true],['SO₄',2,'sulfat',true]];
const safety=[{title:'Membuat larutan tepat 100,0 mL',choices:['Mengisi beker kira-kira 100 mL','Melarutkan lalu menyesuaikan volume akhir dalam labu ukur','Memanaskan larutan dalam labu ukur'],correct:1,why:'Labu ukur dikalibrasi untuk volume akhir tertentu. Sesuaikan meniskus pada tanda setelah larutan berada pada suhu yang sesuai kalibrasi.'},{title:'Memindahkan tepat 10,00 mL larutan',choices:['Pipet volumetrik dan pengisap pipet','Memipet dengan mulut','Menuang dari tabung reaksi'],correct:0,why:'Pipet volumetrik dirancang untuk transfer volume tetap. Pengisap pipet mencegah paparan melalui mulut.'},{title:'Menemukan tumpahan bahan tak dikenal',choices:['Mencampurnya dengan basa','Menghirup agar mengenali zat','Menjauh, memperingatkan orang sekitar dan melapor guru'],correct:2,why:'Komposisi tidak diketahui sehingga tindakan kimia sembarangan berbahaya. Ikuti penanganan oleh guru menurut SOP dan SDS.'},{title:'Membaca meniskus larutan bening',choices:['Mata sejajar bagian bawah meniskus cekung','Mata dari atas','Membaca perkiraan tanpa melihat skala'],correct:0,why:'Posisi mata sejajar mengurangi paralaks; bentuk meniskus dan jenis cairan harus diperhatikan.'}];
function setup(){
 if(TOPIC.sim==='particles'){choose('kind','Jenis partikel',[['element','Unsur atomik (model)'],['oxygen','Unsur molekuler O₂'],['water','Senyawa H₂O'],['mix','Campuran O₂ dan H₂O']]);choose('state','Keadaan model',[['solid','Padat'],['liquid','Cair'],['gas','Gas']])}
 if(TOPIC.sim==='formula'){choose('cation','Kation',cations.map((x,i)=>[i,x[0]+' '+x[1]+'+']));choose('anion','Anion',anions.map((x,i)=>[i,x[0]+' '+x[1]+'−']))}
 if(TOPIC.sim==='mole')choose('substance','Zat',[['18|H₂O|molekul|no','H₂O, M=18 g/mol'],['44|CO₂|molekul|yes','CO₂, M=44 g/mol'],['58.5|NaCl|satuan formula|no','NaCl, M=58,5 g/mol'],['56|Fe|atom|no','Fe, M=56 g/mol']]);
 if(TOPIC.sim==='safety'){choose('scenario','Skenario',safety.map((x,i)=>[i,x.title]));choose('decision','Pilih tindakan',[['-1','Pilih tindakan dahulu']])}
 if(TOPIC.sim==='balance'){choose('reaction','Persamaan',reactions.map((x,i)=>[i,x.label]));const host=document.createElement('div');host.id='coefficients';$('controls').append(host)}
 update();
}
let lastResult='', lastScenario=-1,lastReaction=-1;
function update(){
 let text='',viz='';const s=TOPIC.sim;
 if(s==='experiment'){const t=240*val('size')/((1+(val('temp')-20)/40)*val('stir'));text='Waktu model: '+fmt(t,1)+' s. Ukuran='+val('size')+', suhu='+val('temp')+' °C, pengadukan='+val('stir')+'. Ini prediksi model, bukan pengukuran nyata.';viz=bars([['Waktu (s)',t,1200]])}
 if(s==='green'){const total=val('input'),p=val('prod'),w=total-p;text='Limbah '+fmt(w)+' kg; E-factor '+fmt(w/p)+' kg/kg; PMI '+fmt(total/p)+' kg/kg; intensitas energi '+fmt(val('energy')/p)+' kWh/kg produk. Semua masukan dihitung pada batas sistem yang sama.';viz=bars([['Produk (kg)',p,total],['Limbah (kg)',w,total]])}
 if(s==='atom'){const p=val('p'),n=val('n'),c=val('charge'),e=p-c;if(e<0){text='Muatan tidak mungkin untuk model ini: jumlah elektron akan negatif.'}else{text='Z='+p+', A='+(p+n)+', proton='+p+', neutron='+n+', elektron='+e+'. Massa rata-rata Cl≈'+fmt(35*val('abundance')/100+37*(100-val('abundance'))/100)+' u. Konfigurasi inti buatan tidak menyatakan kestabilan.';viz=bars([['Proton',p,25],['Neutron',n,25],['Elektron',e,25]])}}
 if(s==='laws'){const h=val('h'),o=val('o'),r=Math.min(h,o/8),water=9*r;text='H bereaksi '+fmt(r)+' g; O bereaksi '+fmt(8*r)+' g; air '+fmt(water)+' g; sisa H '+fmt(h-r)+' g dan O '+fmt(o-8*r)+' g. Neraca: '+fmt(h+o)+' = '+fmt(water)+' + '+fmt(h-r)+' + '+fmt(o-8*r)+' g.';viz=bars([['Air (g)',water,h+o],['Sisa H (g)',h-r,h+o],['Sisa O (g)',o-8*r,h+o]])}
 if(s==='mole'){const [m,name,entity,gas]=sel('substance').split('|'),n=val('mass')/Number(m);text=fmt(val('mass'))+' g '+name+' / '+m+' g mol⁻¹ = '+fmt(n,5)+' mol = '+(n*6.02214076e23).toExponential(4)+' '+entity+'. '+(gas==='yes'?'Volume gas ideal pada 0 °C, 1 atm = '+fmt(n*22.4)+' L.':'22,4 L/mol tidak dipakai untuk volume zat ini dalam keadaan lazimnya.');viz=bars([['Jumlah (mol)',n,Math.max(1,n)]])}
 if(s==='limiting'){const h=val('hydrogen')*val('purity')/100/2,o=val('oxygen')/32,x=Math.min(h/2,o),m=36*x;const limiting=Math.abs(h/2-o)<1e-9?'tepat stoikiometris, kedua pereaksi habis':h/2<o?'H₂ pembatas':'O₂ pembatas';text='nH₂='+fmt(h)+' mol; nO₂='+fmt(o)+' mol; ξ=min('+fmt(h/2)+', '+fmt(o)+')='+fmt(x)+' mol; '+limiting+'. Air teoritis '+fmt(m)+' g; aktual '+fmt(m*val('yield')/100)+' g; sisa H₂ '+fmt((h-2*x)*2)+' g; sisa O₂ '+fmt((o-x)*32)+' g; pengotor '+fmt(val('hydrogen')*(1-val('purity')/100))+' g.';viz=bars([['Air teoritis (g)',m,Math.max(m,1)],['Air aktual (g)',m*val('yield')/100,Math.max(m,1)]])}
 if(s==='waste'){const m=val('concentration')*val('volume'),left=m*(1-val('removal1')/100)*(1-val('removal2')/100),c=left/(val('volume')*val('dilution'));text='Massa awal '+fmt(m)+' mg; tersisih '+fmt(m-left)+' mg; tersisa '+fmt(left)+' mg; volume akhir '+fmt(val('volume')*val('dilution'))+' L; konsentrasi akhir '+fmt(c)+' mg/L. Pengenceran tidak mengubah massa tersisa. Hasil tidak menentukan keamanan air.';viz=bars([['Massa tersisih (mg)',m-left,m],['Massa tersisa (mg)',left,m]])}
 if(s==='nano'){const a=val('edge');text='S/V = 6/'+a+' = '+fmt(6/a,5)+' nm⁻¹. Untuk volume total 1 µm³, luas total = '+fmt(6000/a)+' µm². Emisi listrik proses = '+fmt(val('consumption')*val('carbon')/1000)+' kg CO₂e/kg H₂. Belum termasuk infrastruktur, bahan, distribusi, atau kebocoran.';viz=bars([['Luas total (µm²)',6000/a,6000]])}
 if(s==='formula'){const c=cations[val('cation')],a=anions[val('anion')],g=(x,y)=>y?g(y,x%y):x,d=g(c[1],a[1]),nc=a[1]/d,na=c[1]/d;const sub=n=>String(n).replace(/\d/g,x=>'₀₁₂₃₄₅₆₇₈₉'[x]);const part=(ion,n)=> (ion[3]&&n>1?'('+ion[0]+')':ion[0])+(n>1?sub(n):'');const formula=part(c,nc)+part(a,na);text=formula+' — '+c[2]+' '+a[2]+'. Rasio kation:anion='+nc+':'+na+'. Muatan '+nc+'×(+'+c[1]+') + '+na+'×(−'+a[1]+') = 0.';viz='<p class="big">'+formula+'</p>'}
 if(s==='safety'){const i=val('scenario'),sc=safety[i];if(i!==lastScenario){$('decision').replaceChildren(new Option('Pilih tindakan dahulu','-1'));sc.choices.forEach((x,j)=>$('decision').add(new Option(x,j)));lastScenario=i}const d=val('decision');text=sc.title+': '+(d<0?'Pilih tindakan untuk memeriksa keputusan.':(d===sc.correct?'Tepat. ':'Perlu diperbaiki. ')+sc.why);viz='<p class="big">'+(d<0?'?':d===sc.correct?'✓':'!')+'</p>'}
 if(s==='balance'){const i=val('reaction'),r=reactions[i];if(i!==lastReaction){$('coefficients').innerHTML=r.names.map((n,j)=>'<label>Koefisien '+n+'<input id="coeff'+j+'" type="number" min="1" max="12" step="1" value="1"></label>').join('');$('coefficients').querySelectorAll('input').forEach(e=>e.addEventListener('input',update));lastReaction=i}const cs=r.names.map((_,j)=>val('coeff'+j));if(cs.some(x=>!Number.isInteger(x)||x<1||x>12)){text='Gunakan koefisien bulat 1–12.'}else{const atoms=[...new Set(r.atoms.flatMap(Object.keys))],rows=atoms.map(a=>[a,r.atoms.reduce((t,x,j)=>t+(j<r.split?(x[a]||0)*cs[j]:0),0),r.atoms.reduce((t,x,j)=>t+(j>=r.split?(x[a]||0)*cs[j]:0),0)]),ok=rows.every(x=>x[1]===x[2]);text=r.names.map((n,j)=>(j===r.split?'→ ':j?' + ':'')+cs[j]+n).join('')+'. '+(ok?(cs.every((x,j)=>x===r.min[j])?'Setara dan paling sederhana.':'Setara; sederhanakan koefisien.'):'Belum setara.');viz='<table><tr><th>Unsur</th><th>Kiri</th><th>Kanan</th></tr>'+rows.map(x=>'<tr><td>'+x[0]+'</td><td>'+x[1]+'</td><td>'+x[2]+'</td></tr>').join('')+'</table>'}}
 if(s==='particles'){const kind=sel('kind'),state=sel('state');text='Jenis: '+$('kind').selectedOptions[0].textContent+'; keadaan: '+$('state').selectedOptions[0].textContent+'. Gambar skematis, tidak berskala. Identitas partikel tidak berubah karena perubahan keadaan.';let circles='';for(let i=0;i<18;i++){const gap=state==='solid'?38:state==='liquid'?43:66,x=30+(i%6)*gap,y=35+Math.floor(i/6)*(state==='gas'?70:45)+(state==='liquid'?(i%2)*10:0),type=kind==='mix'?(i%2?'water':'oxygen'):kind;circles+='<g><circle cx="'+x+'" cy="'+y+'" r="9" fill="#a78bfa"/>'+(type==='oxygen'?'<circle cx="'+(x+14)+'" cy="'+y+'" r="9" fill="#a78bfa"/>':type==='water'?'<circle cx="'+(x-10)+'" cy="'+(y+10)+'" r="5" fill="#34d399"/><circle cx="'+(x+10)+'" cy="'+(y+10)+'" r="5" fill="#34d399"/>':'')+'</g>'}viz='<svg viewBox="0 0 420 225" role="img" aria-label="Susunan partikel skematis">'+circles+'</svg><p>Ungu: atom unsur utama; hijau: atom H pada model H₂O.</p>'}
 lastResult=text;$('result').textContent=text;$('visual').innerHTML=viz;
 document.querySelectorAll('[data-value]').forEach(e=>e.textContent=$(e.dataset.value).value);
}
function save(){if(window.PortalSubmission?.isFinal())return;try{const d={};document.querySelectorAll('[data-answer]').forEach(e=>d[e.id]=e.value);localStorage.setItem(STORAGE_KEY,JSON.stringify(d));$('draft-status').textContent='Draf tersimpan pada perangkat.'}catch(_){$('draft-status').textContent='Draf belum tersimpan. Penyimpanan browser tidak tersedia.'}}
function start(){setup();try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');Object.entries(d).forEach(([id,v])=>{if($(id)&&$(id).hasAttribute('data-answer'))$(id).value=v})}catch(_){}$('student-date').value=new Date().toLocaleDateString('id-ID');document.querySelectorAll('[data-answer]').forEach(e=>e.addEventListener('input',save));document.querySelectorAll('#controls input').forEach(e=>e.addEventListener('input',update));$('record').onclick=()=>{if(window.PortalSubmission?.isFinal()||$('lks-observasi').disabled)return;const inputs=[...$('controls').querySelectorAll('input,select')].map(e=>e.id+'='+e.value).join('; ');$('lks-observasi').value+=($('lks-observasi').value?'\n\n':'')+inputs+'\n'+lastResult;save()};}
document.addEventListener('DOMContentLoaded',start);
