'use strict';
const $=id=>document.getElementById(id),val=id=>Number($(id).value),fmt=(x,d=4)=>Number(x).toLocaleString('id-ID',{maximumFractionDigits:d});
const measured=x=>Math.abs(x)>0&&Math.abs(x)<1e-5?x.toExponential(4):fmt(x,8);
const escapeLab=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function acidPH(total,ka,strong=0){let lo=-16,hi=2;for(let i=0;i<160;i++){const m=(lo+hi)/2,h=10**m;if(h+strong-1e-14/h-total*ka/(ka+h)>0)hi=m;else lo=m}return-(lo+hi)/2}
function strongPH(excess){const root=Math.hypot(excess,2e-7),h=excess>=0?(excess+root)/2:2e-14/(root-excess);return-Math.log10(h)}
function binding(a,b,k){let lo=0,hi=Math.min(a,b);for(let i=0;i<90;i++){const x=(lo+hi)/2;if(x>k*(a-x)*(b-x))hi=x;else lo=x}return(lo+hi)/2}
function esterEq(a,b){let lo=0,hi=Math.min(a,b);for(let i=0;i<90;i++){const x=(lo+hi)/2;if(x*x>4*(a-x)*(b-x))hi=x;else lo=x}return(lo+hi)/2}
function titrationPH(v,weak){const volume=(25+v)/1000,total=.0025/volume,na=.1*v/1000/volume;return weak?acidPH(total,1.8e-5,na):strongPH(total-na)}
const F=96485;
function evaluateLab(id,p){let summary='',rows=[],color='#a78bfa',kind='beaker',level=.55,graph=null,valid=true;const put=(label,value,unit='')=>rows.push([label,value,unit]);
if(id==='keselamatan'){const correct={spill:'report',heat:'away',waste:'collect'}[p.scenario],ok=p.action===correct&&p.ppe==='full';summary=ok?'Keputusan sesuai skenario dan APD. Jelaskan alasan serta pengendalian risikonya.':'Keputusan perlu diperbaiki: '+(p.ppe!=='full'?'lengkapi APD. ':'')+(p.action!==correct?{spill:'Jauhi tumpahan dan laporkan kepada guru.',heat:'Arahkan mulut tabung menjauh dari orang.',waste:'Ikuti wadah limbah berlabel dan petunjuk guru.'}[p.scenario]:'');put('Keputusan sesuai',ok?'Ya':'Belum');kind='safety';color=ok?'#34d399':'#fbbf24'}
if(id==='pengukuran'){const scale=Number(p.scale),read=Math.round((p.volume+p.parallax)/scale)*scale;put('Pembacaan',read,'mL');put('Acuan',p.volume,'mL');put('Bias aktual',read-p.volume,'mL');put('Ketidakpastian skala ±',scale/2,'mL');summary='Baca dasar meniskus sejajar mata. Pembulatan memakai skala yang dipilih; bias paralaks bukan ketidakpastian acak.';kind='cylinder';level=read/50}
if(id==='pemisahan'){const match={sand:'filter',salt:'crystal',liquid:'distill'}[p.mixture]===p.method;summary=match?'Metode sesuai tujuan pemisahan. '+(p.mixture==='liquid'?'Fraksi lebih kaya etanol, tidak dijamin murni.':'Hitung rendemen dan jelaskan kemungkinan kehilangan.'):'Metode tidak mencapai tujuan model; bandingkan ukuran partikel, kelarutan, dan volatilitas.';put('Metode sesuai',match?'Ya':'Belum');if(p.mixture!=='liquid'&&match)put('Target padat terkumpul',10*p.recovery/100,'g');else if(match)put('Pemulihan fraksi asumsi',p.recovery,'%');kind=p.method==='filter'?'filter':p.method==='distill'?'distill':'beaker';valid=match}
if(id==='larutan'){const n=p.target*p.volume/1000,actual=n/((p.volume+p.error)/1000);put(p.mode==='solid'?'NaCl ditimbang':'Stok0,5M dipipet',p.mode==='solid'?n*58.5:n/.5*1000,p.mode==='solid'?'g':'mL');put('Volume akhir aktual',p.volume+p.error,'mL');put('Konsentrasi aktual',actual,'M');put('Bias relatif',100*(actual-p.target)/p.target,'%');summary='Larutkan/pindahkan kuantitatif, tambah air sampai volume akhir, lalu homogenkan.';kind='flask';level=.5+p.error/100}
if(id==='titrasi'){const ph=titrationPH(p.volume,p.acid==='weak'),low=p.indicator==='pp'?8.2:3.1,high=p.indicator==='pp'?10:4.4;put('NaOH terpakai',p.volume,'mL');put('pH',ph);put('Volume ekuivalen',25,'mL');put('C jika volume dianggap titik akhir',.1*p.volume/25,'M');summary=(p.volume<25?'Sebelum ekuivalen.':p.volume===25?'Tepat ekuivalen.':'Sesudah ekuivalen.')+' Indikator: '+(p.indicator==='pp'?(ph<low?'tak berwarna':ph>high?'merah muda kuat':'merah muda transisi'):(ph<low?'merah':ph>high?'kuning':'jingga transisi'))+'.';kind='burette';level=p.volume/50;color=p.indicator==='pp'?(ph<low?'#d4d4d8':'#f472b6'):(ph<low?'#f87171':ph>high?'#fde047':'#fb923c');graph={points:Array.from({length:101},(_,i)=>[i/2,titrationPH(i/2,p.acid==='weak')]),x:'NaOH (mL)',y:'pH',min:0,max:14}}
if(id==='buffer'){const ph=acidPH(.2,1.8e-5,.1+p.added/.1/1000);put('Tambahan kuat',p.added,'mmol; +basa/−asam');put('pH',ph);put('Kapasitas stoikiometri terlampaui',Math.abs(p.added)>10?'Ya':'Belum');summary='Volume tetap100mL; reaksi tambahan kuat dan kesetimbangan asam lemah diperhitungkan.';graph={points:Array.from({length:61},(_,i)=>{const a=-15+i*.5;return[a,acidPH(.2,1.8e-5,.1+a/.1/1000)]}),x:'Tambahan basa/asam (mmol)',y:'pH',min:0,max:14}}
if(id==='kalorimetri'){const q=57000*p.amount*(1-p.loss/100),delta=q/(418+p.capacity);put('Suhu awal',25,'°C');put('Suhu akhir',25+delta,'°C');put('ΔT',delta,'°C');put('Kalor diterima',q,'J');put('ΔH terukur',-q/p.amount/1000,'kJ/mol');summary='Larutan100g,c4,18J/gK. Kalor hilang tidak ikut dalam suhu yang terukur.';kind='calorimeter';color='#fb923c'}
if(id==='kinetika'){const k=.02*Math.exp(40000/8.314*(1/300-1/p.temp))*Number(p.area)*Number(p.catalyst),left=p.initial*Math.exp(-k*p.time);put('k model',k,'s⁻¹');put('[A] tersisa',left,'M');put('Laju awal',k*p.initial,'M/s');put('Laju saat pengamatan',k*left,'M/s');summary='Suhu,area,katalis mengubah k empiris. Gunakan perbandingan satu variabel per percobaan.';graph={points:Array.from({length:61},(_,i)=>[i*2,p.initial*Math.exp(-k*i*2)]),x:'Waktu (s)',y:'[A] (M)',min:0,max:p.initial};level=left/p.initial}
if(id==='kesetimbangan'){const k=1000*Math.exp(20000/8.314*(1/p.temp-1/300)),x=binding(p.fe/1000,p.scn/1000,k);put('K model',k,'M⁻¹');put('FeSCN²⁺',x*1000,'mmol/L');put('Fe³⁺ sisa',p.fe-x*1000,'mmol/L');put('SCN⁻ sisa',p.scn-x*1000,'mmol/L');summary='Intensitas merah relatif mengikuti kompleks; K danΔH merupakan parameter ilustratif.';color='#ef4444';level=.2+.7*x/.002}
if(id==='kelarutan'){const ag=10**p.silver,cl=Math.max(0,.01-1.8e-10/ag),iod=Math.max(0,.01-8.3e-17/ag);put('Ag⁺ bebas',ag,'M');put('Cl⁻ mengendap',cl/.01*100,'%');put('I⁻ mengendap',iod/.01*100,'%');put('Ambang AgCl',1.8e-8,'M');put('Ambang AgI',8.3e-15,'M');summary='Ag⁺ bebas dipertahankan model; Ag total ditambahkan tidak sama dengan nilai ini.';kind='precipitate';color='#fde68a';level=(cl+iod)/.02}
if(id==='volta'){const E={Zn:-.76,Cu:.34,Ag:.80},anode=E[p.left]<=E[p.right]?p.left:p.right,cathode=anode===p.left?p.right:p.left,diff=Math.abs(E[p.left]-E[p.right]);put('E standar pasangan',diff,'V');put('Anode',diff?anode:'Tidak ada beda potensial');put('Katode',diff?cathode:'Tidak ada beda potensial');put('Rangkaian berkelanjutan',p.bridge==='yes'&&diff>0?'Tersambung':'Tidak');summary=diff?'Elektron melalui kabel: '+anode+' → '+cathode+'. '+(p.bridge==='yes'?'Ion jembatan menjaga netralitas.':'Tanpa jembatan, arus tidak bertahan; E standar pasangan tetap sifat termodinamika.'):'Elektroda sama pada kondisi sama memberi E nol.';kind='cell';level=diff/1.56}
if(id==='elektrolisis'){const q=p.current*p.time,n=q/F;put('Muatan',q,'C');put('Mol elektron',n,'mol');put('Massa Cu katode',n/2*63.55,'g');put(p.anode==='copper'?'Cu anode larut':'O₂ anode',p.anode==='copper'?n/2*63.55:n/4,p.anode==='copper'?'g':'mol');summary='Cu²⁺ berlebih, efisiensi arus100%. Katode reduksi, anode oksidasi.';kind='electrolytic';color='#fb923c'}
if(id==='permanganometri'){const ratio=p.analyte==='iron'?5:2.5,vEq=.0025/ratio/.02*1000,used=.02*p.volume/1000;put('Ekuivalen',vEq,'mL');put('Analit tersisa',Math.max(0,.0025-ratio*used)*1000,'mmol');put('MnO₄⁻ berlebih',Math.max(0,used-.0025/ratio)*1000,'mmol');put('C jika dianggap titik akhir',ratio*.02*p.volume/25,'M');summary=p.volume<vEq?'Warna titran habis dalam model reaksi sempurna.':p.volume===vEq?'Ekuivalen stoikiometri; warna persisten membutuhkan sedikit kelebihan titran.':'Permanganat berlebih: warna ungu/merah muda tersisa.';kind='burette';level=p.volume/65;color=p.volume>vEq?'#c084fc':'#d4d4d8'}
if(id==='gravimetri'){const ideal=.2*143.32/35.45,measured=ideal*p.recovery/100+p.water,percent=100*measured*35.45/143.32;put('AgCl ideal',ideal,'g');put('Massa ditimbang',measured,'g');put('Kadar Cl terhitung',percent,'%');put('Bias',percent-20,'poin persentase');summary='Tara wadah diasumsikan benar. Massa tambahan dianggap keliru seluruhnya sebagai AgCl.';kind='balance';level=measured}
if(id==='spektro'){const a=.1*p.concentration+.02+(p.cuvette==='dirty'?.05:0),corrected=a-(p.blank==='yes'?.02:0),c=corrected/.1;put('Absorbansi mentah',a);put('Absorbansi dipakai',corrected);put('Kadar terhitung larutan ukur',c,'mg/L');put('Kadar asal terhitung',c*p.dilution,'mg/L');summary=(c>8?'Di luar rentang kalibrasi; encerkan dan ukur kembali. ':'Dalam rentang standar. ')+(p.blank==='no'?'Mengabaikan intersep/blanko saat memakai slope menimbulkan bias. ':'Blanko dikoreksi. ');kind='cuvette';level=Math.min(1,a);graph={points:[0,2,4,6,8].map(x=>[x,.1*x+.02]),x:'Standar (mg/L)',y:'A mentah',min:0,max:1}}
if(id==='kromatografi'){valid=p.baseline==='above';const rf=p.solvent==='one'?[.3,.7]:[.6,.8];put('Pengembangan valid',valid?'Ya':'Tidak: garis asal terendam');if(valid){put('Bercak A',rf[0]*p.front,'cm');put('Bercak B',rf[1]*p.front,'cm');put('Rf A',rf[0]);put('Rf B',rf[1])}summary=valid?'Jarak diukur dari garis asal, bukan tepi kertas. Rf model tidak menyatakan identitas unik.':'Sampel dapat larut ke reservoir; jangan laporkan Rf sebagai hasil sah.';kind='chromatogram';level=p.front/10;graph={rf:valid?rf:[],front:p.front}}
if(id==='gugus'){const positive={bromine:['alkene'],dnph:['aldehyde','ketone'],tollens:['aldehyde'],carbonate:['acid']}[p.reagent].includes(p.sample),description={bromine:'bromin memudar',dnph:'endapan derivat karbonil',tollens:'cermin/endapan perak',carbonate:'gelembung CO₂'}[p.reagent];put('Hasil',positive?'Positif: '+description:'Negatif pada sampel model');summary='Aliquot segar untuk setiap uji. Gabungan uji diperlukan; hasil berlaku hanya untuk kandidat sederhana ini.';kind='tube';color=positive?'#fbbf24':'#a1a1aa'}
if(id==='esterifikasi'){const eq=esterEq(p.acid,p.alcohol),k=p.catalyst==='yes'?.06:.02,x=eq*(1-Math.exp(-k*p.time));put('Ester terbentuk',x,'mol');put('Air terbentuk',x,'mol');put('Asam tersisa',p.acid-x,'mol');put('Batas ester setimbang model',eq,'mol');put('Hasil relatif pereaksi pembatas',100*x/Math.min(p.acid,p.alcohol),'%');summary='Aroma ester hanya deskripsi karakter umum; jangan menghirup pereaksi. Pendekatan waktu empiris, K tidak berubah oleh katalis.';kind='reflux';graph={points:Array.from({length:61},(_,i)=>[i*5,eq*(1-Math.exp(-k*i*5))]),x:'Waktu model (s)',y:'Ester (mol)',min:0,max:Math.min(p.acid,p.alcohol)}}
if(id==='makanan'){valid=p.test!=='benedict'||p.heat==='yes';const match={benedict:['glucose','mix'],iodine:['starch'],biuret:['protein','mix'],lipid:['oil','mix']}[p.test].includes(p.sample),desc={benedict:'endapan jingga/merah bata model',iodine:'biru kehitaman',biuret:'ungu',lipid:'emulsi putih keruh'}[p.test];put('Hasil',!valid?'Belum dapat dinilai: kondisi pemanasan Benedict belum terpenuhi':match?'Positif: '+desc:'Negatif pada model');summary='Bandingkan kontrol air; hasil kualitatif tidak mengukur kadar nutrisi.';kind='tube';color=valid&&match?{benedict:'#ea580c',iodine:'#312e81',biuret:'#a855f7',lipid:'#fafafa'}[p.test]:'#94a3b8'}
if(id==='koloid'){const coag=p.kind==='sol'&&p.salt>=10,stable=p.kind==='emulsion'?Math.exp(-p.time/(p.emulsifier==='yes'?60:5)):coag?0:1;put('Tyndall',p.kind==='solution'?'Tidak nyata pada model':'Ada pada partikel terdispersi');put('Koagulasi',coag?'Terjadi pada ambang model':'Tidak diprediksi');if(p.kind==='emulsion')put('Fraksi emulsi bertahan model',stable*100,'%');summary='Ambang garam dan kestabilan merupakan ilustrasi. Setelah koagulasi, pengamatan cahaya tidak setara sol awal.';kind='tyndall';level=stable;color=p.kind==='solution'?'#94a3b8':'#fef3c7'}
if(id==='nyala'){const palette={Na:['kuning','#fde047'],K:['lilac','#c084fc'],Ca:['merah jingga','#fb7185'],Ba:['hijau apel','#a3e635'],Cu:['hijau biru','#2dd4bf']},metal=p.clean==='yes'?p.metal:'Na';put('Warna',palette[metal][0]);put('Gangguan',p.clean==='yes'?'Tidak dalam model':'Na dominan; identifikasi target tidak dapat dipastikan');summary='Warna layar perkiraan dan tidak menunjukkan kadar. Bandingkan dengan kontrol kawat bersih.';kind='flame';color=palette[metal][1]}
if(id==='halogen'){const a=Number(p.oxidant),b=Number(p.halide),names=['Cl','Br','I'],reaction=a<b;summary=reaction?names[a]+'₂ + 2'+names[b]+'⁻ → 2'+names[a]+'⁻ + '+names[b]+'₂.':a===b?'Tidak ada perubahan bersih pasangan sama.':'Tidak terjadi penggantian menurut model urutan oksidator.';put('Penggantian',reaction?'Ya':'Tidak');put('Halogen dominan ilustratif',names[reaction?b:a]+'₂');put('Warna lapisan ilustratif',['kuning pucat','jingga','ungu'][reaction?b:a]);kind='layers';color=['#fef08a','#fb923c','#a855f7'][reaction?b:a]}
if(id==='air'){const profiles={one:[7,80,30,1,5],two:[6,200,100,10,20],three:[8,300,200,30,40]},index={ph:0,hardness:1,chloride:2,turbidity:3,nitrate:4}[p.test],v=profiles[p.sample][index],unit=['','mg/L sebagaiCaCO₃','mg/L Cl⁻','NTU','mg/L NO₃⁻'][index];put('Hasil parameter',v,unit);if(p.test==='hardness')put('EDTA0,010M untuk50mL',v*.05/1000/100/.01*1000,'mL');summary='Profil sintetis. Tidak mengukur mikroba/semua kontaminan; tidak menyimpulkan aman diminum.';kind='meter'}
if(id==='misteri'){const candidates={A:'glucose',B:'chloride',C:'starch',D:'carbonate'},yes={acid:'carbonate',iodine:'starch',benedict:'glucose',chloride:'chloride'}[p.test]===candidates[p.sample];put('Kode sampel',p.sample);put('Hasil',yes?'Positif':'Negatif');put('Biaya uji',2,'kredit');summary='Hasil berlaku pada kandidat terbatas dan kondisi selektif model. Gabungkan bukti untuk menyimpulkan identitas; catat alasan eliminasi.';kind='tube';color=yes?'#fbbf24':'#94a3b8'}
return{summary,rows,color,kind,level,graph,valid};}
function chart(g){const points=g.points,xmin=points[0][0],xmax=points[points.length-1][0];return '<svg viewBox="0 0 440 245" role="img" aria-label="'+escapeLab(g.y+' terhadap '+g.x)+'"><path d="M45 25V185H405" fill="none" stroke="#a1a1aa"/><polyline fill="none" stroke="#a78bfa" stroke-width="3" points="'+points.map(([x,y])=>(45+360*(x-xmin)/(xmax-xmin))+','+(185-150*(y-g.min)/(g.max-g.min))).join(' ')+'"/><g fill="#fafafa" font-size="12"><text x="45" y="17">'+escapeLab(g.y)+': '+fmt(g.min)+'–'+fmt(g.max)+'</text><text x="45" y="220">'+escapeLab(g.x)+': '+fmt(xmin)+'–'+fmt(xmax)+'</text></g></svg>'}
function apparatus(r){const c=r.color,level=Math.max(.05,Math.min(.95,r.level)),liquid='<path d="M105 110H235V220Q170 240 105 220Z" fill="'+c+'" opacity=".6"/>',beaker='<path d="M100 65V220Q170 245 240 220V65" stroke="#d4d4d8" fill="none" stroke-width="3"/>'+liquid;let drawing=beaker;
if(r.kind==='tube'||r.kind==='layers'||r.kind==='precipitate')drawing='<path d="M140 40V210Q170 250 200 210V40" fill="none" stroke="#d4d4d8" stroke-width="3"/><path d="M144 130H196V207Q170 242 144 207Z" fill="'+c+'" opacity=".8"/>'+(r.kind==='precipitate'&&r.level>0?'<path d="M147 208Q170 242 193 208Z" fill="#fef3c7"/>':'');
if(r.kind==='cylinder')drawing='<path d="M140 25V225H205V25M125 230H220" fill="none" stroke="#d4d4d8" stroke-width="3"/><rect x="143" y="'+(225-level*195)+'" width="59" height="'+(level*195)+'" fill="'+c+'" opacity=".5"/>'+Array.from({length:10},(_,i)=>'<path d="M190 '+(225-i*20)+'H205" stroke="white"/>').join('');
if(r.kind==='burette')drawing='<path d="M160 15V112H180V15M170 112V145M155 120H185" stroke="white" fill="none" stroke-width="3"/><rect x="163" y="'+(20+level*85)+'" width="14" height="'+(85*(1-level))+'" fill="#a78bfa"/><path d="M150 155V175L115 235H225L190 175V155" fill="none" stroke="white" stroke-width="3"/><path d="M137 200H203L221 232H119Z" fill="'+c+'" opacity=".65"/>';
if(r.kind==='flask')drawing='<path d="M155 30V130Q90 155 115 215Q170 250 225 215Q250 155 185 130V30M150 90H190" fill="none" stroke="white" stroke-width="3"/><path d="M126 170H214Q241 211 210 223H130Q99 211 126 170" fill="'+c+'" opacity=".6"/>';
if(r.kind==='filter')drawing='<path d="M100 35H240L180 125V165H160V125Z" fill="none" stroke="white" stroke-width="3"/><path d="M110 45H230L170 110Z" fill="#a78bfa" opacity=".5"/><path d="M115 175V230H225V175" fill="none" stroke="white" stroke-width="3"/>';
if(r.kind==='balance')drawing='<rect x="80" y="145" width="180" height="85" rx="12" fill="#27272a" stroke="white"/><rect x="110" y="165" width="120" height="40" fill="#09090b"/><text x="170" y="193" text-anchor="middle" fill="#34d399">'+fmt(r.level)+' g</text><path d="M110 120Q170 145 230 120V140H110Z" fill="'+c+'"/>';
if(r.kind==='cell')drawing='<path d="M40 115V235H145V115M205 115V235H310V115" fill="none" stroke="white" stroke-width="3"/><path d="M75 190V60H265V190" fill="none" stroke="#a78bfa" stroke-width="7"/>'+(r.rows.find(x=>x[0]==='Rangkaian berkelanjutan')?.[1]==='Tersambung'?'<path d="M120 155V95Q175 50 230 95V155" fill="none" stroke="#34d399" stroke-width="7"/>':'')+'<text x="175" y="28" fill="white" text-anchor="middle">Elektroda • rangkaian • elektrolit</text>';
if(r.kind==='electrolytic')drawing=beaker+'<path d="M130 195V50H210V195" fill="none" stroke="#d4d4d8" stroke-width="7"/><rect x="145" y="30" width="50" height="40" fill="#27272a" stroke="#a78bfa"/><text x="170" y="56" text-anchor="middle" fill="white">DC</text>';
if(r.kind==='calorimeter')drawing='<rect x="90" y="95" width="160" height="140" rx="12" stroke="white" fill="#27272a"/>'+liquid+'<path d="M75 85H260M195 30V200" stroke="white" stroke-width="5"/><circle cx="195" cy="203" r="10" fill="'+c+'"/>';
if(r.kind==='reflux'||r.kind==='distill')drawing='<circle cx="120" cy="195" r="42" fill="'+c+'" opacity=".7"/><path d="M105 160V25H135V160M95 40H145M95 60H145M95 80H145M95 100H145" fill="none" stroke="white" stroke-width="3"/>'+(r.kind==='distill'?'<path d="M135 45L270 135V180M235 180V235H305V180" fill="none" stroke="white" stroke-width="3"/>':'<text x="180" y="100" fill="white">Uap ↑</text><text x="180" y="130" fill="white">Kondensat ↓</text>');
if(r.kind==='flame')drawing='<path d="M155 235V195H185V235" fill="#71717a"/><path d="M170 190Q100 140 175 30Q140 110 210 130Q235 165 170 190" fill="'+c+'"/>';
if(r.kind==='cuvette'||r.kind==='meter')drawing='<rect x="70" y="40" width="220" height="190" rx="12" fill="#27272a" stroke="white"/><rect x="145" y="90" width="50" height="110" stroke="white" fill="'+c+'" opacity=".6"/><path d="M90 145H145M195 145H270" stroke="#34d399" stroke-width="5"/><text x="180" y="70" text-anchor="middle" fill="white">Pembaca instrumen</text>';
if(r.kind==='tyndall')drawing=beaker+'<path d="'+(r.rows.find(x=>x[0]==='Tyndall')?.[1]==='Tidak nyata pada model'?'M40 150H100M240 150H300':'M40 150H300')+'" stroke="#fbbf24" stroke-width="4" opacity="'+(r.level||.1)+'"/>';
if(r.kind==='safety')drawing='<path d="M170 30L290 230H50Z" fill="none" stroke="'+c+'" stroke-width="5"/><text x="170" y="190" font-size="90" text-anchor="middle" fill="'+c+'">!</text>';
if(r.kind==='chromatogram')drawing='<rect x="95" y="20" width="150" height="220" fill="#27272a" stroke="white"/><path d="M100 220H240" stroke="white"/><path d="M100 '+(220-180*r.level)+'H240" stroke="#38bdf8" stroke-dasharray="5 4"/>'+r.graph.rf.map((v,i)=>'<ellipse cx="'+(145+i*55)+'" cy="'+(220-180*r.level*v)+'" rx="14" ry="8" fill="'+['#a78bfa','#34d399'][i]+'"/>').join('')+'<text x="260" y="225" fill="white">Asal</text><text x="260" y="'+(220-180*r.level)+'" fill="white">Front</text>';
return '<svg viewBox="0 0 360 270" role="img" aria-label="Skema alat virtual '+escapeLab(r.kind)+'">'+drawing+'</svg><p class="hint">Skema alat dan warna bersifat ilustratif. Gunakan tabel untuk nilai pengukuran.</p>';
}
let labState={version:1,entries:[],credits:8},lastRun=null;
function finalLocked(){return Boolean(window.PortalSubmission?.isFinal())}
function readParams(){const p={};document.querySelectorAll('#controls input,#controls select').forEach(e=>p[e.id]=e.type==='range'?Number(e.value):e.value);return p}
function labJournal(){return labState.entries.map((e,i)=>'Percobaan '+(i+1)+' | '+e.time+'\nKondisi: '+JSON.stringify(e.params)+'\n'+e.result.rows.map(([k,v,u])=>k+': '+(typeof v==='number'?measured(v):v)+(u?' '+u:'')).join('\n')+'\n'+e.result.summary).join('\n\n')}
function save(){if(finalLocked())return;try{const d={};document.querySelectorAll('[data-answer]').forEach(e=>d[e.id]=e.value);localStorage.setItem(STORAGE_KEY,JSON.stringify(d));localStorage.setItem(STORAGE_KEY+'_lab',JSON.stringify(labState));$('draft-status').textContent='Draf dan jurnal praktikum tersimpan pada perangkat.'}catch(_){$('draft-status').textContent='Penyimpanan perangkat gagal. Salin catatan sebelum menutup halaman.'}}
function renderHistory(){const table=$('lab-history');table.innerHTML='<table><caption>Riwayat '+labState.entries.length+' percobaan</caption><thead><tr><th>No.</th><th>Kondisi</th><th>Pengamatan utama</th></tr></thead><tbody>'+labState.entries.map((e,i)=>'<tr><td>'+(i+1)+'</td><td>'+escapeLab(Object.entries(e.params).map(([k,v])=>k+'='+v).join('; '))+'</td><td>'+escapeLab(e.result.rows.map(([k,v,u])=>k+': '+(typeof v==='number'?measured(v):v)+' '+u).join('; '))+'</td></tr>').join('')+'</tbody></table>';$('lks-journal').value=labJournal();if(TOPIC.sim==='misteri')$('lab-credit').textContent='Sisa anggaran: '+labState.credits+' kredit. Tiap uji memakai2kredit.'}
function update(){lastRun=null;$('result').textContent='Kondisi diubah. Jalankan percobaan untuk mendapatkan hasil baru.';$('visual').innerHTML='';document.querySelectorAll('[data-value]').forEach(e=>e.textContent=$(e.dataset.value).value)}
function runExperiment(){if(finalLocked()||$('lks-observasi').disabled)return;if(![...document.querySelectorAll('.lab-step')].every(e=>e.checked)){$('result').textContent='Selesaikan dan centang tiga langkah persiapan terlebih dahulu.';return}if(labState.entries.length>=100){$('result').textContent='Jurnal sudah memuat 100 percobaan. Gunakan data yang ada untuk laporan.';return}if(TOPIC.sim==='misteri'&&labState.credits<2){$('result').textContent='Anggaran uji habis. Gunakan bukti dalam jurnal untuk menyimpulkan.';return}const params=readParams(),result=evaluateLab(TOPIC.sim,params);if(TOPIC.sim==='misteri')labState.credits-=2;lastRun={params,result,time:new Date().toLocaleString('id-ID')};labState.entries.push(lastRun);$('result').textContent=result.summary;$('visual').innerHTML=apparatus(result)+(result.graph?.points?chart(result.graph):'')+'<table><caption>Hasil percobaan</caption><tbody>'+result.rows.map(([k,v,u])=>'<tr><th>'+escapeLab(k)+'</th><td>'+escapeLab(typeof v==='number'?(Math.abs(v)>0&&Math.abs(v)<1e-5?v.toExponential(4):fmt(v,6)):v)+' '+escapeLab(u)+'</td></tr>').join('')+'</tbody></table>';renderHistory();save()}
function clearFinalLab(){if(!finalLocked())return;labState={version:1,entries:[],credits:8};lastRun=null;$('lab-history').innerHTML='Jurnal perangkat telah dihapus setelah penyimpanan final dikonfirmasi.';$('lks-journal').value='';$('visual').innerHTML='';$('result').textContent='Praktikum sudah dikumpulkan dan dikunci.';$('lab-credit').textContent='';try{localStorage.removeItem(STORAGE_KEY+'_lab')}catch(_){}}
function start(){for(const [id,label,options] of TOPIC.selects){const l=document.createElement('label');l.textContent=label;const el=document.createElement('select');el.id=id;for(const [value,name]of options)el.add(new Option(name,value));l.append(el);$('controls').append(l)}
try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');Object.entries(d).forEach(([id,v])=>{if($(id)&&$(id).hasAttribute('data-answer'))$(id).value=v});const state=JSON.parse(localStorage.getItem(STORAGE_KEY+'_lab')||'null');if(state?.version===1&&Array.isArray(state.entries)&&state.entries.length<=100&&Number.isInteger(state.credits)&&state.credits>=0&&state.credits<=8)labState=state}catch(_){}
$('student-date').value=new Date().toLocaleDateString('id-ID');document.querySelectorAll('[data-answer]').forEach(e=>e.addEventListener('input',save));document.querySelectorAll('#controls input,#controls select').forEach(e=>e.addEventListener(e.type==='range'?'input':'change',update));$('lab-run').addEventListener('click',runExperiment);$('record').onclick=()=>{if(finalLocked()||$('lks-observasi').disabled)return;if(!lastRun){$('result').textContent='Jalankan kondisi saat ini sebelum menyalin pengamatan.';return}const text=lastRun.result.rows.map(([k,v,u])=>k+': '+(typeof v==='number'?measured(v):v)+' '+u).join('\n');$('lks-observasi').value+=($('lks-observasi').value?'\n\n':'')+JSON.stringify(lastRun.params)+'\n'+text+'\n'+lastRun.result.summary;save()};
if(['titrasi','permanganometri'].includes(TOPIC.sim)){const box=$('lab-dose');for(const step of [.05,1,5]){const b=document.createElement('button');b.type='button';b.textContent='Tambah '+fmt(step)+' mL';b.onclick=()=>{if(finalLocked()||$('volume').disabled)return;const el=$('volume');el.value=Math.min(Number(el.max),Math.round((Number(el.value)+step)*100)/100);update();runExperiment()};box.append(b)}}renderHistory();update();if(typeof MutationObserver!=='undefined')new MutationObserver(clearFinalLab).observe($('lks-journal'),{attributes:true,attributeFilter:['disabled']});clearFinalLab();}
document.addEventListener('DOMContentLoaded',start);


