const topics=[];
const range=(id,label,min,max,value,step=1)=>[id,label,min,max,value,step];
function prose(s){return s.replace(/([a-z]{3,})(?=[A-Z0-9])/g,'$1 ').replace(/(\d)(?=(?:mL|mmol|mol|mg|cm|kJ|J|g|s|K|M|V)\b)/g,'$1 ').replace(/,([A-Za-z])/g,', $1').replace(/;(\S)/g,'; $1').replaceAll('kesetimbanganmodel','kesetimbangan model').replaceAll('ujiemulsi','uji emulsi').replaceAll('untukpati','untuk pati').replaceAll('untukikatan','untuk ikatan').replaceAll('sampelberkode','sampel berkode').replaceAll('kartu uji,pipet','kartu uji, pipet').replaceAll('kontrolair','kontrol air').replaceAll('empat uji','empat uji').replaceAll('ujidan','uji dan').replaceAll('ujipalinginformatif','uji paling informatif').replaceAll('rumuskan hipotesis','rumuskan hipotesis').replaceAll('pHmeter','pH meter').replaceAll('penangas','penangas')}
function lab(id,title,apparatus,concept,limits,steps,controls,selects,lks,rubric,qs){
 apparatus=prose(apparatus);concept=prose(concept);limits=prose(limits);steps=steps.map(prose);lks=lks.map(prose);qs=qs.map(q=>q.map(prose));
 const questions=qs.concat([['Agar pengaruh satu variabel dapat disimpulkan, sebaiknya ...','ubah satu variabel dan kendalikan lainnya','ubah semua sekaligus','abaikan kontrol','pilih hasil yang disukai'],['Laporan praktikum yang baik memuat ...','kondisi, data, penalaran dan batas model','kesimpulan tanpa bukti','hanya jawaban teman','hanya angka tanpa satuan']]);
 const quiz=questions.map(([question,correct,...wrong],i)=>{const options=[correct,...wrong],k=i%4;for(let j=0;j<k;j++)options.unshift(options.pop());return{question,options,answer:k}});
 topics.push({id:'lab-'+id,file:'Lab_Virtual_'+id.replaceAll('-','_'),title:'Laboratorium Virtual '+title,sim:id,apparatus,limits,steps,controls,selects,lks,rubric,quiz,goals:['Melaksanakan alur praktikum virtual '+title,'Membandingkan kondisi dan mencatat pengamatan','Menjelaskan hasil beserta sumber kesalahan'],intro:'Siapkan alat virtual, tentukan kondisi, jalankan percobaan, lalu bandingkan hasil dalam jurnal praktikum.',task:'Selesaikan langkah persiapan, jalankan sedikitnya dua kondisi, lalu simpan pengamatan ke LKPD. Percobaan boleh diulang untuk belajar; jawaban evaluasi dan pengumpulan tetap final.',lessons:[['Konsep praktikum',concept],['Alat dan bahan virtual',apparatus],['Asumsi dan batas',limits],['Alur kerja',steps.join(' → ')]]});
}
lab('keselamatan','Keselamatan Laboratorium','Meja skenario, label bahaya, kacamata, jas, sepatu tertutup, wadah limbah.',
'Kenali bahaya sebelum mulai; APD melengkapi pengendalian risiko. Tumpahan tidak dikenal harus dijauhi dan dilaporkan kepada guru, bukan dinetralkan secara coba-coba. Limbah dipisahkan sesuai jenis dan prosedur sekolah.',
'Latihan keputusan untuk siswa; respons keadaan nyata mengikuti guru, SDS dan prosedur darurat sekolah.',
['Baca label dan skenario','Pilih APD sesuai aktivitas','Tentukan respons yang akan diuji'],[],
[['scenario','Skenario',[['spill','Tumpahan zat tak dikenal'],['heat','Pemanasan tabung'],['waste','Sisa larutan ion logam']]],['action','Respons',[['report','Jauhi area dan laporkan ke guru'],['away','Arahkan mulut tabung menjauh dari orang'],['collect','Masukkan ke wadah limbah berlabel sesuai petunjuk'],['sink','Tuang ke wastafel'],['touch','Sentuh atau hirup langsung']]],['ppe','APD',[['full','Kacamata, jas, sepatu tertutup'],['none','Tanpa APD lengkap']]]],
['Catat keputusan pada tumpahan dan jelaskan mengapa tidak mencoba menetralkannya sendiri.','Bandingkan respons pemanasan dengan pembuangan limbah logam.','Jelaskan mengapa APD lengkap tidak membuat semua tindakan menjadi aman.'],
'Spill report;heat away;waste collect;APDfull. Tolak sink/touch dan netralisasi improvisasi. APD bukan pengganti prosedur.',
[['Tumpahan tidak dikenal pertama-tama ...','jauhi dan laporkan','sentuh','campur basa','hirup'],['Mulut tabung dipanaskan diarahkan ...','menjauh dari orang','ke teman','ke wajah','ditutup rapat selalu'],['Limbah logam ...','ikuti wadah/prosedur yang ditetapkan','selalu ke wastafel','ke tanah','dicampur semua']]);
lab('pengukuran','Alat dan Pengukuran','Gelas ukur berskala, neraca, wadah tara.',
'Baca dasar meniskus cekung sejajar mata. Volume dari dua pembacaan buret diperoleh dari selisihnya. Neraca perlu tara; angka tampilan bukan jaminan akurasi tanpa kalibrasi.',
'Model menunjukkan bias paralaks yang sengaja diberikan dan ketelitian pembulatan; bukan model optik lengkap. Ketidakpastian skala analog memakai setengah skala terkecil.',
['Pilih skala ukur dan posisi mata','Tentukan volume acuan','Baca meniskus lalu bandingkan bias'],
[range('volume','Volume acuan (mL)',5,45,25,.1),range('parallax','Bias pembacaan model (mL)',-2,2,0,.1)],
[['scale','Skala terkecil',[['1','1mL'],['0.2','0,2mL']]]],
['Bandingkan pembacaan volume25mL dengan bias0 dan+1mL.','Bandingkan ketidakpastian skala1 dan0,2mL.','Jelaskan perbedaan ketelitian, akurasi dan fungsi tara.'],
'Baca25vs26;u±.5mLvs±.1mL;bias sistematis tidak hilang karena skala rapat. Tara mengurangi massa wadah.',
[['Meniskus dibaca ...','sejajar mata','dari atas selalu','dari bawah selalu','tanpa skala'],['Setengah skala0,2mL ...','0,1mL','0,2mL','1mL','2mL'],['Tara mengurangi ...','massa wadah','massa jenis','volume','jumlah mol']]);
lab('pemisahan','Pemisahan Campuran','Corong, kertas saring, bejana, kondensor konseptual, cawan kristalisasi.',
'Metode dipilih berdasarkan sifat campuran: filtrasi untuk padatan tak larut, distilasi untuk perbedaan volatilitas, kristalisasi untuk memperoleh zat terlarut. Filtrasi biasa tidak memisahkan garam terlarut dari air.',
'Rendemen pemulihan adalah parameter latihan, bukan prediksi efisiensi alat. Distilasi etanol-air tidak otomatis menghasilkan etanol murni karena azeotrop.',
['Pilih campuran dan tujuan pemisahan','Susun metode virtual','Atur pemulihan dan kumpulkan fraksi'],
[range('recovery','Pemulihan komponen target (%)',50,100,90)],
[['mixture','Campuran',[['sand','Pasir10g dalam air: ambil pasir'],['salt','Garam10g terlarut: ambil garam'],['liquid','Etanol-air: ambil fraksi lebih kaya etanol']]],['method','Metode',[['filter','Filtrasi'],['crystal','Kristalisasi'],['distill','Distilasi']]]],
['Bandingkan filtrasi pada pasir dan garam terlarut.','Hitung zat padat didapat jika target10g dan pemulihan90%.','Jelaskan mengapa fraksi distilasi tidak harus murni.'],
'sandfilter,saltcrystal,liquiddistill;90%10g=9g. Garam terlarut lolos filter;distilasi dipengaruhi kesetimbangan dan azeotrop.',
[['Pasir dipisahkan dengan ...','filtrasi','titrasi','netralisasi','elektrolisis'],['Garam terlarut lolos kertas saring?','ya','tidak selalu tertahan','menjadi pasir','menjadi gas'],['Pemulihan90% dari10g ...','9g','10g','0,9g','90g']]);
lab('larutan','Pembuatan dan Pengenceran Larutan','Neraca, spatula, labu ukur, pipet volumetrik, botol stok NaCl.',
'Larutan dibuat hingga volume akhir labu, bukan dengan menambah air sebanyak volume akhir. n=m/M dan C=n/V. Pengenceran memenuhi CstokVpipet=CakhirVakhir bila tidak ada reaksi atau kehilangan zat.',
'NaCl M58,5g/mol, volume aditif model. Bias volume merepresentasikan pengisian melewati/di bawah tanda; kemurnian dan suhu diabaikan.',
['Pilih pelarutan padat atau pengenceran','Hitung massa atau volume stok','Isi sampai tanda model dan homogenkan'],
[range('target','Konsentrasi target (M)',.02,.2,.1,.01),range('volume','Volume labu (mL)',100,500,250,50),range('error','Kesalahan volume akhir (mL)',-10,10,0,1)],
[['mode','Cara',[['solid','Timbang NaCl'],['stock','Encerkan stok0,5M']]]],
['Hitung massaNaCl dan volume stok0,5M untuk250mL0,1M.','Bandingkan kadar aktual ketika volume akhir250 dan260mL.','Jelaskan urutan pelarutan, pemindahan kuantitatif dan pengisian tanda.'],
'm1.4625g;Vstok50mL;C250=.1,C260=.0961538M. Larutkan sebelum tepatkan volume,homogenkan.',
[['MassaNaCl untuk0,025mol ...','1,4625g','0,025g','58,5g','14,625g'],['Volume akhir adalah ...','volume seluruh larutan','volume air saja','volume zat padat','massa'],['Kelebihan pelarut membuat C ...','turun','naik','tetap','negatif']]);
lab('titrasi','Titrasi Asam–Basa','BuretNaOH0,100M, pipet25mL, erlenmeyer, indikator, pH meter.',
'Titrasi menghubungkan volume titran dengan stoikiometri. HCl kuat dan asam asetat lemah0,100M masing-masing membutuhkan25mL NaOH0,100M untuk25mL aliquot. pH ekuivalennya berbeda.',
'Larutan ideal25°C, Ka asam asetat1,8×10⁻⁵. Kurva memakai keseimbangan muatan termasuk air. Warna indikator merupakan pendekatan rentang transisi.',
['Isi buret dan tetapkan pembacaan awal0mL','Pipet25mL asam serta pilih indikator','Tambahkan titran bertahap dan baca pH'],
[range('volume','NaOH terpakai (mL)',0,50,0,.05)],
[['acid','Analit',[['strong','HCl0,100M'],['weak','CH₃COOH0,100M']]],['indicator','Indikator',[['pp','Fenolftalein8,2–10'],['mo','Metil jingga3,1–4,4']]]],
['Catat pH sebelum, dekat dan sesudah25mL untuk dua asam.','Pilih indikator yang sesuai dan bedakan titik akhir/ekuivalen.','Jika titik akhir26mL, hitung C asam terukur dan arah kesalahan.'],
'Veq25;kuatpH7,lemah≈8.72;PPsesuai lemah-kuat,MOkurangsesuai.26mL=>.104M,tinggi4%.',
[['Titik ekuivalen ditentukan ...','stoikiometri','warna semata','bentuk labu','waktu'],['Asam lemah-basa kuat pH ekuivalen ...','lebih dari7','selalu7','kurang7','0'],['Volume26mL memberi C ...','0,104M','0,096M','1,04M','0,1M pasti']]);
lab('buffer','Larutan Penyangga','Bejana100mL asam asetat/asetat, pipet titran kuat, pH meter.',
'Pasangan asam lemah dan basa konjugat menahan perubahan pH melalui reaksi terhadap tambahan asam/basa. Ketahanan terbatas oleh jumlah masing-masing komponen; pengenceran dan penambahan besar tetap berpengaruh.',
'Mula-mula masing-masing10mmolHA danA⁻, volume100mL tetap sebagai penyederhanaan. Ka1,8×10⁻⁵; model kesetimbangan muatan digunakan saat komponen habis.',
['Siapkan pasanganHA/A⁻','Pilih jumlah asam atau basa tambahan','Aduk dan ukur pH'],
[range('added','Tambahan basa positif/asam negatif (mmol)',-15,15,0,1)],[],
['Bandingkan pH saat tambahan0,+5 dan−5mmol.','Amati penambahan±12mmol dan jelaskan batas kapasitas.','Mengapa buffer bukan berarti pH sama persis untuk semua penambahan?'],
'AwalpKa≈4.745;pH+5≈5.22;−5≈4.27. Kapasitas terlampaui saat>10mmol;gunakan stoikiometri dan kesetimbangan bukan HHdi luar kapasitas.',
[['Buffer memerlukan ...','asam lemah dan basa konjugat','asam kuat saja','air murni','logam'],['Tambah basa mengonsumsi ...','HA','Na⁺','air seluruhnya','elektron'],['Kapasitas buffer ...','terbatas','tak terbatas','selalu nol','sama semua konsentrasi']]);
lab('kalorimetri','Kalorimetri','Kalorimeter cangkir, termometer, larutanHCl/NaOH, pengaduk.',
'Kalor reaksi diterima larutan dan kalorimeter. qreaksi=−(mc+Ckal)ΔT. Koreksi kapasitas kalorimeter penting; kehilangan kalor membuat besar kalor terukur lebih kecil.',
'Netralisasi model melepas57kJ/mol; larutan100g,c4,18J/gK,Tawal25°C. Ckal dan fraksi kehilangan dapat diubah. Tidak memodelkan kinetika atau penguapan.',
['Tetapkan kapasitas kalorimeter hasil kalibrasi','Campur pereaksi ekuimolar','Baca suhu akhir dan hitungΔH'],
[range('amount','Mol netralisasi',.01,.1,.05,.01),range('capacity','Kapasitas kalorimeter (J/K)',0,100,20,5),range('loss','Kalor hilang (%)',0,40,0,5)],[],
['HitungΔT untuk0,05mol,Ckal20J/K tanpa kehilangan.','BandingkanΔH terukur pada kehilangan0% dan20%.','Jelaskan peran kalibrasi dan tanda negatifqreaksi.'],
'q2850J;ΔT2850/438≈6.50685;ΔH−57dan−45.6kJ/mol. Eksoterm negatif,kalorimeter menyerap.',
[['qreaksi eksoterm bertanda ...','negatif','positif selalu','nol','tanpa satuan'],['Ckal harus ...','diperhitungkan','selalu dihapus','diganti mol','dianggap suhu'],['Kalor hilang membuat |ΔH| terukur ...','lebih kecil','lebih besar pasti','tetap','tak hingga']]);
lab('kinetika','Laju Reaksi','Bejana reaksiA→produk, pengatur suhu, katalis, pencatat waktu.',
'Laju dipengaruhi konsentrasi dan konstanta laju. Model orde satu memberi[A]=[A]₀e^(−kt). Arrhenius menjelaskan pengaruh suhu; luas permukaan relevan untuk sistem heterogen.',
'Model A hipotetis dengan k300K=0,02s⁻¹,Ea40kJ/mol. Faktor area dan katalis adalah pengali empiris latihan, bukan data pereaksi tertentu; kesetimbangan tidak dihitung.',
['Tetapkan konsentrasi dan suhu','Pilih bentuk padatan model dan katalis','Mulai waktu virtual serta ukur sisaA'],
[range('initial','[A] awal (M)',.1,1,.5,.1),range('temp','Suhu (K)',280,330,300,5),range('time','Waktu (s)',0,120,30,5)],
[['area','Area relatif',[['1','Bongkah1×'],['2','Serbuk2×']]],['catalyst','Katalis',[['1','Tidak'],['3','Ada: laju model3×']]]],
['Bandingkan sisaA saat300K dan320K pada waktu sama.','Bedakan laju awal dengan konsentrasi yang tersisa.','Jelaskan mengapa faktor katalis model tidak menetapkan perubahanK kesetimbangan.'],
'k=.02exp(40000/R(1/300−1/T))*area*cat;A=A0e−kt. Katalis laju bukan ubahK;kontrol variabel lain.',
[['Orde satu satuan k ...','s⁻¹','M','mol','K'],['Suhu naik dalam model ...','menaikkan k','selalu menurunkan k','tidak berpengaruh','mengubah atom'],['Grafik[A] waktu ...','eksponensial','selalu linear','selalu naik','tak berubah']]);
lab('kesetimbangan','Pergeseran Kesetimbangan','TabungFe³⁺/SCN⁻, pipet, penangas, pembaca warna.',
'Fe³⁺+SCN⁻⇌FeSCN²⁺ menghasilkan kompleks berwarna merah. Perubahan konsentrasi dan suhu dapat menggeser komposisi. Warna mencerminkan konsentrasi, bukan langsung mol total.',
'K300K=1000M⁻¹ danΔH−20kJ/mol adalah parameter ilustratif. Spesies samping diabaikan; warna merah dihitung sebagai intensitas relatif.',
['Tetapkan konsentrasi awal kedua ion','Ubah satu konsentrasi atau suhu','Setimbangkan dan bandingkan warna'],
[range('fe','Fe³⁺ awal (mmol/L)',.1,2,1,.1),range('scn','SCN⁻ awal (mmol/L)',.1,2,1,.1),range('temp','Suhu (K)',280,330,300,5)],[],
['Bandingkan kompleks saatFe awal1 dan2mmol/L padaSCN tetap.','Prediksi efek pemanasan untukΔH negatif dan uji.','Bedakan pergeseran komposisi dengan perubahanK akibat konsentrasi.'],
'K berubah karenaT saja;menambahFe naikkonsentrasikompleks;pemanasaneksoterm menurunkanK. x=K(a−x)(b−x).',
[['Menambah Fe³⁺ umumnya ...','menambah kompleks','menghapusSCN','mengubahKpadasuhu tetap','menghentikan reaksi'],['Pemanasan reaksi maju eksoterm ...','menurunkanK','menaikkanK selalu','tidak pernah berpengaruh','membuatKnol'],['Warna terutama terkait ...','konsentrasi kompleks','nama tabung','massa kaca','waktu saja']]);
lab('kelarutan','Ksp dan Pengendapan Selektif','Bejana campuranCl⁻/I⁻, larutanAg⁺, pengaduk, filter virtual.',
'Endapan mulai terbentuk ketikaQ melebihiKsp. AgI memilikiKsp jauh lebih kecil daripadaAgCl, sehingga dapat mengendap lebih dahulu pada campuran konsentrasi sebanding.',
'Cl⁻ danI⁻ awal masing-masing0,01M;KspAgCl1,8×10⁻¹⁰ danAgI8,3×10⁻¹⁷. SliderAg⁺ bebas adalah kondisi setimbang yang dipertahankan, bukan volume titran.',
['Siapkan campuran halida','TetapkanAg⁺ bebas model','Setimbangkan dan pisahkan endapan'],
[range('silver','log₁₀[Ag⁺] bebas (M)',-16,-5,-10,.5)],[],
['Hitung ambangAg⁺ untuk dua endapan.','Bandingkan persenI⁻ danCl⁻ mengendap padaAg⁺10⁻¹⁰M.','Mengapa model tidak boleh dibaca sebagai volumeAgNO₃ yang ditambahkan?'],
'AmbangI8.3e−15,Cl1.8e−8. Ag1e−10=>I99.9917%,Cl0. Bebas bukan total,perlu neraca dan volume titran.',
[['Endapan terbentuk jika ...','Q>Ksp','Q<Ksp selalu','Q=0','tidak ada ion'],['Lebih dahulu pada kondisi ini ...','AgI','AgCl','keduanya tidak','NaCl'],['Ag⁺ bebas berbeda dengan ...','Ag total ditambahkan','satuanM','ion per liter','konsentrasi bebas']]);
lab('volta','Sel Volta','Dua elektroda, larutan ion1M, jembatan garam, kabel, voltmeter.',
'Elektroda dengan potensial reduksi lebih besar menjadi katode pada sel spontan. Esel=Ekatode−Eanode; elektron mengalir dari anode ke katode melalui rangkaian luar.',
'Kondisi standar25°C:Zn−0,76;Cu+0,34;Ag+0,80V. Model rangkaian terbuka jika jembatan dilepas; tidak menghitung polarisasi, hambatan atau Nernst.',
['Pilih pasangan elektroda dan larutan sesuai','Pasang kabel serta jembatan garam','Baca voltmeter dan arah elektron'],[],
[['left','Elektroda kiri',[['Zn','Zn/Zn²⁺'],['Cu','Cu/Cu²⁺'],['Ag','Ag/Ag⁺']]],['right','Elektroda kanan',[['Cu','Cu/Cu²⁺'],['Zn','Zn/Zn²⁺'],['Ag','Ag/Ag⁺']]],['bridge','Jembatan garam',[['yes','Terpasang'],['no','Dilepas']]]],
['Tentukan anode,katode,E dan arah elektron selZn/Cu.','BandingkanCu/Ag danZn/Ag.','Jelaskan fungsi jembatan dan beda elektron dengan aliran ion.'],
'ZnCuE1.10;CuAg.46;ZnAg1.56. Oksidasipotensialrendah,elektronluar ke katode;ion jembatan netralitas. Tanpajembatan tidakarus berkelanjutan.',
[['Anode berlangsung ...','oksidasi','reduksi','netralisasi saja','kondensasi'],['E standarZn/Cu ...','1,10V','0,42V','−1,10V spontan','2V'],['Jembatan menghantarkan ...','ion','elektron seperti kabel','proton saja','cahaya']]);
lab('elektrolisis','Elektrolisis dan Faraday','SumberDC, elektroda,CuSO₄, neraca, stopwatch.',
'Q=It; mol elektron=Q/F. Cu²⁺+2e⁻→Cu memerlukan dua mol elektron per molCu. ElektrodaCu aktif dapat larut di anode; anode inert pada modelCuSO₄ menghasilkanO₂ dari air.',
'F96485C/mol,MCu63,55g/mol,efisiensi100%,Cu²⁺ berlebih. Perbandingan elektroda berlaku padaCuSO₄ berair model; bukan aturan semua elektrolit.',
['Pilih jenis anode dan hubungkanDC','Tetapkan arus dan waktu','Elektrolisis lalu timbangCu katode'],
[range('current','Arus (A)',.1,3,1,.1),range('time','Waktu (s)',60,3600,600,60)],
[['anode','Anode',[['copper','Cu aktif'],['inert','Inert model']]]],
['Hitung massaCu pada1A600s.','Bandingkan perubahan anodeCu dengan anode inert.','Mengapa massa nyata dapat lebih kecil daripada prediksiFaraday?'],
'm600/96485/2*63.55≈.197596g;anodeCu larut setaramassa;inertO2=Q/4F. Efisiensi,reaksisamping,kehilangan.',
[['Q sama dengan ...','It','I/t','t/I','I+t'],['Cu²⁺ perlu elektron perCu ...','2','1','3','4'],['AnodeCu model mengalami ...','pelarutan','pengendapanCu','tanpa perubahan','produksiH₂']]);
lab('permanganometri','Titrasi Permanganometri','BuretKMnO₄0,020M, aliquot25mL Fe²⁺ atau oksalat0,100M, medium asam.',
'Dalam asam,1MnO₄⁻ setara5Fe²⁺ atau2,5C₂O₄²⁻. Titik akhir adalah sedikit kelebihan warna permanganat; ekuivalen ditentukan stoikiometri. Oksalat membutuhkan kondisi kinetika sesuai dalam eksperimen nyata.',
'Sampel standar latihan,reaksi diasumsikan selesai; keasaman cukup dan hambatan kinetika diabaikan. Ini bukan prosedur penanganan pereaksi nyata.',
['Pilih analit dan catat konsentrasi titran','Siapkan aliquot dalam kondisi asam model','Tambah titran sampai sekitar ekuivalen'],
[range('volume','KMnO₄ terpakai (mL)',0,65,25,.5)],
[['analyte','Analit',[['iron','Fe²⁺0,100M'],['oxalate','C₂O₄²⁻0,100M']]]],
['HitungVeq untukFe²⁺ dan oksalat.','Bandingkan kadar terhitung sebelum/tepat/lewat ekuivalen.','Jelaskan mengapa kondisi asam dan standarisasi titran penting.'],
'FeV25mL,oksalat50mL;rasio5dan2.5. C=ratio*.02*V/25. Medium memengaruhi produkMn;standarC.',
[['RasioFe:MnO₄⁻ ...','5:1','1:1','2:1','1:5'],['Oksalat25mL0,1M perlu titran ...','50mL','25mL','10mL','5mL'],['Lewat titik akhir membuat estimasi ...','tinggi','rendah selalu','tetap','negatif']]);
lab('gravimetri','Gravimetri Klorida','Bejana,Ag⁺ berlebih,filter,cawan,oven virtual,neraca.',
'Cl⁻ diendapkan sebagaiAgCl,disaring,dicuci,dikeringkan dan ditimbang. Faktor gravimetriCl/AgCl=35,45/143,32. Endapan hilang dan air tertinggal memberi bias berlawanan.',
'Sampel1g berkadarCl20%;recovery dan air tertinggal adalah parameter latihan. Tidak memodelkan fotodekomposisi atau kemurnian selain massa tambahan.',
['Endapkan dan saringAgCl','Cuci lalu pilih pemulihan/pengeringan','Timbang dan hitung kadar'],
[range('recovery','Endapan berhasil dipulihkan (%)',70,100,100),range('water','Air/pengotor tertinggal (g)',0,.2,0,.01)],[],
['HitungAgCl ideal dari0,2gCl.','Bandingkan90%recovery dengan100%+0,05gair.','Jelaskan mengapa hasil benar secara kebetulan belum membuktikan prosedur baik.'],
'ideal.808575g;kadar18%vs21.2367%;bias saling menutupi. Keringkan sampai massa konstan tetapperlukemurnian.',
[['FaktorCl/AgCl ...','35,45/143,32','143,32/35,45','1','2'],['Endapan hilang menyebabkan ...','kadar rendah','tinggi','pasti tepat','100%'],['Air tersisa menyebabkan ...','massa tinggi','massa rendah','molCl nyata naik','Ag hilang']]);
lab('spektro','Spektrofotometri','Kuvet1cm,blanko,standar0–8mg/L,spektrofotometer.',
'Absorbansi bergantung konsentrasi dalam rentang linear. KalibrasiA=0,1c+0,02 denganc mg/L digunakan untuk menghitung sampel; faktor pengenceran dikalikan setelah memperoleh kadar larutan ukur.',
'Data sintetis linear,tidak ada noise acak. Blanko0,02;kuvet kotor menambah0,05A. Kadar di luar0–8mg/L harus ditandai ekstrapolasi.',
['Pasang blanko dan pilih koreksi','Ukur standar lalu sampel pada kuvet','Hitung kadar dan faktor pengenceran'],
[range('concentration','Kadar sampel larutan ukur (mg/L)',0,12,4,.5),range('dilution','Faktor pengenceran',1,20,5)],
[['blank','Koreksi blanko',[['yes','Diterapkan'],['no','Diabaikan saat memakai slope']]],['cuvette','Kuvet',[['clean','Bersih'],['dirty','Kotor: bias+0,05A']]]],
['Bandingkan hasil sampel4mg/L,F5 dengan/tanpa blanko.','Hitung bias kuvet kotor terhadap kadar.','Apa tindakan jika sampel di atas standar8mg/L?'],
'Bersihblanko=>20mg/L;tanpablanko21mg/L;kuvetkotor+.5mg/Lterukuratau+2.5asalF5. Encerkan di atasrentang. Regresiintersep boleh mengoreksilatar.',
[['A=0,1c+0,02,c4 memberiA ...','0,42','0,4','4,2','0,02'],['Kuvet kotor dapat ...','menambahbias absorbansi','menghilangkan analit','mengubah massa atom','selalu memperbaiki'],['F5 diterapkan ...','kali5','bagi5','tambah5','diabaikan']]);
lab('kromatografi','Kromatografi Kertas','Kertas,garis asal,pelarut,tinta dua komponen,penggaris.',
'Rf=jarak pusat bercak/jarak front pelarut dari garis asal. Perbedaan afinitas terhadap fase diam/gerak menyebabkan pemisahan. Garis asal harus berada di atas permukaan pelarut.',
'Rf model dua pigmenA/B berbeda pada dua pelarut:0,3/0,7 atau0,6/0,8. Angka ilustratif,bukan identitas zat nyata;Rf tidak unik tanpa kondisi yang sama.',
['Buat garis asal di atas pelarut','Pilih fase gerak dan kembangkan kertas','Tandai front lalu ukur dua bercak'],
[range('front','Jarak front (cm)',2,10,8,.5)],
[['solvent','Pelarut model',[['one','Pelarut1'],['two','Pelarut2']]],['baseline','Posisi garis asal',[['above','Di atas pelarut'],['below','Terendam pelarut']]]],
['Hitung jarak bercak danRf untukfront8cm,pelarut1.','Bandingkan pemisahan pada dua pelarut.','Mengapa garis terendam atau kondisi berbeda membuat identifikasi tidak sah?'],
'Jarak2.4dan5.6cm,Rf.3/.7;pelarut2jarak4.8/6.4,Rf.6/.8. Pelarut1lebihpisah;asalterendamlarutkesumur.',
[['Rf diperoleh dari ...','jarakbercak/front','front/bercak','massabercak','waktu saja'],['Garis asal harus ...','di atas pelarut','terendam','di luar kertas','dihapus'],['Rf dapat berubah jika ...','pelarut berubah','judul berubah','nama siswa berubah','warna meja berubah']]);
lab('gugus','Identifikasi Gugus Fungsi','Rak tabung,sampel sederhana,DNPH,Tollens,bromin model,bikarbonat.',
'Gabungan uji memberi bukti gugus:alkena memudarkan bromin,karbonil memberiDNPH,aldehida sederhana memberiTollens,asam karboksilat memberiCO₂ denganbikarbonat.',
'Hanya contohetena,etanol,etanal,propanon,asam etanoat. Selektivitas tidak universal;kontrol dan konfirmasi lain diperlukan. Semua pereaksi berbahaya digunakan secara virtual.',
['Pilih sampel dan kontrol','Ambil aliquot baru untuk tiap uji','Tambahkan pereaksi virtual dan catat'],[],
[['sample','Sampel',[['alkene','Etena'],['alcohol','Etanol'],['aldehyde','Etanal'],['ketone','Propanon'],['acid','Asam etanoat']]],['reagent','Uji',[['bromine','Bromin'],['dnph','2,4-DNPH'],['tollens','Tollens'],['carbonate','Bikarbonat']]]],
['Susun pembeda etanal dan propanon dari dua uji.','Bandingkan etena dengan asam etanoat pada pereaksi yang sesuai.','Mengapa aliquot segar dan kontrol diperlukan?'],
'AldDNPH+/Tollens+;ketDNPH+/Tollens−;alkenebromine+;acidcarbonateCO2+. Cegahkontaminasipereaksi,bukti bukanidentitasunik.',
[['Etanal dan propanon sama-sama ...','DNPH positif','Tollens positif','bikarbonat positif','alkena'],['Asam+bikarbonat menghasilkan ...','CO₂','H₂','Cl₂','O₂'],['Aliquot segar mencegah ...','gangguan pereaksi sebelumnya','semua kesalahan','penguapan mutlak','reaksi apa pun']]);
lab('esterifikasi','Esterifikasi','Labu,refluks virtual,penangas,asam etanoat,etanol,pemisah konseptual.',
'Asam etanoat+etanol⇌etil etanoat+air. Katalis mempercepat pendekatan kesetimbangan. Refluks mempertahankan bahan volatil melalui kondensasi kembali; bukan pemisahan ester murni otomatis.',
'K=4 ilustratif,produkawal0;pendekatanx(t)=xeq(1−e^(−kt)) empiris,k0,02atau0,06s⁻¹. Bukan hukum laju mekanistik. Aroma hanya deskripsi,tidak meminta menghirup.',
['Siapkan mol asam dan alkohol','Pasang refluks serta pilih katalis','Panaskan waktu virtual dan hitung hasil'],
[range('acid','Asam awal (mol)',.5,2,1,.5),range('alcohol','Alkohol awal (mol)',.5,3,1,.5),range('time','Waktu model (s)',0,300,60,10)],
[['catalyst','Katalis',[['no','Tanpa'],['yes','Dengan']]]],
['Bandingkan hasil1:1 dan1:2 pada waktu panjang.','Bandingkan katalis pada60s dan batas kesetimbangan.','Mengapa refluks dan aroma tidak membuktikan kemurnian ester?'],
'xeq1:1=2/3;alkoholberlebihnaikhasil;katalisubahk bukanxeq. Reflukskembalikanvolatil,aromadeskriptif bukanbuktimurni.',
[['Katalis mengubah ...','kecepatan mencapai setimbang','K pada suhu tetap','stoikiometri','identitas atom'],['Produk esterifikasi ...','ester dan air','keton saja','amina','garam selalu'],['Refluks membantu ...','mengembalikan uap terkondensasi','membuat zat murni otomatis','menghilangkan semua air','menambah mol unsur']]);
lab('makanan','Uji Zat Makanan','Tabung,sampel model,kontrolair,Benedict,iodin,Biuret,ujilemak.',
'Benedict untuk gula pereduksi,iodin untukpati,Biuret untukikatan peptida,ujiemulsi untuklipid. Sukrosa utuh bukan gula pereduksi; hasil uji dipengaruhi kondisi.',
'Sampel disederhanakan menjadi larutan glukosa,pati,protein,minyak,campuran dan air. Benedict memerlukan pemanasan model. Hasil bukan analisis nutrisi kuantitatif.',
['Pilih kontrol dan sampel','Pilih pereaksi pada aliquot segar','Terapkan kondisi uji dan amati'],[],
[['sample','Sampel',[['water','Air kontrol'],['glucose','Glukosa'],['starch','Pati'],['protein','Protein'],['oil','Minyak'],['mix','Campuran glukosa/protein/lipid']]],['test','Uji',[['benedict','Benedict'],['iodine','Iodin'],['biuret','Biuret'],['lipid','Emulsi lipid']]],['heat','Pemanasan Benedict',[['yes','Dilakukan'],['no','Tidak']]]],
['Bandingkan air dan glukosa padaBenedict dengan/tanpa pemanasan.','Identifikasi campuran dari gabungan empat uji.','Jelaskan mengapa positifBenedict bukan berarti pasti glukosa murni.'],
'Glukosaben+setelahpanas;campuranben+/biuret+/lipid+,iod−. Tanpapemanasanhasilbelumvalid;gula lainbisa positif.',
[['Biuret mendeteksi ...','ikatanpeptida','pati','lemak saja','garam'],['Iodin khas untuk ...','pati','glukosa','protein','minyak'],['Kontrol negatif berguna untuk ...','membandingkan latar pereaksi','menggantikan sampel','menaikkan kadar','membuatsemuapositif']]);
lab('koloid','Pembuatan dan Sifat Koloid','Bejana sol/emulsi,senter,garam model,pengaduk,emulgator.',
'Koloid dapat menghamburkan cahaya melalui efekTyndall. Koagulasi menggabungkan partikel sehingga kestabilan menurun. Emulgator membantu menstabilkan antarmuka;adsorpsi terjadi pada permukaan.',
'Ambang elektrolit koagulasi10mM adalah skenario ilustratif,bukan nilai semua koloid. Emulsi memakai skor kestabilan sederhana terhadap waktu,tidak memodelkan ukuran partikel detail.',
['Pilih larutan,sol atau emulsi','Tambahkan elektrolit atau emulgator','Sorot cahaya dan amati setelah menunggu'],
[range('salt','Elektrolit tambahan (mM)',0,20,0,1),range('time','Waktu tunggu (menit)',0,30,10,5)],
[['kind','Dispersi',[['solution','Larutan gula'],['sol','Sol model'],['emulsion','Minyak-air']]],['emulsifier','Emulgator',[['no','Tidak'],['yes','Ada']]]],
['BandingkanTyndall larutan dengansol.','Uji elektrolit di bawah/atas ambang pada sol.','Bandingkan emulsi dengan/tanpaemulgator dan jelaskan batas model.'],
'LarutangulatanpaTyndall,solya;garam>=10koagulasi model;emulgatorlambatpemisahan. Ambangbukanuniversal.',
[['Tyndall adalah ...','hamburan cahaya','reaksiinti','penguapan','aruslistrik'],['Koagulasi berarti ...','penggabunganpartikel','ionisasipenuh','distilasi','semuamenjadigas'],['Emulgator membantu ...','kestabilanantarmuka','membuatminyakjadiunsur','menghilangkanmassa','menetapkanpH7']]);
lab('nyala','Uji Nyala Logam','Pembakar virtual,kawat bersih,sampelNa/K/Ca/Ba/Cu,kontrol.',
'Pemanasan dapat mengeksitasi spesies yang kemudian memancarkan cahaya khas. Warna nyala adalah bukti pendukung,bukan penentuan kadar. KontaminasiNa dapat menutupi warna lain.',
'Warna layar perkiraan,bergantung perangkat dan bukan spektrum terkalibrasi. SenyawaBa/Cu tidak disentuh langsung;semua uji virtual.',
['Bersihkan kawat dan jalankan kontrol','Pilih sampel serta status kontaminasi','Masukkan ke nyala dan bandingkan warna'],[],
[['metal','Sampel',[['Na','Na'],['K','K'],['Ca','Ca'],['Ba','Ba'],['Cu','Cu']]],['clean','Kawat',[['yes','Bersih'],['no','TerkontaminasiNa']]]],
['Catat perbedaanNa,K,Ca,Ba,Cu pada kawat bersih.','UjiK saat ada kontaminasiNa dan jelaskan masalahidentifikasi.','Mengapa warna layar tidak cukup untuk analisis kadar?'],
'Nakuning,Kungu/lilac,Camerahjingga,Bahijauapel,Cuhijaubiru. Nacontamdominankuning;visualkualitatif bukan kadar.',
[['Na cenderung memberi ...','kuning','ungu','biru saja','hitam'],['K cenderung memberi ...','lilac','kuningNa','merahCa','tanpa cahaya'],['Kawat kotor dapat ...','menggangguidentifikasi','menjaminakurasi','mengubahunsur','menghilangkansemuabias']]);
lab('halogen','Penggantian Halogen','TabungCl₂/Br₂/I₂ danhalida,pipet,pengamatanwarna virtual.',
'Urutan oksidatorCl₂>Br₂>I₂ digunakan untuk memprediksi penggantian halida. Halogen kuat mengoksidasi ion halida dari halogen lebih lemah.',
'Pereaksi model terpisah dan hasil kualitatif. Pilihan lapisan organik hanya ilustrasi warnaBr₂jingga/I₂ungu;partisi dan pelarutspesifik tidak dihitung. Tanpa instruksi mencampur bahan nyata.',
['Pilih halogen danhalida','Campur aliquotvirtual','Amati hasil dan lapisan ilustratif'],[],
[['oxidant','Halogen',[['0','Cl₂'],['1','Br₂'],['2','I₂']]],['halide','Halida',[['0','Cl⁻'],['1','Br⁻'],['2','I⁻']]]],
['TuliskanCl₂+Br⁻ dan identifikasioksidator.','BandingkanBr₂+I⁻ denganI₂+Br⁻.','Mengapa warna sebelum reaksi perlu dicatat?'],
'Cl2+2Br−→2Cl−+Br2;Br2+2I−→2Br−+I2;balik tidak spontanmodel. Catatwarnaawalhalogenuntukbedakanproduk.',
[['Cl₂ mengoksidasi ...','Br⁻','Cl⁻ menjadiCl⁻','Na⁺','Ar'],['I₂ denganBr⁻ ...','tidakmenggantikan dalammodel','pastiCl₂','menghasilkanAgCl','menjadiNa'],['ReduktorCl₂+Br⁻ adalah ...','Br⁻','Cl₂','Cl⁻produk','airselalu']]);
lab('air','Analisis Kualitas Air','pHmeter,titrasiEDTA model,ujiCl⁻,turbidimeter,kolorimeternitrat.',
'Beberapa parameter salingmelengkapi:pH,kesadahan,klorida,kekeruhan,nitrat. Kesadahan sebagaiCaCO₃ dapat dihitung dari titrasiEDTA1:1 terhadapiondivalenmodel.',
'Profil air sintetis,bukan standar kelayakan kesehatan. Lima parameter ini tidak menilai mikroba atau seluruh kontaminan sehingga tidak menetapkan aman diminum.',
['Pilih sampel dan aliquot50mL','Pilih parameter dan kalibrasi model','Ukur beberapa parameter sebelum menyimpulkan'],[],
[['sample','Profil',[['one','SampelA'],['two','SampelB'],['three','SampelC']]],['test','Parameter',[['ph','pH'],['hardness','KesadahanCaCO₃'],['chloride','Klorida'],['turbidity','Kekeruhan'],['nitrate','Nitrat sebagaiNO₃⁻']]]],
['BandingkanA,B,C menurut pH dan kesadahan.','HitungV EDTA0,010M untuk50mL sampel berkadar200mg/LsebagaiCaCO₃(M100).','Mengapa air jernih belum dapat dinyatakan layakminum?'],
'200mg/L*0.05L=10mg=.0001mol;VEDTA10mL. ProfilA7/80,B6/200,C8/300;tidakada ujimikroba sehingga takbolehklaimaman.',
[['Kesadahan dilaporkan sebagai ...','CaCO₃ekuivalen','logamCu','massaairtotal','pH'],['EDTA1:1 untuk0,1mmol perlu0,01M ...','10mL','1mL','100mL','0,1mL'],['Airjernih pasti aman?','tidak dapatdisimpulkan','ya selalu','hanya dariwarnanya','tanpauji']]);
lab('misteri','Analisis Sampel Misterius','Empat sampelberkode,kartu uji,pipet,anggaran8kredit.',
'Identifikasi dilakukan dari gabunganbukti. Kandidat dibatasiNaCl,Na₂CO₃,glukosa,pati. Ujibikarbonat/asammodel,iodin,Benedict dan kloridamemberi polabukti berbeda.',
'Kode sampel tetap agar tugas dapat dinilai. Hasil dananggarantersimpan;tidak menampilkan nama kandidat sampel aktif sebagai jawaban. Setiapuji memakai2kredit;tidak ada pengisianulanganggaran otomatis.',
['Pilih sampelberkode danrumuskan hipotesis','Pilih ujipalinginformatif','Jalankan maksimalempat ujidan simpulkan'],[],
[['sample','Kode',[['A','A'],['B','B'],['C','C'],['D','D']]],['test','Uji2kredit',[['acid','Asam:gasCO₂'],['iodine','Iodin'],['benedict','Benedict denganpemanasan'],['chloride','Klorida:AgCl']]]],
['Tuliskan kode,hipotesis dan hasilsekurangnyadua uji.','Tentukan kandidat dari gabunganbukti serta eliminasi kandidat lain.','Jelaskan strategi pemilihan uji dalam anggaran8kredit.'],
'KodeAglukosa,BNaCl,Cpati,DNa2CO3. Ben+A,chloride+B,iodine+C,acid+D. Penilaianpenalarandanbukti bukan hanya nama. Ujiklorida diasumsikan kondisi selektif tervalidasi untukkandidat,reaksisamping takdimodelkan.',
[['Kesimpulanidentifikasi membutuhkan ...','gabunganbukti','tebaknama','warnaawalsaja','satuangkaacak'],['Empatuji×2kredit ...','8kredit','4kredit','2kredit','16kredit'],['Ujiberikut dipilih untuk ...','membedakankandidatyangtersisa','menghabiskananggaransaja','meniru teman','mengabaikanhasilawal']]);
module.exports=topics;
