'use strict';
const $=id=>document.getElementById(id),val=id=>Number($(id).value),fmt=(n,d=4)=>Number(n).toLocaleString('id-ID',{maximumFractionDigits:d});
function choose(id,label,options){const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');s.id=id;options.forEach(([v,t])=>s.add(new Option(t,v)));l.append(s);$('controls').append(l);s.addEventListener('change',update)}
function cards(items){return items.map(x=>'<p style="padding:12px;border:1px solid #52525b;border-radius:8px">'+x+'</p>').join('')}
function bar(label,n,max=100){return '<p>'+label+': '+fmt(n)+'</p><div class="track"><i style="width:'+Math.max(0,Math.min(100,100*n/max))+'%"></i></div>'}
function oilPosition(tb,top,bottom){return(bottom-tb)/(bottom-top)}
function combustion(n,m){const mol=m/(14*n+2);return{mol,o2:mol*(3*n+1)/2,co2:mol*n,water:mol*(n+1),co2mass:mol*n*44}}
const oxides={Na2O:['Na₂O','basa','Na₂O + H₂O → 2NaOH','Na₂O + 2H⁺ → 2Na⁺ + H₂O','Tidak ada reaksi asam–basa sederhana dengan OH⁻'],MgO:['MgO','basa','Hidrasi menjadi Mg(OH)₂ terbatas/lambat; bukan larutan basa kuat bebas batas','MgO + 2H⁺ → Mg²⁺ + H₂O','Tidak ada reaksi asam–basa sederhana dengan OH⁻'],Al2O3:['Al₂O₃','amfoter','Tidak langsung bereaksi dengan air dalam model','Al₂O₃ + 6H⁺ → 2Al³⁺ + 3H₂O','Al₂O₃ + 2OH⁻ + 3H₂O → 2[Al(OH)₄]⁻'],SiO2:['SiO₂','asam','Tidak langsung bereaksi dengan air','Tidak dengan asam nonfluorida pada model ini','SiO₂ + 2OH⁻ → SiO₃²⁻ + H₂O (model kondisi sesuai)'],SO3:['SO₃','asam','SO₃ + H₂O → H₂SO₄','Tidak ada netralisasi dengan H⁺ pada model','SO₃ + 2OH⁻ → SO₄²⁻ + H₂O']};
const ions=[['Ti³⁺',1],['Cr³⁺',3],['Mn²⁺',5],['Fe²⁺',6],['Fe³⁺',5],['Co²⁺',7],['Ni²⁺',8],['Cu²⁺',9],['Zn²⁺',10]];
function hund(d){return d<=5?d:10-d}
const complexes=[
 {name:'[Co(NH₃)₆]³⁺',q:3,lq:0,count:6,donors:6,shape:'oktahedral',center:'Co',labels:['N','N','N','N','N','N']},
 {name:'[Fe(CN)₆]⁴⁻',q:-4,lq:-6,count:6,donors:6,shape:'oktahedral',center:'Fe',labels:['C','C','C','C','C','C']},
 {name:'[Co(en)₃]³⁺',q:3,lq:0,count:3,donors:6,shape:'oktahedral',center:'Co',labels:['N₁','N₂','N₁','N₃','N₂','N₃']},
 {name:'[NiCl₄]²⁻',q:-2,lq:-4,count:4,donors:4,shape:'tetrahedral',center:'Ni',labels:['Cl','Cl','Cl','Cl']},
 {name:'cis-[Pt(NH₃)₂Cl₂]',q:0,lq:-2,count:4,donors:4,shape:'planar persegi',center:'Pt',labels:['Cl','Cl','N','N']},
 {name:'trans-[Pt(NH₃)₂Cl₂]',q:0,lq:-2,count:4,donors:4,shape:'planar persegi',center:'Pt',labels:['Cl','N','Cl','N']}
];
function complexSVG(c){const coords=c.donors===6?[[0,-85],[0,85],[-95,0],[95,0],[-60,-42],[60,42]]:c.shape==='tetrahedral'?[[0,-85],[-85,55],[85,55],[0,32]]:[[0,-85],[85,0],[0,85],[-85,0]];return '<svg viewBox="0 0 420 260" role="img" aria-label="Skema '+c.shape+'">'+coords.map(([x,y],i)=>'<line x1="210" y1="130" x2="'+(210+x)+'" y2="'+(130+y)+'" stroke="#a78bfa" stroke-width="3" '+(c.shape==='tetrahedral'&&i===3?'stroke-dasharray="5 5"':'')+'/><circle cx="'+(210+x)+'" cy="'+(130+y)+'" r="21" fill="#27272a"/><text x="'+(210+x)+'" y="'+(135+y)+'" text-anchor="middle" fill="white">'+c.labels[i]+'</text>').join('')+'<circle cx="210" cy="130" r="23" fill="#a78bfa"/><text x="210" y="135" text-anchor="middle" fill="#09090b">'+c.center+'</text></svg><p>Skema proyeksi, bukan panjang/sudut eksak. N/C menunjukkan atom donor ligan; subskrip sama pada en menandai satu ligan bidentat.</p>'}
const alcohols=[['Etanol','primer','CH₃CH₂OH','Etanal CH₃CHO','Asam etanoat CH₃COOH'],['Propan-2-ol','sekunder','CH₃CH(OH)CH₃','Propanon CH₃COCH₃','Propanon; tidak mengikuti oksidasi lanjut sederhana tanpa pemutusan C–C'],['2-metilpropan-2-ol','tersier','(CH₃)₃COH','Tidak teroksidasi melalui jalur sederhana ini','Tidak teroksidasi melalui jalur sederhana ini; kondisi keras dapat memutus C–C'],['Metoksimetana','eter','CH₃OCH₃','Bukan alkohol; jalur model tidak berlaku','Bukan alkohol; jalur model tidak berlaku']];
const carbonyls=[['Propanal','CH₃CH₂CHO',true,true,'Propan-1-ol'],['Propanon','CH₃COCH₃',true,false,'Propan-2-ol'],['Etanol','CH₃CH₂OH',false,false,'Tidak dimodelkan sebagai reduksi karbonil']];
function titrate(aliquot,c,v){const fe=.1*aliquot/1000,mn=c*v/1000,reacted=Math.min(fe,5*mn);return{feLeft:fe-reacted,mnExcess:Math.max(0,mn-fe/5),fe3:reacted,equivalent:fe/(5*c)*1000,estimate:5*mn/(aliquot/1000)}}
function gravimetric(recovery,contamination){const ideal=.2*143.32/35.45,measured=ideal*recovery/100+contamination;return{ideal,measured,chloride:measured*35.45/143.32,percent:100*measured*35.45/143.32}}
function regress(points){const n=points.length,xm=points.reduce((s,p)=>s+p[0],0)/n,ym=points.reduce((s,p)=>s+p[1],0)/n,xx=points.reduce((s,p)=>s+(p[0]-xm)**2,0),xy=points.reduce((s,p)=>s+(p[0]-xm)*(p[1]-ym),0),m=xy/xx,b=ym-m*xm,ss=points.reduce((s,p)=>s+(p[1]-ym)**2,0),err=points.reduce((s,p)=>s+(p[1]-m*p[0]-b)**2,0);return{m,b,r2:1-err/ss}}
function standards(noise){const variation=[0,1,-1,.5,-.5];return[0,2,4,6,8].map((x,i)=>[x,.1*x+.02+noise*variation[i]])}
function decay(n,half,t){const remain=n*2**(-t/half);return{remain,fraction:remain/n,activity:Math.LN2/half*remain}}
const nuclear=[
 ['Alfa: U238 → Th234 + He4',[[238,92]],[[234,90],[4,2]],'A berkurang 4; Z berkurang 2.'],
 ['Beta minus: C14 → N14 + e⁻ + antineutrino',[[14,6]],[[14,7],[0,-1],[0,0]],'Neutron menjadi proton; neutrino tidak mengubah A/Z.'],
 ['Beta plus: O15 → N15 + e⁺ + neutrino',[[15,8]],[[15,7],[0,1],[0,0]],'Proton menjadi neutron.'],
 ['Gamma: Tc99m → Tc99 + γ',[[99,43]],[[99,43],[0,0]],'Keadaan energi berubah; A/Z tetap.'],
 ['Fisi contoh: U235 + n → Ba141 + Kr92 + 3n',[[235,92],[1,0]],[[141,56],[92,36],[3,0]],'Satu saluran ilustratif; A neutron produk total3.'],
 ['Fusi: H2 + H3 → He4 + n',[[2,1],[3,1]],[[4,2],[1,0]],'Inti ringan bergabung; neutron membawa sebagian energi.']
];
function setup(){const s=TOPIC.sim;
if(s==='oil')choose('boiling','Komponen wakil',[['69','Heksana ~69°C'],['126','Oktana ~126°C'],['216','Dodekana ~216°C'],['287','Heksadekana ~287°C']]);
if(s==='families'){choose('oxidant','Halogen',[['0','Cl₂'],['1','Br₂'],['2','I₂']]);choose('halide','Ion halida',[['0','Cl⁻'],['1','Br⁻'],['2','I⁻']])}
if(s==='period3'){choose('oxide','Oksida',Object.entries(oxides).map(([k,v])=>[k,v[0]]));choose('reagent','Pereaksi',[['2','Air'],['3','Asam nonfluorida (H⁺)'],['4','Basa kuat (OH⁻)']])}
if(s==='transition')choose('ion','Kation',ions.map((x,i)=>[i,x[0]]));
if(s==='complex')choose('complex','Kompleks',complexes.map((x,i)=>[i,x.name]));
if(s==='alcohol'){choose('compound','Senyawa',alcohols.map((x,i)=>[i,x[0]]));choose('condition','Kondisi model',[['3','Oksidasi terbatas'],['4','Oksidasi lanjut']])}
if(s==='carbonyl'){choose('compound','Sampel',carbonyls.map((x,i)=>[i,x[0]]));choose('test','Uji virtual',[['dnph','2,4-DNPH'],['tollens','Tollens'],['reduction','Reduksi karbonil']])}
if(s==='ester')choose('medium','Hidrolisis',[['acid','Berkatalis asam'],['base','Basa NaOH cukup']]);
if(s==='nuclear')choose('reaction','Contoh',nuclear.map((x,i)=>[i,x[0]]));
update();}
let lastResult='';
function update(){const s=TOPIC.sim;let text='',visual='';
if(s==='oil'){const tb=val('boiling'),top=val('top'),bottom=val('bottom'),h=oilPosition(tb,top,bottom);text='Titik didih wakil='+tb+'°C. '+(h>1?'Tetap uap hingga puncak: profil belum cukup dingin.':h<0?'Suhu dasar di bawah titik didih: komponen belum tervaporisasi dalam model.':'Perkiraan kondensasi pada '+fmt(100*h)+'% tinggi dari dasar.')+' Model komponen tunggal, tekanan tetap, profil suhu linear.';visual='<svg viewBox="0 0 420 270" role="img" aria-label="Profil kolom distilasi"><rect x="110" y="25" width="100" height="220" fill="#27272a" stroke="#a78bfa"/>'+[0,.25,.5,.75,1].map(t=>'<path d="M110 '+(245-220*t)+'H210" stroke="#52525b"/><text x="230" y="'+(249-220*t)+'" fill="white">'+fmt(bottom-(bottom-top)*t)+'°C</text>').join('')+(h>=0&&h<=1?'<circle cx="160" cy="'+(245-220*h)+'" r="9" fill="#34d399"/>':'')+'</svg>'}
if(s==='fuel'){const n=val('carbon'),m=val('mass'),r=combustion(n,m),ratio=val('oxygen');text='C'+n+'H'+(2*n+2)+': '+fmt(r.mol)+' mol bahan bakar; O₂ kebutuhan lengkap='+fmt(r.o2)+' mol; tersedia='+fmt(r.o2*ratio/100)+' mol. '+(ratio<100?'O₂ kurang: CO₂ aktual tidak dihitung; acuan lengkap hipotetis '+fmt(r.co2mass)+' g.':'Jika pembakaran lengkap, CO₂='+fmt(r.co2)+' mol ('+fmt(r.co2mass)+' g), H₂O='+fmt(r.water)+' mol.')+' Nilai ini bukan perbandingan energi atau angka oktan.';visual=bar('O₂ tersedia (% kebutuhan)',ratio,150)+cards(['1 mol C'+n+'H'+(2*n+2)+' + '+fmt((3*n+1)/2)+' mol O₂ → '+n+' mol CO₂ + '+(n+1)+' mol H₂O'])}
if(s==='families'){const a=val('oxidant'),b=val('halide'),names=['Cl','Br','I'];text=a<b?names[a]+'₂ + 2'+names[b]+'⁻ → 2'+names[a]+'⁻ + '+names[b]+'₂. Oksidator '+names[a]+'₂; reduktor '+names[b]+'⁻.':a===b?'Pasangan unsur sama: tidak ada perubahan bersih dalam model.':'Tidak ada penggantian spontan yang diprediksi pada model urutan Cl₂ > Br₂ > I₂.';visual=cards(['Kekuatan oksidator: Cl₂ > Br₂ > I₂','Alkali: lazim +1 | alkali tanah: lazim +2','Gas mulia: reaktivitas rendah, bukan mutlak nol'])}
if(s==='period3'){const o=oxides[$('oxide').value];text=o[0]+' — oksida '+o[1]+'. '+o[val('reagent')]+'. Kondisi ideal ringkas; laju dan kelarutan tidak dihitung.';visual=cards([o[0],o[1],o[val('reagent')]])}
if(s==='transition'){const [name,d]=ions[val('ion')],u=hund(d);text=name+': [Ar]3d'+d+'; elektron tak berpasangan model ion bebas='+u+'; μ spin-only='+fmt(Math.sqrt(u*(u+2)))+' BM. '+(u?'Paramagnetik dalam model.':'Diamagnetik dalam model.')+' Kompleks ligan dapat mempunyai susunan spin berbeda.';visual='<div style="display:flex;gap:8px;flex-wrap:wrap">'+Array.from({length:5},(_,i)=>'<div style="padding:12px;border:1px solid #a78bfa">'+(d>i?'↑':'·')+(d>i+5?'↓':'')+'</div>').join('')+'</div><p>Lima orbital d setara; isi tunggal dahulu menurut Hund.</p>'}
if(s==='complex'){const c=complexes[val('complex')],z=c.q-c.lq;text=c.name+': biloks pusat='+z+' karena x+('+c.lq+')='+c.q+'. Jumlah ligan='+c.count+'; atom donor/koordinasi='+c.donors+'; geometri contoh '+c.shape+'.';visual=complexSVG(c)}
if(s==='alcohol'){const a=alcohols[val('compound')];text=a[0]+' ('+a[1]+'), '+a[2]+' → '+a[val('condition')]+'. Hasil umum kualitatif, bukan prediksi semua pereaksi.';visual=cards([a[2],a[val('condition')]])}
if(s==='carbonyl'){const c=carbonyls[val('compound')],test=$('test').value,answer=test==='reduction'?c[4]:test==='dnph'?(c[2]?'Positif: endapan derivat karbonil':'Negatif dalam model'):(c[3]?'Positif: cermin/endapan perak':'Negatif dalam model');text=c[0]+' '+c[1]+': '+answer+'. Hanya berlaku pada sampel sederhana yang tersedia, bukan identifikasi unik semua zat.';visual=cards([c[1],answer])}
if(s==='ester'){const n=val('initial'),x=n*val('conversion')/100,base=$('medium').value==='base';text='Ester bereaksi='+fmt(x)+' mol; sisa='+fmt(n-x)+' mol; etanol='+fmt(x)+' mol; '+(base?'natrium etanoat='+fmt(x)+' mol dan NaOH dikonsumsi='+fmt(x)+' mol.':'asam etanoat='+fmt(x)+' mol dan air dikonsumsi='+fmt(x)+' mol.')+' Konversi ditentukan pengguna, bukan hasil perhitungan kesetimbangan.';visual=bar('Ester sisa (mol)',n-x,2)+bar('Etanol (mol)',x,2)+bar(base?'Etanoat (mol)':'Asam etanoat (mol)',x,2)}
if(s==='halo'){const n=val('initial'),f=val('elimination')/100,e=n*f,al=n-e;text='Konversi penuh '+fmt(n)+' mol bromoetana: etanol='+fmt(al)+' mol; etena='+fmt(e)+' mol; Br⁻='+fmt(n)+' mol; air dari eliminasi='+fmt(e)+' mol. Karbon produk='+fmt(2*(al+e))+' mol atom, sama dengan awal. Fraksi adalah asumsi hasil, bukan prediksi kondisi.';visual=bar('Etanol (mol)',al,2)+bar('Etena (mol)',e,2)+cards(['Substitusi: C₂H₅Br + OH⁻ → C₂H₅OH + Br⁻','Eliminasi: C₂H₅Br + OH⁻ → C₂H₄ + H₂O + Br⁻'])}
if(s==='redox'){const r=titrate(val('aliquot'),val('titrant'),val('volume'));text='V ekuivalen='+fmt(r.equivalent)+' mL; Fe²⁺ tersisa='+fmt(r.feLeft*1000)+' mmol; Fe³⁺ terbentuk='+fmt(r.fe3*1000)+' mmol; MnO₄⁻ berlebih='+fmt(r.mnExcess*1000)+' mmol. '+(Math.abs(val('volume')-r.equivalent)<1e-8?'Tepat ekuivalen stoikiometri.':val('volume')<r.equivalent?'Belum ekuivalen.':'Lewat ekuivalen: kelebihan permanganat.')+' Jika volume ini dianggap titik akhir, kadar Fe terhitung='+fmt(r.estimate)+' M.';visual=bar('Fe²⁺ tersisa (mmol)',r.feLeft*1000,5)+bar('Fe³⁺ (mmol)',r.fe3*1000,5)+bar('MnO₄⁻ berlebih (mmol)',r.mnExcess*1000,5)}
if(s==='gravimetry'){const r=gravimetric(val('recovery'),val('contamination'));text='Sampel1g mengandungCl0,2g. AgCl ideal='+fmt(r.ideal,6)+' g; endapan tertimbang='+fmt(r.measured,6)+' g; Cl terhitung='+fmt(r.chloride,6)+' g; kadar='+fmt(r.percent)+'%; bias='+fmt(r.percent-20)+' poin persentase.';visual=bar('Kadar benar (%)',20,30)+bar('Kadar terhitung (%)',r.percent,30)}
if(s==='calibration'){const points=standards(val('noise')),r=regress(points),a=val('absorbance'),c=(a-r.b)/r.m,original=c*val('dilution');text='Regresi A='+fmt(r.m,6)+'c + '+fmt(r.b,6)+'; R²='+fmt(r.r2,6)+'. c larutan ukur='+fmt(c)+' mg/L; hasil hitung asal='+fmt(original)+' mg/L. '+(c<0?'Hasil negatif tidak layak sebagai kadar; periksa blanko dan batas kuantifikasi.':c>8?'Di luar rentang0–8mg/L: ekstrapolasi, encerkan/validasi ulang.':'Dalam rentang konsentrasi standar; periksa pula mutu metode.')+' Variasi standar adalah skenario latihan.';const px=x=>40+40*x,py=y=>195-140*y;visual='<svg viewBox="0 0 420 250" role="img" aria-label="Kurva kalibrasi"><path d="M40 15V195H390" fill="none" stroke="white"/><line x1="40" y1="'+py(r.b)+'" x2="360" y2="'+py(r.m*8+r.b)+'" stroke="#a78bfa"/>'+points.map(([x,y])=>'<circle cx="'+px(x)+'" cy="'+py(y)+'" r="5" fill="#34d399"/>').join('')+'<g fill="white" font-size="12"><text x="40" y="228">c:0–8mg/L; titik=standar, garis=regresi</text><text x="40" y="13">Absorbansi (skala vertikal0–1,2)</text></g></svg>'+cards(points.map(([x,y])=>'c='+x+'mg/L; A='+fmt(y)))}
if(s==='decay'){const half=val('half'),n=val('population')*1e6,t=val('time'),r=decay(n,half,t);text='t/t½='+fmt(t/half)+'; sisa='+fmt(100*r.fraction)+'%; N harapan='+fmt(r.remain,3)+' inti; A='+fmt(r.activity,3)+' Bq. Nilai kontinu adalah harapan statistik, bukan jumlah pecahan inti yang diamati.';visual='<svg viewBox="0 0 420 250" role="img" aria-label="Peluruhan terhadap waktu"><path d="M40 20V190H390" fill="none" stroke="white"/><polyline fill="none" stroke="#a78bfa" stroke-width="3" points="'+Array.from({length:101},(_,i)=>(40+3.4*i)+','+(190-160*2**(-i/half))).join(' ')+'"/><circle cx="'+(40+3.4*t)+'" cy="'+(190-160*r.fraction)+'" r="5" fill="#34d399"/><g fill="white" font-size="12"><text x="40" y="220">Waktu0–100s; vertikal: sisa0–100%</text></g></svg>'}
if(s==='nuclear'){const r=nuclear[val('reaction')],sum=arr=>arr.reduce((a,p)=>[a[0]+p[0],a[1]+p[1]],[0,0]),left=sum(r[1]),right=sum(r[2]),q=val('defect')*931.5;text=r[0]+'. Neraca A: '+left[0]+'='+right[0]+'; Z: '+left[1]+'='+right[1]+'. '+r[3]+' Perhitungan TERPISAH dengan Δm input: Q='+fmt(q)+' MeV ('+(q>0?'dilepas':q<0?'perlu energi':'nol')+'). Δm bukan data reaksi terpilih.';visual=cards([r[0],'Total A pereaksi/produk: '+left[0]+'/'+right[0],'Total Z pereaksi/produk: '+left[1]+'/'+right[1],'Q model massa–energi: '+fmt(q)+' MeV'])}
lastResult=text;$('result').textContent=text;$('visual').innerHTML=visual;document.querySelectorAll('[data-value]').forEach(e=>e.textContent=$(e.dataset.value).value);
}
function save(){if(window.PortalSubmission?.isFinal())return;try{const d={};document.querySelectorAll('[data-answer]').forEach(e=>d[e.id]=e.value);localStorage.setItem(STORAGE_KEY,JSON.stringify(d));$('draft-status').textContent='Draf tersimpan pada perangkat.'}catch(_){$('draft-status').textContent='Draf belum tersimpan. Penyimpanan browser tidak tersedia.'}}
function start(){setup();try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');Object.entries(d).forEach(([id,v])=>{if($(id)&&$(id).hasAttribute('data-answer'))$(id).value=v})}catch(_){}$('student-date').value=new Date().toLocaleDateString('id-ID');document.querySelectorAll('[data-answer]').forEach(e=>e.addEventListener('input',save));document.querySelectorAll('#controls input').forEach(e=>e.addEventListener('input',update));$('record').onclick=()=>{if(window.PortalSubmission?.isFinal()||$('lks-observasi').disabled)return;const inputs=[...$('controls').querySelectorAll('input,select')].map(e=>e.id+'='+e.value).join('; ');$('lks-observasi').value+=($('lks-observasi').value?'\n\n':'')+inputs+'\n'+lastResult;save()};}
document.addEventListener('DOMContentLoaded',start);



