const topics=[];
function add(id,file,title,sim,lessons,controls,task,lks,rubric,qs){const quiz=qs.map(([question,correct,...wrong],i)=>{const options=[correct,...wrong];const k=i%4;for(let j=0;j<k;j++)options.unshift(options.pop());return{question,options,answer:k}});topics.push({id,file,title,sim,lessons,controls,task,lks,rubric,quiz,intro:task,goals:['Menjelaskan konsep dan hubungan sebab-akibat pada '+title,'Menggunakan simulasi untuk menguji prediksi','Menafsirkan data, satuan dan batas model secara kritis']})}
add('lan-minyak','Minyak_Bumi_dan_Distilasi','Minyak Bumi dan Distilasi Fraksional','oil',[
['Minyak bumi sebagai campuran','Minyak mentah mengandung banyak hidrokarbon dengan sifat berbeda. Fraksi bukan zat murni, melainkan kelompok komponen dalam rentang titik didih. Komposisi minyak dari sumber berbeda tidak selalu sama.'],['Kolom fraksinasi','Bagian bawah kolom lebih panas dan bagian atas lebih dingin. Komponen bertitik didih tinggi cenderung terkondensasi pada bagian bawah. Distilasi memisahkan secara fisik; proses ini tidak memutus ikatan C–C seperti cracking.'],['Pengolahan lanjutan','Cracking memecah hidrokarbon besar menjadi molekul lebih kecil. Reforming mengubah struktur untuk meningkatkan mutu komponen bahan bakar. Hasil distilasi masih memerlukan pengolahan; fraksi bensin bukan berarti langsung memenuhi semua spesifikasi kendaraan.'],['Model titik embun','Simulasi memilih komponen wakil dengan titik didih perkiraan: heksana 69°C, oktana 126°C, dodekana 216°C, heksadekana 287°C. Tekanan tetap dan profil suhu linear. Posisi kondensasi diperoleh dari suhu setempat sama dengan titik didih; bukan prediksi kolom industri multikomponen.']],
[['top','Suhu puncak (°C)',20,100,30,5],['bottom','Suhu dasar (°C)',200,400,350,10]],'Ubah profil suhu kolom dan komponen wakil. Prediksi tempat kondensasi serta kondisi ketika komponen tidak mengembun di dalam kolom.',
['Pada puncak30°C dan dasar350°C, bandingkan posisi heksana dengan heksadekana.','Apa yang terjadi dalam model jika suhu puncak lebih tinggi daripada titik didih komponen?','Bedakan distilasi, cracking dan reforming; mengapa fraksi bukan senyawa tunggal?'],
'h=(Tdasar-Tdidih)/(Tdasar-Tpuncak),diukur dari dasar. Heksana87.8125%,heksadekana19.6875%. Tb<Tpuncak tetap uap;Tb>Tdasar tidak tervaporisasi dalam model. Distilasi fisik,cracking pecah rantai,reforming ubah struktur.',
[['Fraksi minyak bumi adalah ...','campuran dalam rentang didih','satu unsur','selalu oktana murni','isotop'],['Bagian kolom lebih dingin adalah ...','puncak','dasar','semua sama','pompa'],['Cracking terutama ...','memutus rantai besar','memisahkan tanpa perubahan kimia','menambah neutron','mengendapkan garam'],['Komponen didih tinggi cenderung mengembun ...','lebih dekat dasar','selalu di puncak','di luar atmosfer','tidak pernah'],['Profil simulasi mengasumsikan ...','tekanan tetap','semua campuran identik','kolom tanpa gradien','seluruh komponen murni di kilang']] );
add('lan-bakar','Bahan_Bakar_Oktan_dan_Emisi','Bahan Bakar, Angka Oktan, dan Emisi','fuel',[
['Pembakaran lengkap','Untuk alkana CnH₂n₊₂, satu mol memerlukan (3n+1)/2 mol O₂ dan menghasilkan n mol CO₂ serta n+1 mol H₂O. Koefisien pecahan menyatakan rasio mol; dapat dikalikan dua untuk koefisien bulat.'],['Udara dan pembakaran tak lengkap','Kekurangan oksigen dapat menyebabkan CO, karbon padat dan bahan bakar tersisa. Produk nyata bergantung pencampuran dan kinetika, sehingga model hanya memberi kebutuhan minimum O₂ pembakaran lengkap, bukan komposisi gas buang.'],['Angka oktan','Angka oktan menyatakan ketahanan terhadap ketukan dalam kondisi uji, bukan persentase energi, kemurnian, atau banyaknya atom karbon. Skala acuan memakai isooktana dan n-heptana. Campuran bensin nyata tidak harus memiliki komposisi yang sama dengan bahan acuan.'],['Emisi dan perbandingan','CO₂ per massa bahan bakar berbeda dari emisi per energi berguna. Perbandingan lingkungan juga memerlukan efisiensi dan daur hidup. Simulasi memakai hidrokarbon murni dan ArC12,H1,O16; mengabaikan emisi produksi serta penggunaan lahan.']],
[['carbon','Jumlah C alkana (n)',1,12,8,1],['mass','Massa bahan bakar (g)',1,100,10,1],['oxygen','O₂ tersedia (% kebutuhan)',50,150,100,5]],'Hitung kebutuhan oksigen dan hasil CO₂ lengkap. Bandingkan per gram bahan bakar, lalu kurangi oksigen dan jelaskan mengapa model tidak lagi memprediksi hasil CO₂ aktual.',
['Hitung O₂ dan CO₂ untuk pembakaran lengkap 11,4g oktana.','Mengapa angka oktan tidak sama dengan nilai kalor atau persen oktana dalam bensin?','Bandingkan CO₂ per gram metana dan oktana; jelaskan data tambahan untuk perbandingan per energi.'],
'OktanaM114;11.4g=.1mol;O2=1.25mol;CO2=.8mol=35.2g. Metana44/16=2.75g/g;oktana352/114≈3.0877g/g. Oktan ketahanan ketuk bukan nilai kalor,perlu energi dan efisiensi. O2kurang:hasil aktual tidak diprediksi.',
[['Pembakaran lengkap C₈H₁₈ perlu O₂ per mol ...','12,5 mol','8 mol','9 mol','4 mol'],['Angka oktan menunjukkan ...','ketahanan ketukan','nilai kalor pasti','jumlah atom C','persen CO₂'],['Kekurangan O₂ dapat menghasilkan ...','CO','hanya CO₂ selalu','NaCl','He'],['Emisi per gram setara emisi per energi?','tidak, perlu nilai kalor','selalu sama','hanya bergantung warna','tidak perlu efisiensi'],['Metana lengkap menghasilkan CO₂ per mol ...','1 mol','2 mol','4 mol','0 mol']] );
add('lan-golongan','Kimia_Unsur_Golongan_Utama','Kimia Unsur Golongan Utama','families',[
['Alkali dan alkali tanah','Alkali mempunyai elektron valensi ns¹ dan lazim membentuk +1; alkali tanah ns² dan lazim +2. Energi ionisasi dan ukuran atom membantu menjelaskan kecenderungan, tetapi kondisi reaksi dan lapisan permukaan dapat memengaruhi pengamatan.'],['Halogen','Halogen adalah nonlogam dengan konfigurasi valensi ns²np⁵. Dalam model reaksi penggantian larutan, Cl₂ mengoksidasi Br⁻ dan I⁻; Br₂ mengoksidasi I⁻; I₂ tidak mengoksidasi Cl⁻ atau Br⁻. Kekuatan oksidator menurun Cl₂>Br₂>I₂ pada konteks ini.'],['Gas mulia','Kulit valensi penuh menjelaskan reaktivitas yang umumnya rendah. Tidak tepat menyebut semua gas mulia mutlak tidak bereaksi; beberapa senyawa xenon dikenal. He mempunyai dua elektron valensi, bukan delapan.'],['Kegunaan dan pembuktian','NaCl digunakan sebagai bahan garam; Mg dalam paduan; halogen dalam berbagai senyawa; Ar sebagai atmosfer relatif inert. Sifat unsur tidak sama dengan sifat senyawanya. Simulasi penggantian halogen adalah prediksi kualitatif terpilih, bukan instruksi percobaan.']],[],
'Pilih halogen dan ion halida. Gunakan urutan kekuatan oksidator untuk memprediksi apakah terjadi penggantian.',
['Tulis reaksi ion Cl₂ dengan Br⁻ dan identifikasi oksidator serta reduktor.','Bandingkan Br₂+I⁻ dan I₂+Br⁻; jelaskan arah reaksi.','Bandingkan muatan ion alkali/alkali tanah serta jelaskan pengecualian pernyataan gas mulia tidak pernah bereaksi.'],
'Cl2+2Br-→2Cl-+Br2;Cl2oksidator,Br-reduktor. Br2mengoksidasiI- bukan sebaliknya. Alkali+1,alkali tanah+2,He2elektron,senyawaXe dikenal.',
[['Ion alkali lazim bermuatan ...','+1','+2','−2','0'],['Oksidator terkuat pada pilihan ini ...','Cl₂','Br₂','I₂','Br⁻'],['Br₂ dapat mengoksidasi ...','I⁻','Cl⁻','Na⁺','Ar'],['Elektron valensi He ...','2','8','6','1'],['Sifat Na dan NaCl ...','berbeda','identik','selalu sama berbahaya','ditentukan nama saja']] );
add('lan-periode3','Unsur_Periode_Ketiga_dan_Oksidanya','Unsur Periode Ketiga dan Oksidanya','period3',[
['Struktur sepanjang periode','Na, Mg dan Al memiliki ikatan logam; Si membentuk jaringan kovalen; fosfor, sulfur dan klorin memiliki struktur molekuler pada bentuk umum yang dibahas; Ar monoatomik. Titik leleh tidak berubah secara monoton karena struktur zat ikut berubah.'],['Oksida basa','Na₂O bereaksi dengan air menghasilkan NaOH. MgO bersifat basa tetapi tidak boleh dianggap mempunyai kelarutan atau laju reaksi sama dengan Na₂O. Kecenderungan basa ke asam berkaitan dengan karakter logam dan struktur ikatan.'],['Amfoter dan asam','Al₂O₃ bersifat amfoter: dapat bereaksi dengan asam maupun basa kuat pada kondisi sesuai. SiO₂ dan SO₃ diklasifikasikan oksida asam; SiO₂ tidak langsung bereaksi dengan air seperti SO₃. Sifat asam bukan sinonim mudah larut dalam air.'],['Menguji klasifikasi','Respons terhadap asam dan basa memberi petunjuk klasifikasi. Simulasi menampilkan reaksi ideal stoikiometri contoh; tidak menghitung laju, pelarutan, suhu atau semua spesies dalam larutan.']],[],
'Bandingkan lima oksida terhadap air, asam, dan basa. Temukan oksida yang dapat bereaksi dengan kedua jenis pereaksi.',
['Bandingkan Na₂O dan SiO₂ terhadap air; apakah keduanya harus larut?','Jelaskan bukti amfoter Al₂O₃ dari dua reaksi.','Mengapa titik leleh periode ketiga tidak dapat diprediksi hanya dari nomor atom?'],
'Na2O+H2O→2NaOH;SiO2tidakbereaksi langsung air. Al2O3+6H+→2Al3++3H2O;Al2O3+2OH-+3H2O→2[Al(OH)4]-. Struktur logam,jaringan,molekul,monoatomik berbeda.',
[['Oksida amfoter ...','Al₂O₃','Na₂O','SO₃','CO₂'],['SiO₂ dalam air ...','tidak langsung bereaksi','pasti membentuk larutan asam kuat','menjadi NaOH','melepaskan Cl₂'],['Na₂O tergolong ...','basa','asam','amfoter','netral selalu'],['Si padat memiliki ...','jaringan kovalen','molekul Si₂ umum','gas monoatomik','ikatan hidrogen saja'],['Titik leleh dipengaruhi ...','struktur dan interaksi','nomor atom saja','warna saja','nama unsur saja']] );
add('lan-transisi','Unsur_Transisi_Konfigurasi_dan_Sifat','Unsur Transisi: Konfigurasi dan Sifat','transition',[
['Definisi dan konteks','Unsur transisi mempunyai subkulit d belum penuh pada atom atau dapat membentuk kation dengan d belum penuh. Zn dan Zn²⁺ memiliki d¹⁰ sehingga Zn bukan unsur transisi menurut definisi ini, walaupun terletak dalam blok d.'],['Konfigurasi kation','Pada pembentukan kation logam transisi periode pertama, elektron 4s dilepas sebelum 3d. Fe netral [Ar]3d⁶4s² menjadi Fe²⁺ [Ar]3d⁶ dan Fe³⁺ [Ar]3d⁵. Cr dan Cu netral menunjukkan konfigurasi yang perlu diperhatikan sebagai pengecualian pola sederhana.'],['Warna dan magnetisme','Elektron tak berpasangan menimbulkan paramagnetisme. Kompleks dapat berwarna melalui transisi elektron, tetapi d⁰/d¹⁰ tidak selalu menjamin semua senyawa tidak berwarna karena perpindahan muatan dapat berperan. Warna dan spin bergantung lingkungan ligan.'],['Model pengisian','Diagram lima orbital d setara memakai aturan Hund untuk model ion bebas. Nilai spin-only μ≈√(u(u+2)) BM memakai u elektron tak berpasangan. Ini tidak memprediksi otomatis keadaan spin kompleks medan kuat atau seluruh sifat magnet padatan.']],[],
'Pilih kation, hitung elektron d dan elektron tak berpasangan dalam model ion bebas. Bandingkan Fe²⁺, Fe³⁺ dan Zn²⁺.',
['Turunkan konfigurasi Fe²⁺ dan Fe³⁺ dari Fe netral; elektron mana dilepas lebih dahulu?','Hitung u dan μ model untuk d⁵ dan d⁶.','Mengapa hasil model ion bebas tidak selalu berlaku pada kompleks dengan ligan medan kuat?'],
'Fe2+d6,Fe3+d5;4s lebih dulu. Hund d5u5μ√35≈5.916;d6u4μ√24≈4.899. Pemisahan orbital ligan mengubah spin. Znd10bukan transisi definisi ketat.',
[['Fe³⁺ mempunyai ...','d⁵','d⁶','d⁸','d¹⁰'],['Elektron yang dilepas dahulu dari Fe ...','4s','3d','2p','inti'],['d⁵ model Hund memiliki u ...','5','1','0','3'],['Zn²⁺ memiliki ...','d¹⁰','d⁹','d⁵','d⁰'],['Spin kompleks dipengaruhi ...','medan ligan','hanya massa atom','warna kertas','hanya jumlah neutron']] );
add('lan-kompleks','Senyawa_Kompleks_dan_Koordinasi','Senyawa Kompleks dan Koordinasi','complex',[
['Ikatan koordinasi','Ligan menyumbang pasangan elektron kepada pusat logam sebagai asam Lewis. Ligan dapat netral seperti NH₃ dan H₂O atau bermuatan seperti Cl⁻. Bilangan koordinasi menghitung atom donor terikat, bukan selalu jumlah molekul ligan.'],['Muatan dan biloks','Muatan kompleks sama dengan biloks pusat ditambah jumlah muatan ligan. Pada [Co(NH₃)₆]³⁺, NH₃ netral sehingga Co+3. Pada [Fe(CN)₆]⁴⁻, enam CN⁻ memberikan −6 sehingga Fe+2.'],['Dentisitas dan bentuk','en adalah etilendiamina netral bidentat: dua atom donor per ligan. [Co(en)₃]³⁺ memiliki tiga ligan tetapi koordinasi enam. Kompleks koordinasi empat dapat tetrahedral atau planar persegi; jumlah koordinasi saja belum menentukan bentuk.'],['Isomer geometri','Pada kompleks planar persegi MA₂B₂, dua ligan sama bersebelahan adalah cis dan berseberangan trans. Bentuk tersebut berbeda dari proyeksi tetrahedral. Simulasi menampilkan contoh terpilih dan skema geometri, bukan prediksi struktur sembarang kompleks.']],[],
'Jelajahi kompleks, hitung biloks dari muatan, lalu bandingkan jumlah ligan dengan bilangan koordinasi. Periksa cis/trans pada kompleks Pt.',
['Tentukan biloks Fe dalam [Fe(CN)₆]⁴⁻ dengan persamaan muatan.','Bandingkan jumlah ligan dan koordinasi [Co(en)₃]³⁺ dengan [Co(NH₃)₆]³⁺.','Jelaskan cis/trans [Pt(NH₃)₂Cl₂] dan mengapa koordinasi empat tidak selalu tetrahedral.'],
'Fe−6=−4=>Fe+2. Coen3:3ligan bidentat6donor;CoNH36:6monodentat6donor. Pt+2,planar persegi,cisClbersebelahantransberseberangan;NiCl4tetrahedral.',
[['Ligan berperan sebagai ...','donor pasangan elektron','donor neutron','selalu kation','inti logam'],['Biloks Fe pada [Fe(CN)₆]⁴⁻ ...','+2','+4','−4','+6'],['Koordinasi [Co(en)₃]³⁺ ...','6','3','9','1'],['Ligan NH₃ bermuatan ...','0','−1','+1','−3'],['Planar persegi MA₂B₂ dapat mempunyai ...','cis dan trans','hanya tetrahedral','isotop berbeda wajib','koordinasi enam']] );
add('lan-alkohol','Alkohol_Eter_dan_Oksidasi','Alkohol, Eter, dan Oksidasi','alcohol',[
['Klasifikasi alkohol','Primer, sekunder dan tersier ditentukan jumlah atom C yang terikat pada C pembawa OH, bukan jumlah seluruh gugus OH. Etanol primer, propan-2-ol sekunder, 2-metilpropan-2-ol tersier.'],['Oksidasi bertahap','Alkohol primer dapat menjadi aldehida dan selanjutnya asam karboksilat. Pengambilan aldehida dari campuran membantu membatasi oksidasi lanjut. Alkohol sekunder menghasilkan keton; tersier tidak mengalami oksidasi sederhana yang sama tanpa pemutusan rangka karbon.'],['Alkohol versus eter','Alkohol memiliki O–H dan dapat menjadi donor ikatan hidrogen. Eter mempunyai C–O–C tanpa O–H sehingga tidak mendonorkan ikatan hidrogen sesama molekulnya, namun dapat menerimanya dari air. Massa dan bentuk molekul juga memengaruhi titik didih.'],['Batas prediksi','Pilihan oksidasi ringan/lanjut adalah ringkasan hasil umum, bukan resep pereaksi. Eter tidak diperlakukan sebagai alkohol. Reaksi lain seperti dehidrasi alkohol memerlukan kondisi berbeda dan tidak dimodelkan oleh pilihan oksidasi.']],[],
'Bandingkan alkohol primer, sekunder, tersier dan eter pada kondisi oksidasi model ringan atau lanjut.',
['Bandingkan produk etanol pada dua kondisi model.','Jelaskan perbedaan hasil propan-2-ol dan 2-metilpropan-2-ol.','Mengapa etanol dan metoksimetana berbeda interaksi antarmolekul meski sama rumus C₂H₆O?'],
'Etanol→etanal→asam etanoat;sekunderpropan2ol→propanon;tersier tidak oksidasi sederhana tanpa putusC-C. AlkoholOHdonor/akseptor,eterakseptorbukandonor.',
[['Etanol adalah alkohol ...','primer','sekunder','tersier','fenol'],['Propan-2-ol dioksidasi menjadi ...','propanon','propanal','asam etanoat','metana'],['Oksidasi lanjut alkohol primer menghasilkan ...','asam karboksilat','eter selalu','amina','alkana'],['Klasifikasi alkohol berdasar ...','C terikat pada C–OH','seluruh atom H','massa saja','warna'],['Eter dapat ...','menerima ikatan hidrogen dari air','mendonorkan O–H yang dimilikinya','selalu menjadi keton','tergolong alkohol tersier']] );
add('lan-karbonil','Aldehida_Keton_dan_Identifikasi','Aldehida, Keton, dan Identifikasi','carbonyl',[
['Posisi karbonil','Aldehida mempunyai gugus –CHO; keton mempunyai karbonil di antara dua gugus karbon. Propanal dan propanon sama-sama C₃H₆O tetapi isomer gugus fungsi. Keduanya polar, namun tidak memiliki O–H sebagai donor ikatan hidrogen.'],['Uji pembeda','2,4-DNPH memberi endapan dengan aldehida/keton pada kondisi uji. Tollens umumnya positif untuk aldehida alifatik sederhana dan negatif untuk keton sederhana. Uji positif bukan identitas unik; senyawa lain dapat memberi respons pada kondisi tertentu.'],['Reduksi dan oksidasi','Reduksi propanal memberi propan-1-ol, sedangkan reduksi propanon memberi propan-2-ol. Aldehida mudah dioksidasi menjadi asam terkait. Keton tidak mengikuti oksidasi ringan yang sama tanpa perubahan rangka.'],['Menyusun bukti','Gunakan gabungan uji, rumus dan konteks, bukan satu warna saja. Simulasi terbatas pada propanal, propanon dan etanol sebagai kontrol negatif karbonil; tidak mencakup gula pereduksi atau senyawa multifungsi.']],[],
'Pilih sampel dan uji virtual. Susun alur identifikasi dari hasil DNPH dan Tollens, lalu prediksi alkohol hasil reduksi.',
['Susun pembeda propanal, propanon dan etanol dari dua uji.','Tulis alkohol hasil reduksi propanal dan propanon.','Mengapa Tollens positif saja tidak membuktikan nama sampel tertentu?'],
'PropanalDNPH+/Tollens+;propanonDNPH+/Tollens−;etanolkeduanya−dalammodel. Reduksi propanalpropan1ol,propanonpropan2ol. Uji sifat gugus bukan identitas unik.',
[['Gugus aldehida ...','–CHO','–COOH','–O–','–NH₂'],['Propanon memiliki karbonil ...','di antara dua gugus karbon','terikat H terminal','tanpa O','dalam ion Na'],['DNPH pada propanon ...','positif','negatif selalu','membentuk NaCl','menghasilkan logam'],['Propanal direduksi menjadi ...','propan-1-ol','propan-2-ol','etena','metanol'],['Satu uji positif ...','belum menentukan identitas unik','pasti propanal','selalu salah','membuktikan kemurnian']] );
add('lan-asamester','Asam_Karboksilat_Ester_dan_Hidrolisis','Asam Karboksilat, Ester, dan Hidrolisis','ester',[
['Asam dan ester','Asam karboksilat mengandung –COOH dan dapat mendonorkan proton; ester –COOR memiliki gugus alkil menggantikan H pada bagian OH. Etil etanoat memiliki bagian etanoat CH₃COO– dan etil –CH₂CH₃.'],['Hidrolisis dalam asam','Etil etanoat dan air dapat menghasilkan asam etanoat dan etanol dalam kesetimbangan berkatalis asam. Besar konversi bergantung kondisi; satu mol ester yang bereaksi menghasilkan satu mol masing-masing produk.'],['Hidrolisis basa','Ester+OH⁻ menghasilkan karboksilat+alkohol. Untuk etil etanoat, satu mol NaOH dikonsumsi per mol ester; produknya natrium etanoat, bukan asam etanoat bebas dalam campuran basa. Pengasaman selanjutnya merupakan tahap berbeda.'],['Neraca konversi','Model meminta persen konversi yang diasumsikan, bukan menghitung laju atau kesetimbangan. Jumlah berubah x=n₀f. Pada mode basa, OH⁻ awal harus setidaknya x; simulasi mengasumsikan tersedia cukup. Jangan menafsirkan slider sebagai jaminan hasil eksperimen.']],
[['initial','Ester awal (mol)',0.1,2,1,0.1],['conversion','Konversi yang diasumsikan (%)',0,100,50,5]],'Bandingkan produk hidrolisis asam dan basa pada konversi sama. Periksa pereaksi yang dikonsumsi dan ester tersisa.',
['Pada 1mol ester dan konversi60%, hitung ester sisa dan produk.','Bedakan spesies karboksil pada hidrolisis asam dan basa.','Apakah konversi dari slider membuktikan konstanta kesetimbangan? Jelaskan.'],
'x.6mol,sisa.4,etanol.6;asamasam etanoat.6danH2Odikonsumsi.6;basaetanoat.6danOH-.6. Konversi diasumsikan tidak menentukanKtanpa data aktivitas/kondisi.',
[['Etil etanoat mengandung gugus ...','ester','eter saja','aldehida','amina'],['Hidrolisis basa menghasilkan ...','karboksilat dan alkohol','asam bebas selalu','alkana saja','keton saja'],['NaOH per mol monoester ...','1 mol','2 mol','3 mol','0'],['Konversi60% dari1mol menyisakan ...','0,4 mol','0,6 mol','1,6 mol','0 mol'],['Hidrolisis asam adalah ...','reaksi dapat balik','selalu100%','tanpa air','reaksi inti']] );
add('lan-halo','Haloalkana_Substitusi_dan_Eliminasi','Haloalkana, Substitusi, dan Eliminasi','halo',[
['Ikatan C–halogen','Haloalkana memiliki halogen menggantikan H alkana. Ikatan C–X terpolarisasi sehingga C dapat diserang nukleofil. Kemudahan reaksi juga dipengaruhi substrat, gugus pergi dan pelarut; bukan hanya rumus molekul.'],['Substitusi','Model bromoetana dengan OH⁻ dalam medium berair menghasilkan etanol dan Br⁻. Gugus Br diganti OH. Ini merupakan ringkasan stoikiometri, tidak menguraikan semua tahapan mekanisme atau konstanta laju.'],['Eliminasi','Basa dalam medium alkohol dengan pemanasan dapat mendukung eliminasi membentuk etena: C₂H₅Br+OH⁻→C₂H₄+H₂O+Br⁻. H pada karbon tetangga dilepas bersama gugus pergi; C=C terbentuk.'],['Kompetisi','Substitusi dan eliminasi dapat bersaing. Slider fraksi eliminasi adalah skenario hasil, bukan prediksi dari suhu atau pelarut. Untuk konversi penuh, jumlah etanol+etena sama dengan bromoetana awal dan satu mol Br⁻ dihasilkan per mol awal.']],
[['initial','Bromoetana awal (mol)',0.1,2,1,0.1],['elimination','Fraksi eliminasi diasumsikan (%)',0,100,50,5]],'Ubah fraksi eliminasi pada konversi penuh dan bandingkan produk, sambil menjaga neraca karbon dan bromida.',
['Untuk1mol awal dan30% eliminasi, hitung etanol, etena dan Br⁻.','Bandingkan perubahan ikatan pada substitusi dan eliminasi.','Mengapa pilihan medium saja belum cukup menentukan persen produk secara pasti?'],
'Etanol.7,etena.3,Br-1mol,air.3. SubstitusiBrdigantiOH,eliminasiH/BrmembentukC=C. Kompetisi bergantungsubstrat,basa,pelarut,suhu;fraksi input bukan prediksi.',
[['Substitusi bromoetana oleh OH⁻ menghasilkan ...','etanol','etena saja','etuna','benzena'],['Eliminasi membentuk ...','C=C','ikatan inti','NaBr tanpa organik','COOH selalu'],['Eliminasi30% dari1mol memberi etena ...','0,3 mol','0,7 mol','1,3 mol','3 mol'],['Br⁻ pada konversi penuh1mol ...','1 mol','0,3 mol','0,7 mol','2 mol'],['Fraksi simulasi adalah ...','skenario yang ditentukan pengguna','data eksperimen pasti','fungsi suhu terukur','konstanta universal']] );
add('lan-titrasiredoks','Titrasi_Redoks_dan_Kadar_Besi','Titrasi Redoks dan Kadar Besi','redox',[
['Reaksi analitik','Dalam suasana asam, MnO₄⁻+5Fe²⁺+8H⁺→Mn²⁺+5Fe³⁺+4H₂O. Satu mol permanganat setara lima mol Fe²⁺. Lingkungan asam penting: produk reduksi mangan berubah bila kondisi berbeda.'],['Ekuivalen dan titik akhir','Titik ekuivalen ditentukan stoikiometri. Titik akhir ditandai sinyal yang diamati, pada permanganat berupa warna merah muda pucat persisten dari sedikit kelebihan titran. Keduanya berdekatan tetapi bukan konsep yang sama.'],['Menentukan kadar','nFe=5CMnVMn, dengan V dalam liter. Konsentrasi Fe dalam aliquot=nFe/Valiquot. Jika larutan awal diencerkan faktor F, konsentrasi awal=F kali konsentrasi aliquot. Simulasi memberi standar Fe0,1M untuk latihan menemukan volume ekuivalen.'],['Mutu hasil','Standarisasi titran, pembacaan buret, blanko dan pengulangan memengaruhi hasil. Menggunakan volume yang terlalu jauh melewati ekuivalen akan memberi estimasi kadar terlalu tinggi. Model stoikiometri mengabaikan potensial elektroda, pencampuran dan gangguan ion lain.']],
[['aliquot','Aliquot Fe²⁺0,100M (mL)',10,50,25,5],['titrant','KMnO₄ (M)',0.01,0.05,0.02,0.005],['volume','Volume titran (mL)',0,60,25,0.5]],'Naikkan volume titran sampai melewati ekuivalen. Bandingkan jumlah Fe²⁺ tersisa, kelebihan permanganat dan kadar yang dihitung dari volume pilihan.',
['Untuk25mL Fe²⁺0,100M dan KMnO₄0,020M, hitung volume ekuivalen.','Jika titik akhir dicatat26mL, berapa konsentrasi Fe terhitung dan arah kesalahannya?','Bedakan ekuivalen, titik akhir dan peran standarisasi.'],
'Fe.0025mol;Mn.0005mol;V25mL.26mL=>Fe.104M,tinggi4%. Mn:Fe1:5. Ekuivalenstoikiometri,akhirindikasi,standarisasi memastikanC.',
[['Rasio MnO₄⁻:Fe²⁺ adalah ...','1:5','1:1','5:1','2:3'],['V harus dimasukkan ke n=CV sebagai ...','liter','mL tanpa konversi','gram','detik'],['Lewat titik akhir terlalu banyak membuat kadar ...','terlalu tinggi','terlalu rendah selalu','tetap pasti','negatif'],['Permanganat direduksi dalam asam menjadi ...','Mn²⁺','Mn logam','MnO₄²⁻ selalu','Fe³⁺'],['Ekuivalen ditentukan oleh ...','stoikiometri','warna tabung saja','ukuran labu saja','massa buret']] );
add('lan-gravimetri','Gravimetri_dan_Penentuan_Klorida','Gravimetri dan Penentuan Klorida','gravimetry',[
['Dasar gravimetri','Analit diubah menjadi senyawa dengan komposisi diketahui lalu ditimbang. Untuk Cl⁻, Ag⁺+Cl⁻→AgCl(s). Mol Cl sama dengan mol AgCl. Massa endapan tidak sama dengan massa klorida karena endapan juga mengandung Ag.'],['Faktor gravimetri','Menggunakan MAgCl143,32 dan ArCl35,45, massaCl=mAgCl×35,45/143,32. Persen klorida=100massaCl/massa sampel. Timbangan mengukur wadah+endapan; massa wadah harus dikurangkan.'],['Sumber bias','Endapan hilang menyebabkan kadar rendah. Air tersisa atau pengotor menambah massa sehingga kadar tampak tinggi. Pengeringan sampai massa konstan mendukung, tetapi tidak sendirian membuktikan kemurnian endapan.'],['Model mutu','Simulasi memakai sampel1g dengan kadar Cl sebenarnya20%. Ubah fraksi endapan berhasil dikumpulkan dan massa kontaminan. Program membandingkan kadar terhitung dengan kadar benar untuk menunjukkan bahwa dua kesalahan berlawanan dapat saling menutupi.']],
[['recovery','Endapan terkumpul (%)',70,100,100,1],['contamination','Air/pengotor tertimbang (g)',0,0.2,0,0.01]],'Bandingkan kehilangan endapan dengan penambahan pengotor. Cari kondisi kadar tampak benar walaupun prosedur mengandung dua kesalahan.',
['Hitung massa AgCl ideal dari0,200g Cl dan faktor gravimetrinya.','Bandingkan kadar pada recovery90% tanpa pengotor dengan recovery100% dan pengotor0,05g.','Apakah hasil mendekati20% pasti membuktikan prosedur baik? Jelaskan.'],
'AgCl=.2*143.32/35.45≈.808575g;f=.24734999. recovery90=>18%;kontaminan.05=>21.2367%. Bias berlawanan dapat menutupi,akurasi kebetulan bukanjaminanprosedur.',
[['Mol Cl⁻ dibanding AgCl ...','1:1','1:2','2:1','tidak berkaitan'],['Massa Cl dihitung dari AgCl dengan faktor ...','35,45/143,32','143,32/35,45','1 selalu','35,45×143,32'],['Endapan hilang membuat kadar ...','rendah','tinggi','tetap','selalu100%'],['Air tertinggal membuat massa ...','terlalu tinggi','terlalu rendah','nol','tidak berubah'],['Massa konstan membuktikan ...','kestabilan massa pada kondisi pengeringan','kemurnian mutlak','tanpa bias pasti','komposisi sembarang']] );
add('lan-kalibrasi','Kurva_Kalibrasi_dan_Spektrofotometri','Kurva Kalibrasi dan Spektrofotometri','calibration',[
['Absorbansi','Absorbansi A=−log₁₀T dengan T fraksi cahaya diteruskan. Untuk kondisi sesuai hukum Beer–Lambert, A=εbc. Panjang lintasan, panjang gelombang, matriks dan rentang konsentrasi harus dikendalikan. Hubungan linear tidak berlaku tanpa batas.'],['Kalibrasi empiris','Larutan standar konsentrasi diketahui menghasilkan garis A=mc+b. Intersep dapat mencerminkan latar; pengurangan blanko harus konsisten. Simulasi memakai lima standar0,2,4,6,8mg/L dan regresi kuadrat terkecil, bukan memaksa garis melalui nol.'],['Sampel dan pengenceran','Konsentrasi larutan yang diukur=(A−b)/m; konsentrasi asal=F kali hasil tersebut. Nilai absorbansi di luar rentang standar berarti ekstrapolasi, sehingga perlu pengenceran atau perluasan kalibrasi tervalidasi, bukan menerima hasil secara otomatis.'],['Kualitas data','R² mengukur kecocokan garis terhadap data tetapi tidak menjamin metode akurat atau bebas gangguan. Simulasi memberi variasi terstruktur pada standar untuk mempelajari residual; variasi ini bukan ketidakpastian instrumen nyata.']],
[['noise','Besaran variasi standar (A)',0,0.1,0,0.01],['absorbance','Absorbansi sampel',0,1.2,0.42,0.01],['dilution','Faktor pengenceran',1,20,5,1]],'Ubah variasi standar, absorbansi sampel dan faktor pengenceran. Bedakan interpolasi dengan ekstrapolasi serta cek pengaruh intersep.',
['Tanpa variasi, gunakan A=0,1c+0,02 untuk A0,42 dan F5.','Apa yang harus dilakukan jika A sampel1,1 di atas standar tertinggi?','Mengapa R² tinggi belum membuktikan tidak ada gangguan matriks?'],
'cukur4mg/L,asal20mg/L. StandartertinggiA.82,c8;A1.1ekstrapolasi perlu pengenceran/revalidasi. R2bukanjaminanakurasi,blanko/intersep/matriks dapat bias.',
[['A=0,1c+0,02 dan A0,42 memberi c ...','4 mg/L','4,2 mg/L','0,04 mg/L','42 mg/L'],['Faktor pengenceran5 diterapkan dengan ...','mengalikan kadar ukur5','membagi5','menambah5','mengabaikan'],['R² tinggi menjamin akurasi?','tidak','ya mutlak','hanya untuk semua warna','selalu tanpa blanko'],['A di luar rentang standar adalah ...','ekstrapolasi','interpolasi','titrasi','kondensasi'],['Jika T=0,1 maka A ...','1','0,1','10','−1']] );
add('lan-peluruhan','Radioaktivitas_dan_Waktu_Paruh','Radioaktivitas dan Waktu Paruh','decay',[
['Peluruhan statistik','Peluruhan satu inti bersifat probabilistik. Untuk populasi besar satu radionuklida, nilai harapan N=N₀2^(−t/t½). Setiap satu waktu paruh, separuh populasi yang masih ada meluruh, bukan jumlah tetap dari populasi awal.'],['Aktivitas','Aktivitas A=λN dengan λ=ln2/t½. Jika waktu paruh dalam detik, aktivitas dalam Bq atau peluruhan per detik. Aktivitas turun sebanding N untuk satu radionuklida tanpa tambahan sumber.'],['Membaca grafik','Grafik sisa terhadap waktu berbentuk eksponensial. Pada dua waktu paruh tersisa25%, pada tiga12,5%. Waktu paruh bukan waktu sampai seluruh inti pasti habis; jumlah inti terukur dan deteksi mempunyai keterbatasan statistik.'],['Asumsi dan penggunaan','Model satu tahap dengan produk anak dianggap stabil, tanpa peluruhan berantai atau pengisian sumber. Nilai waktu paruh dipilih untuk latihan, bukan identitas isotop tertentu. Aktivitas tidak sama dengan dosis yang diterima tubuh.']],
[['half','Waktu paruh model (s)',1,20,5,1],['time','Waktu berlalu (s)',0,100,10,1],['population','N₀ (juta inti)',1,10,1,1]],'Bandingkan fraksi sisa pada satu, dua dan tiga waktu paruh. Ubah N₀ dan pisahkan pengaruhnya terhadap fraksi sisa dan aktivitas.',
['UntukN₀1juta,t½5s,t10s, hitungN dan aktivitas.','Apakah menggandakanN₀ mengubah waktu paruh atau fraksi sisa?','Bedakan aktivitas, jumlah inti dan dosis; jelaskan batas model satu tahap.'],
'N250000,A=ln2/5*250000≈34657.36Bq. N0dua kali=>N/Adua kali tapi fraksi/t½tetap. Aktivitaspeluruhan/s bukan dosis,anakdianggapstabil.',
[['Dua waktu paruh menyisakan ...','25%','50%','0%','75%'],['Aktivitas satuan Bq berarti ...','peluruhan per detik','energi per kg','jumlah mol','panjang'],['Setelah satu waktu paruh berikutnya ...','separuh yang tersisa meluruh','separuh awal selalu meluruh','semua pasti habis','N bertambah'],['λ sama dengan ...','ln2/t½','t½/ln2','2t½','N₀t'],['Aktivitas sama dengan dosis?','tidak','ya selalu','hanya tergantung nama','selalu dalam kg']] );
add('lan-inti','Reaksi_Inti_Fisi_dan_Fusi','Reaksi Inti, Fisi, dan Fusi','nuclear',[
['Neraca reaksi inti','Dalam persamaan inti, jumlah nomor massa A dan nomor atom Z setara pada kedua sisi. Alfa membawa A4,Z2; beta minus A0,Z−1; beta plus A0,Z+1; gamma tidak mengubah A atau Z. Neutrino pada proses beta tetap relevan terhadap konservasi energi walaupun tidak mengubah neraca A/Z.'],['Fisi dan fusi','Fisi membelah inti berat; fusi menggabungkan inti ringan. Keduanya dapat melepaskan energi jika massa total produk lebih kecil daripada pereaksi. Kekekalan A tidak berarti massa diam total tidak dapat berubah: sebagian menjadi energi.'],['Energi massa','Q=Δmc², dengan1u setara sekitar931,5MeV/c². Jika Δm positif, energi dilepas; jika negatif, energi perlu disuplai. Nilai Δm pada slider adalah parameter latihan, bukan nilai otomatis dari contoh reaksi yang dipilih.'],['Aplikasi dan batas','Radioisotop digunakan sebagai penjejak dan sumber radiasi, sementara energi inti juga memiliki tantangan pengelolaan. Media ini memeriksa persamaan serta konversi massa–energi, bukan model reaktor, dosis atau rancangan perangkat nuklir.']],
[['defect','Selisih massa pereaksi−produk (u)',-0.02,0.05,0.01,0.001]],'Pilih reaksi inti, periksa neraca A/Z dan ubah selisih massa untuk memahami tanda energi.',
['Tentukan inti anak pada U238 alfa dan C14 beta minus.','Periksa neraca A/Z untuk contoh fisi dan fusi yang tersedia.','HitungQ untukΔm0,01u dan−0,01u; jelaskan mengapa A tetap tetapi massa diam dapat berubah.'],
'U238Z92→Th234Z90+He4Z2;C14Z6→N14Z7+e0Z−1+antineutrino. Fisi235+1=141+92+3,Z92=56+36;fusi2+3=4+1,Z1+1=2. ±.01u=>±9.315MeV. Nomormassa hitungnukleon,bukanmassa tepat.',
[['Peluruhan alfa mengubah A,Z menjadi ...','A−4,Z−2','A,Z+1','A+4,Z+2','A−2,Z−4'],['Beta minus mengubah Z ...','naik1','turun1','tetap selalu','naik2'],['Fusi adalah ...','penggabungan inti ringan','pemutusan molekul','distilasi','pembelahan inti berat'],['Δm positif berarti ...','energi dilepas','energi wajib diserap','A hilang','Z tidak kekal'],['Gamma sendiri mengubah A/Z ...','tidak','A turun4','Z naik1','A naik1']] );
module.exports=topics;
