'use strict';
const $=id=>document.getElementById(id),val=id=>Number($(id).value),fmt=(n,d=4)=>Number(n).toLocaleString('id-ID',{maximumFractionDigits:d});
function choose(id,label,options){const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');s.id=id;options.forEach(([v,t])=>s.add(new Option(t,v)));l.append(s);$('controls').append(l);s.addEventListener('change',update)}
const isomers=[['Rantai; C₄H₁₀','CH₃–CH₂–CH₂–CH₃','CH₃–CH(CH₃)–CH₃'],['Posisi; C₄H₈','CH₂=CH–CH₂–CH₃','CH₃–CH=CH–CH₃'],['Gugus fungsi; C₂H₆O','CH₃–CH₂–OH','CH₃–O–CH₃'],['Geometri; C₄H₈','cis-but-2-ena: CH₃ satu sisi','trans-but-2-ena: CH₃ berseberangan']];
const groups=[['Etanol','CH₃CH₂–OH','Alkohol','Ya; O–H'],['Metoksimetana','CH₃–O–CH₃','Eter','Tidak; tidak ada O–H'],['Etanal','CH₃–CHO','Aldehida','Tidak'],['Propanon','CH₃–CO–CH₃','Keton','Tidak'],['Asam etanoat','CH₃–COOH','Asam karboksilat','Ya; O–H'],['Etil etanoat','CH₃–COO–CH₂CH₃','Ester','Tidak'],['Metilamina','CH₃–NH₂','Amina primer','Ya; N–H']];
function equilibrium(a,b,k){let lo=0,hi=Math.min(a,b);for(let i=0;i<80;i++){const x=(lo+hi)/2;if(x*x>k*(a-x)*(b-x))hi=x;else lo=x}return(lo+hi)/2}
function glycine(ph){const h=10**-ph,k1=10**-2.34,k2=10**-9.60,d=h*h+k1*h+k1*k2;return{plus:h*h/d,zero:k1*h/d,minus:k1*k2/d}}
function rate(s,km,vmax,i){return vmax*s/(km*(1+i)+s)}
function polymer(n,mode){return mode==='addition'?{mass:28*n,water:0,input:28*n}:{mass:90*n-18*(n-1),water:n-1,input:90*n}}
function dna(s){const map={A:'T',T:'A',G:'C',C:'G'},complement=[...s].map(x=>map[x]).join(''),gc=[...s].filter(x=>x==='G'||x==='C').length;return{complement,reverse:[...complement].reverse().join(''),gc:100*gc/s.length,h:2*s.length+gc}}
function bar(label,n,max=100){return '<p>'+label+': '+fmt(n)+'</p><div class="track"><i style="width:'+Math.max(0,Math.min(100,n/max*100))+'%"></i></div>'}
function cards(items){return items.map(x=>'<p style="padding:12px;border:1px solid #52525b;border-radius:8px">'+x+'</p>').join('')}
function chain(n,kind){let out='';for(let i=0;i<n;i++){const x=25+(i%10)*39,y=30+Math.floor(i/10)*65;if(i%10)out+='<line x1="'+(x-39)+'" y1="'+y+'" x2="'+x+'" y2="'+y+'" stroke="#a78bfa"/>';out+='<circle cx="'+x+'" cy="'+y+'" r="15" fill="#7c3aed"/><text x="'+x+'" y="'+(y+4)+'" text-anchor="middle" fill="white" font-size="10">'+(i+1)+'</text>'}return '<svg viewBox="0 0 420 200" role="img" aria-label="'+kind+'">'+out+'</svg><p>Unit bernomor; rantai diteruskan ke baris berikutnya, ukuran tidak berskala.</p>'}
function setup(){const s=TOPIC.sim;
if(s==='isomer')choose('pair','Pasangan',isomers.map((x,i)=>[i,x[0]]));
if(s==='groups')choose('compound','Senyawa',groups.map((x,i)=>[i,x[0]]));
if(s==='polymer')choose('mode','Reaksi',[['addition','Adisi etena'],['condensation','Kondensasi asam hidroksi (M90)']]);
if(s==='carb'){choose('sample','Sampel',[['glucose','Glukosa'],['fructose','Fruktosa'],['sucrose','Sukrosa'],['maltose','Maltosa'],['starch','Pati']]);choose('hydrolysis','Kondisi',[['no','Sebelum hidrolisis'],['yes','Setelah hidrolisis sempurna']])}
if(s==='dna')choose('sequence','Untai DNA 5′→3′',[['ATGCCA','ATGCCA'],['AAAAAA','AAAAAA'],['GCGCGC','GCGCGC'],['ATATGCGA','ATATGCGA']]);
update()}
let lastResult='';
function update(){let text='',visual='';const s=TOPIC.sim;
if(s==='isomer'){const p=isomers[val('pair')];text='Pasangan isomer '+p[0]+'. '+p[1]+' dibandingkan '+p[2]+'. Bandingkan atom, konektivitas, dan orientasi.';visual=cards(p.slice(1));if(val('pair')===3){visual='<svg viewBox="0 0 420 190" role="img" aria-label="Cis dan trans but-2-ena"><g stroke="#a78bfa" stroke-width="2"><path d="M60 90H130M60 96H130M60 90L30 55M60 96L30 135M130 90L165 55M130 96L165 135M260 90H330M260 96H330M260 90L225 55M260 96L225 135M330 90L370 55M330 96L370 135"/></g><g fill="white" text-anchor="middle" font-size="14"><text x="30" y="45">CH₃</text><text x="165" y="45">CH₃</text><text x="30" y="155">H</text><text x="165" y="155">H</text><text x="225" y="45">CH₃</text><text x="370" y="45">H</text><text x="225" y="155">H</text><text x="370" y="155">CH₃</text><text x="95" y="180">cis</text><text x="295" y="180">trans</text></g></svg>'}}
if(s==='groups'){const g=groups[val('compound')];text=g[0]+': '+g[1]+'. Gugus '+g[2]+'. Donor ikatan hidrogen: '+g[3]+'.';visual=cards([g[1],g[2], 'Rantai hidrokarbon dan gugus polar bersama-sama menentukan sifat.'])}
if(s==='reaction'){const a=val('acid'),b=val('alcohol'),k=val('constant'),x=equilibrium(a,b,k);text='Asam='+fmt(a-x)+' mol; alkohol='+fmt(b-x)+' mol; ester='+fmt(x)+' mol; air='+fmt(x)+' mol. Konversi asam='+fmt(100*x/a)+'%. Q='+fmt(x*x/((a-x)*(b-x)))+'. Model ideal, produk awal nol.';visual=bar('Asam tersisa (mol)',a-x,4)+bar('Alkohol tersisa (mol)',b-x,4)+bar('Ester (mol)',x,4)+bar('Air (mol)',x,4)}
if(s==='aromatic'){const p=val('position'),d=Math.min(p-1,7-p),name=['','orto','meta','para'][d];text='Dua CH₃ pada C1 dan C'+p+': '+name+'-dimetilbenzena. Penomoran ekuivalen terdekat: 1,'+(d+1)+'. Lingkaran menyatakan delokalisasi π.';const pts=Array.from({length:6},(_,i)=>[210+75*Math.sin(i*Math.PI/3),115-75*Math.cos(i*Math.PI/3)]);visual='<svg viewBox="0 0 420 250" role="img" aria-label="Cincin dimetilbenzena"><polygon points="'+pts.map(v=>v.join(',')).join(' ')+'" fill="none" stroke="#a78bfa" stroke-width="3"/><circle cx="210" cy="115" r="43" fill="none" stroke="#34d399"/>'+pts.map(([x,y],i)=>'<text x="'+(210+(x-210)*1.35)+'" y="'+(120+(y-115)*1.3)+'" fill="white" text-anchor="middle">'+(i===0||i===p-1?'CH₃':i+1)+'</text>').join('')+'</svg>'}
if(s==='polymer'){const n=val('units'),r=polymer(n,$('mode').value);text='Satu rantai dari '+n+' monomer: M model='+fmt(r.mass)+' g/mol; '+r.water+' molekul H₂O per rantai. Neraca untuk 1 mol rantai: '+r.input+' = '+r.mass+' + '+18*r.water+' g. Adisi mengabaikan gugus ujung; kondensasi linear tanpa siklus.';visual=chain(n,'Unit rantai polimer')}
if(s==='carb'){const a=$('sample').value,h=$('hydrolysis').value==='yes',reducing=h||['glucose','fructose','maltose'].includes(a),iodine=a==='starch'&&!h;const products={glucose:'Glukosa tetap monosakarida',fructose:'Fruktosa tetap monosakarida',sucrose:'Glukosa + fruktosa',maltose:'Dua glukosa',starch:'Glukosa setelah hidrolisis lengkap'};text=$('sample').selectedOptions[0].textContent+'; '+(h?products[a]:'Sampel belum dihidrolisis')+'. Benedict: '+(reducing?'positif':'negatif dalam model kualitatif')+'. Iodin: '+(iodine?'biru kehitaman':'tidak membentuk kompleks biru pati')+'. Pati diperlakukan negatif pada Benedict standar model sekolah; ujung pereduksi dan batas deteksi diabaikan.';visual=cards(['Benedict: '+(reducing?'gula pereduksi terdeteksi':'tidak terdeteksi pada model'),'Iodin: '+(iodine?'pati terdeteksi':'pati tidak terdeteksi')])}
if(s==='protein'){const f=glycine(val('ph'));text='Glisina pH='+fmt(val('ph'))+': kation '+fmt(100*f.plus)+'%, zwitterion '+fmt(100*f.zero)+'%, anion '+fmt(100*f.minus)+'%. Muatan rata-rata='+fmt(f.plus-f.minus)+'. pI model=5,97. Fraksi merupakan kesetimbangan, bukan satu bentuk tunggal mutlak.';visual=bar('H₃N⁺–CH₂–COOH (%)',100*f.plus)+bar('H₃N⁺–CH₂–COO⁻ (%)',100*f.zero)+bar('H₂N–CH₂–COO⁻ (%)',100*f.minus)}
if(s==='enzyme'){const km=val('km'),vmax=val('vmax'),i=val('inhibitor'),s0=val('substrate'),v=rate(s0,km,vmax,i);text='Km tampak='+fmt(km*(1+i))+' mM; v='+fmt(v)+' µmol/menit; tanpa inhibitor='+fmt(rate(s0,km,vmax,0))+' µmol/menit. Vmax tetap '+vmax+'. Model laju awal, Ki=1 mM.';const line=j=>Array.from({length:81},(_,n)=>{const x=n/4;return(40+17*x)+','+(185-150*rate(x,km,vmax,j)/vmax)}).join(' ');visual='<svg viewBox="0 0 420 230" role="img" aria-label="Laju awal terhadap substrat"><path d="M40 20V185H385" fill="none" stroke="white"/><polyline points="'+line(0)+'" fill="none" stroke="#a78bfa" stroke-width="3"/><polyline points="'+line(i)+'" fill="none" stroke="#34d399" stroke-width="3"/><circle cx="'+(40+17*s0)+'" cy="'+(185-150*v/vmax)+'" r="5" fill="white"/><g fill="white" font-size="12"><text x="45" y="16">v: 0–'+vmax+' µmol/menit</text><text x="40" y="215">[S]: 0–20 mM; ungu=tanpa, hijau=dengan inhibitor</text></g></svg>'}
if(s==='lipid'){const n=val('mol'),d=val('double');text='Untuk '+fmt(n)+' mol trigliserida dengan '+d+' C=C per molekul: hidrogenasi lengkap perlu H₂='+fmt(n*d)+' mol. Penyabunan terpisah perlu NaOH='+fmt(3*n)+' mol, menghasilkan gliserol='+fmt(n)+' mol dan sabun='+fmt(3*n)+' mol. Kedua proses dibandingkan, bukan dilakukan berurutan dalam model.';visual=bar('H₂ (mol)',n*d,18)+bar('NaOH (mol)',3*n,18)+cards(['Kepala COO⁻ Na⁺ — ekor hidrokarbon','Air ⇄ kepala hidrofilik | ekor hidrofobik ⇄ minyak'])}
if(s==='dna'){const seq=$('sequence').value,r=dna(seq);text='Untai 5′ '+seq+' 3′; komplemen sejajar 3′ '+r.complement+' 5′; reverse complement 5′ '+r.reverse+' 3′. GC='+fmt(r.gc)+'%; ikatan hidrogen model='+r.h+'.';visual='<table><caption>Pasangan basa antiparalel</caption><tr><th>5′→3′</th>'+[...seq].map(b=>'<td>'+b+'</td>').join('')+'</tr><tr><th>Ikatan H</th>'+[...seq].map(b=>'<td>'+(b==='G'||b==='C'?3:2)+'</td>').join('')+'</tr><tr><th>3′→5′</th>'+[...r.complement].map(b=>'<td>'+b+'</td>').join('')+'</tr></table>'}
lastResult=text;$('result').textContent=text;$('visual').innerHTML=visual;document.querySelectorAll('[data-value]').forEach(e=>e.textContent=$(e.dataset.value).value);
}
function save(){if(window.PortalSubmission?.isFinal())return;try{const d={};document.querySelectorAll('[data-answer]').forEach(e=>d[e.id]=e.value);localStorage.setItem(STORAGE_KEY,JSON.stringify(d));$('draft-status').textContent='Draf tersimpan pada perangkat.'}catch(_){$('draft-status').textContent='Draf belum tersimpan. Penyimpanan browser tidak tersedia.'}}
function start(){setup();try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');Object.entries(d).forEach(([id,v])=>{if($(id)&&$(id).hasAttribute('data-answer'))$(id).value=v})}catch(_){}$('student-date').value=new Date().toLocaleDateString('id-ID');document.querySelectorAll('[data-answer]').forEach(e=>e.addEventListener('input',save));document.querySelectorAll('#controls input').forEach(e=>e.addEventListener('input',update));$('record').onclick=()=>{if(window.PortalSubmission?.isFinal()||$('lks-observasi').disabled)return;const inputs=[...$('controls').querySelectorAll('input,select')].map(e=>e.id+'='+e.value).join('; ');$('lks-observasi').value+=($('lks-observasi').value?'\n\n':'')+inputs+'\n'+lastResult;save()};}
document.addEventListener('DOMContentLoaded',start);


