const q=(question,options,answer)=>({question,options,answer});
const topics=[];
function add(id,file,title,sim,lessons,controls,task,lks,rubric,quiz){topics.push({id,file,title,sim,goals:['Menjelaskan hubungan struktur dan sifat pada '+title,'Membandingkan hasil eksplorasi dengan prediksi','Menyusun kesimpulan berbasis data dan batas model'],intro:task,lessons,controls,task,lks,rubric,quiz})}
add('org-isomer','Isomer_Struktur_dan_Geometri','Isomer Struktur dan Geometri','isomer',[
['Rumus dan konektivitas','Isomer memiliki rumus molekul sama tetapi susunan berbeda. Butana dan 2-metilpropana sama-sama C₄H₁₀, namun kerangka karbonnya berbeda. Menggambar rantai yang sama dari arah berlawanan tidak menghasilkan isomer baru.'],
['Posisi dan gugus fungsi','But-1-ena dan but-2-ena berbeda posisi ikatan rangkap. Etanol dan metoksimetana sama-sama C₂H₆O tetapi berbeda gugus fungsi. Klasifikasi isomer struktur ditentukan dari konektivitas, bukan sekadar bentuk gambar.'],
['Isomer geometri','Rotasi ikatan C=C terbatas. Cis/trans dapat dibedakan pada but-2-ena karena masing-masing C rangkap mengikat dua substituen berbeda. But-1-ena tidak memiliki pasangan cis/trans sebab salah satu C mengikat dua H.'],
['Cara memeriksa','Hitung atom, periksa ikatan, lalu bandingkan posisi substituen. Cis/trans tidak berlaku untuk semua alkena; penamaan E/Z diperlukan untuk kasus lebih umum. Model ini hanya menampilkan pasangan terpilih, bukan generator seluruh isomer.']],[],
'Pilih pasangan, prediksi jenis isomernya, lalu bandingkan rumus serta strukturnya.',
['Bandingkan butana dan 2-metilpropana: buktikan rumus sama dan kerangka berbeda.','Mengapa but-2-ena memiliki cis/trans tetapi but-1-ena tidak?','Bandingkan etanol dan metoksimetana; jelaskan pengaruh gugus fungsi terhadap kemampuan donor ikatan hidrogen.'],
'C4H10 kerangka lurus/cabang; tiap C pada but-2-ena memiliki H dan CH3, but-1-ena memiliki CH2. Etanol donor O-H, eter bukan donor tetapi akseptor.',
[q('Butana dan 2-metilpropana adalah isomer ...',['rantai','geometri','isotop','konformasi saja'],0),q('Syarat isomer adalah ...',['rumus molekul sama','massa berbeda','jumlah C berbeda','selalu bentuk cis'],0),q('Alkena yang memiliki cis/trans ...',['etena','propena','but-2-ena','but-1-ena'],2),q('Etanol dan metoksimetana berbeda ...',['jumlah O','gugus fungsi','jumlah H','rumus molekul'],1),q('Membalik gambar butana menghasilkan ...',['unsur baru','isomer baru pasti','senyawa yang sama','alkena'],2)]);
add('org-gugus','Gugus_Fungsi_dan_Tata_Nama','Gugus Fungsi dan Tata Nama','groups',[
['Gugus fungsi','Gugus fungsi merupakan bagian struktur yang membantu menjelaskan reaktivitas. Alkohol memiliki R–OH, eter R–O–R′, aldehida R–CHO, keton R–CO–R′, asam karboksilat R–COOH, ester R–COO–R′, dan amina mengandung N sebagai turunan amonia.'],
['Penamaan sederhana','Pilih rantai induk yang memuat gugus utama, beri nomor sehingga lokan gugus utama rendah, lalu gunakan akhiran sesuai golongan. Contoh propan-1-ol, propanon, etanal dan asam etanoat. Ester dinamai dari alkil pada O diikuti nama karboksilat: etil etanoat.'],
['Struktur menentukan interaksi','Alkohol dan asam dapat mendonorkan ikatan hidrogen. Eter, keton, aldehida dan ester dapat menerima ikatan hidrogen tetapi tidak mendonorkan dari O jika tidak ada O–H. Kelarutan juga dipengaruhi panjang bagian hidrokarbon; satu gugus polar tidak menjamin semua senyawa larut.'],
['Batas klasifikasi','Satu molekul dapat memiliki beberapa gugus fungsi sekaligus. Fenol memiliki OH langsung pada cincin aromatik dan tidak diklasifikasikan sebagai alkohol alifatik. Pelajari contoh ini sebelum menerapkan aturan pada molekul kompleks.']],[],
'Jelajahi kartu struktur. Tentukan gugus utama, nama, dan kemampuan donor ikatan hidrogennya.',
['Bedakan posisi karbonil pada etanal dan propanon.','Bandingkan alkohol dengan eter sebagai donor dan akseptor ikatan hidrogen.','Jelaskan bagian alkil dan karboksilat pada etil etanoat.'],
'Aldehida karbonil terminal terikat H; keton karbonil di antara C. Alkohol donor/akseptor, eter akseptor tanpa donor O-H. CH3COOCH2CH3: etil dari OCH2CH3 dan etanoat dari CH3COO.',
[q('CH₃CHO termasuk ...',['keton','aldehida','eter','amina'],1),q('CH₃COCH₃ bernama ...',['propanon','propanal','etanol','asam propanoat'],0),q('Gugus ester adalah ...',['R–O–R','R–CHO','R–COO–R','R–NH₂'],2),q('Donor ikatan hidrogen memiliki ...',['hanya C–C','O–H pada alkohol','hanya C=O','hanya C–H'],1),q('OH langsung pada benzena disebut ...',['eter','alkana','ester','fenol'],3)]);
add('org-reaksi','Reaksi_Organik_dan_Esterifikasi','Reaksi Organik dan Esterifikasi','reaction',[
['Pola reaksi','Adisi menambahkan atom pada ikatan rangkap, substitusi mengganti gugus, eliminasi membentuk ikatan rangkap melalui pelepasan gugus, dan oksidasi alkohol dapat menghasilkan karbonil. Kondisi reaksi menentukan produk; tidak semua alkohol teroksidasi dengan cara sama.'],
['Esterifikasi','Asam etanoat + etanol ⇌ etil etanoat + air. Perbandingan mol 1:1:1:1. Katalis asam mempercepat tercapainya kesetimbangan tanpa mengubah K pada suhu tetap. Reaksi ini tidak selalu berlangsung tuntas.'],
['Neraca dan kesetimbangan','Jika mula-mula a mol asam dan b mol alkohol, tanpa ester/air, perubahan x menghasilkan a−x, b−x, x, x. Dalam model campuran ideal dengan volume tetap, K=x²/((a−x)(b−x)). Nilai x dibatasi pereaksi awal.'],
['Hasil dan batas model','Fraksi asam berubah adalah x/a. Menambah alkohol dapat meningkatkan konversi asam. Model mengabaikan aktivitas, pemisahan fase dan perubahan volume; K yang dipilih merupakan parameter latihan, bukan data eksperimen etil etanoat.']],
[['acid','Asam awal (mol)',0.1,2,1,0.1],['alcohol','Alkohol awal (mol)',0.1,4,1,0.1],['constant','K model',0.5,10,4,0.5]],
'Bandingkan campuran 1:1 dengan 1:2 pada K yang sama. Catat mol ester dan konversi asam.',
['Hitung keempat jumlah mol setimbang saat a=b=1 dan K=4.','Apa pengaruh penambahan alkohol pada konversi asam? Gunakan dua hasil simulasi.','Mengapa katalis tidak dimasukkan sebagai pengubah K dalam model ini?'],
'Untuk 1,1,K4: x=2/3; sisa asam/alkohol1/3, ester/air2/3. Alkohol berlebih meningkatkan konversi asam. Katalis mengubah laju dua arah bukan K pada suhu tetap.',
[q('Esterifikasi menghasilkan ...',['ester dan air','alkana saja','amina','logam'],0),q('Rasio mol asam:etanol adalah ...',['2:1','1:2','1:1','3:1'],2),q('Katalis pada suhu tetap ...',['menaikkan K','mempercepat kesetimbangan','menghilangkan air','mengubah stoikiometri'],1),q('Penambahan pada C=C disebut ...',['adisi','substitusi','distilasi','ionisasi'],0),q('Kesetimbangan berarti ...',['reaksi berhenti','semua pereaksi habis','laju maju sama dengan balik','produk selalu nol'],2)]);
add('org-aromatik','Benzena_dan_Turunannya','Benzena dan Turunannya','aromatic',[
['Cincin aromatik','Benzena C₆H₆ memiliki enam C sp² dalam cincin planar dengan elektron π terdelokalisasi. Enam ikatan C–C setara. Dua gambar Kekulé adalah kontributor resonansi, bukan molekul yang berganti-ganti secara fisik.'],
['Turunan benzena','Toluena adalah metilbenzena, fenol mempunyai OH langsung pada cincin, anilina mempunyai NH₂, dan asam benzoat mempunyai COOH. Gugus substituen dapat mengubah sifat serta reaktivitas cincin.'],
['Posisi dua substituen','Dengan satu substituen pada C1, substituen kedua pada C2 disebut orto (1,2), C3 meta (1,3), dan C4 para (1,4). Untuk dua substituen identik, posisi 1,6 ekuivalen dengan 1,2 setelah penomoran ulang.'],
['Reaktivitas','Benzena cenderung mengalami substitusi elektrofilik yang mempertahankan aromatisitas. Model posisi berikut tidak memprediksi distribusi produk atau kondisi sintesis. Benzena berbahaya; eksplorasi ini dilakukan secara virtual.']],
[['position','Posisi CH₃ kedua',2,6,2,1]],
'Pindahkan gugus metil kedua pada cincin dimetilbenzena. Temukan posisi yang setara melalui penomoran ulang.',
['Kelompokkan posisi 2 sampai 6 menjadi orto, meta dan para.','Mengapa ikatan C–C benzena setara walau gambar Kekulé memakai tunggal/rangkap?','Bedakan fenol, toluena dan asam benzoat berdasarkan substituen.'],
'2/6 orto,3/5 meta,4 para. Elektron pi terdelokalisasi, Kekule kontributor resonansi bukan pergantian. FenolOH,toluenaCH3,asam benzoatCOOH.',
[q('Posisi 1,3 disebut ...',['orto','meta','para','cis'],1),q('C–C pada benzena ...',['semuanya setara','tiga selalu lebih panjang','hanya tunggal','ionik'],0),q('Metilbenzena adalah ...',['fenol','anilina','toluena','etanol'],2),q('Reaksi khas benzena mempertahankan ...',['kejenuhan alkana','aromatisitas','ikatan ion','neutron'],1),q('Dua gambar Kekulé adalah ...',['dua isomer isolabel','kontributor resonansi','dua unsur','campuran'],1)]);
add('org-polimer','Polimer_dan_Material','Polimer dan Material','polymer',[
['Monomer dan unit ulang','Polimer merupakan rantai panjang unit berulang. Pada polimerisasi etena, ikatan π dibuka sehingga terbentuk unit –CH₂–CH₂–. Rumus monomer dan unit ulang perlu dibedakan dari gambar rantai lengkap beserta gugus ujung.'],
['Adisi dan kondensasi','Polimerisasi adisi alkena tidak menghasilkan molekul kecil sebagai produk samping ideal. Kondensasi molekul bifungsional dapat melepaskan air. Nylon dan poliester memiliki gugus penghubung berbeda; tidak semua polimer terbentuk melalui adisi.'],
['Neraca massa model','Rantai adisi n etena memiliki perkiraan massa molar 28n g/mol dengan gugus ujung diabaikan. Kondensasi linear n molekul asam hidroksi bermassa molar 90 menghasilkan n−1 air: M≈90n−18(n−1). Model satu rantai, tanpa siklus.'],
['Struktur dan lingkungan','Cabang, ikatan silang dan kristalinitas memengaruhi sifat. Termoplastik dapat dilunakkan kembali; jaringan termoset tidak sekadar meleleh saat dipanaskan. Label polimer tidak otomatis berarti mudah didaur ulang atau terurai hayati.']],
[['units','Jumlah monomer dalam satu rantai',2,30,5,1]],
'Bandingkan adisi etena dan kondensasi asam hidroksi untuk jumlah monomer sama. Periksa neraca massa.',
['Hitung massa molar model adisi saat n=10 dan jelaskan asumsi gugus ujung.','Untuk n=10 pada kondensasi, hitung air dan massa rantai; buktikan neraca massa.','Mengapa jenis ikatan dan ikatan silang relevan terhadap daur ulang?'],
'Adisi n10 M280 tanpa ujung. Kondensasi n10 air9,M738;900=738+162. Termoset jaringan silang sulit dilelehkan ulang; hindari klaim semua plastik biodegradable.',
[q('Unit ulang polietena adalah ...',['–CH₂–CH₂–','CH₄ bebas','CO₂','–COOH'],0),q('Kondensasi linear 5 monomer melepas ...',['5 air','4 air','6 air','0 selalu'],1),q('M model polietena n=10 ...',['28','280','2800','18'],1),q('Termoset mempunyai ...',['jaringan ikatan silang','selalu rantai tunggal larut','hanya ion','tidak ada ikatan'],0),q('Biodegradabilitas ...',['pasti untuk semua polimer','sama dengan bisa dilelehkan','bergantung struktur dan kondisi','hanya bergantung warna'],2)]);
add('bio-karbo','Karbohidrat_dan_Uji_Identifikasi','Karbohidrat dan Uji Identifikasi','carb',[
['Jenis karbohidrat','Glukosa dan fruktosa adalah monosakarida; sukrosa dan maltosa disakarida; pati dan selulosa polisakarida. Rumus empiris mirip tidak berarti struktur serta fungsi sama. Pati dan selulosa berbeda konfigurasi ikatan glikosidiknya.'],
['Hidrolisis','Hidrolisis sukrosa memutus ikatan glikosidik dengan konsumsi air dan menghasilkan glukosa serta fruktosa. Hidrolisis maltosa menghasilkan dua glukosa. Pati akhirnya dapat dihidrolisis menjadi glukosa; selulosa memerlukan kondisi atau enzim yang sesuai.'],
['Uji gula pereduksi','Benedict mendeteksi kemampuan mereduksi pada kondisi uji, bukan khusus glukosa. Fruktosa juga positif melalui perubahan struktur dalam suasana basa. Sukrosa utuh negatif tetapi hidrolisatnya positif. Warna bergantung kadar dan kondisi.'],
['Uji iodin','Pati dapat memberikan warna biru kehitaman dengan iodin; glukosa tidak. Uji iodin dan Benedict menjawab pertanyaan berbeda. Simulasi memakai hasil ideal kualitatif, bukan prosedur eksperimen atau prediksi warna kuantitatif.']],[],
'Pilih sampel dan bandingkan uji sebelum/sesudah hidrolisis sempurna. Gunakan lebih dari satu uji saat menarik kesimpulan.',
['Bandingkan sukrosa sebelum dan sesudah hidrolisis pada Benedict; jelaskan produknya.','Mengapa hasil Benedict positif belum membuktikan sampel pasti glukosa?','Jelaskan perubahan uji iodin pada pati yang dihidrolisis sempurna.'],
'Sukrosa negatif menjadi positif menghasilkan glukosa+fruktosa. Glukosa/fruktosa/maltosa positif sehingga bukan spesifik. Pati iodin positif sebelum, negatif setelah sempurna jadi glukosa. Hindari menganggap seluruh polisakarida identik.',
[q('Monosakarida adalah ...',['pati','sukrosa','glukosa','selulosa'],2),q('Hidrolisis sukrosa menghasilkan ...',['glukosa dan fruktosa','dua fruktosa','pati','asam amino'],0),q('Benedict positif menunjukkan ...',['pasti glukosa','sifat pereduksi','pasti pati','pasti protein'],1),q('Uji iodin khas pati menghasilkan ...',['biru kehitaman','gas hidrogen','perak','selalu bening'],0),q('Fruktosa pada Benedict ...',['dapat positif','selalu negatif','menjadi protein','tidak bereaksi karena ketosa dalam semua kondisi'],0)]);
add('bio-protein','Asam_Amino_dan_Protein','Asam Amino dan Protein','protein',[
['Asam amino','Asam amino penyusun protein memiliki gugus amino, karboksil dan rantai samping R pada karbon alfa. Glisina R=H; alanina R=CH₃. Bentuk muatan bergantung pH; struktur NH₂–CHR–COOH hanyalah salah satu representasi.'],
['Zwitterion','Untuk glisina model dua disosiasi, pKa₁=2,34 dan pKa₂=9,60. Pada pH rendah dominan kation, pH antara kedua pKa dominan zwitterion, dan pH tinggi dominan anion. Muatan bersih nol tidak berarti tidak memiliki gugus bermuatan.'],
['Peptida','Ikatan peptida –CO–NH– menghubungkan residu asam amino. Kondensasi linear n asam amino membentuk n−1 ikatan peptida dan air. Urutan residu adalah struktur primer; pelipatan dan asosiasi menentukan tingkat struktur lebih tinggi.'],
['Denaturasi','Denaturasi mengganggu struktur lebih tinggi dan dapat menurunkan fungsi. Denaturasi tidak identik dengan hidrolisis seluruh ikatan peptida. Model fraksi glisina tidak berlaku langsung pada semua protein karena gugus R dapat terionisasi.']],
[['ph','pH',0,14,6,0.1]],
'Ubah pH dari 1 ke 6 lalu 12. Amati fraksi kation, zwitterion, anion, dan muatan rata-rata glisina.',
['Bandingkan bentuk dominan glisina pada pH1,6,12.','Hitung pI model glisina dan jelaskan arti muatan bersih nol.','Berapa ikatan peptida dalam rantai linear 8 residu? Bedakan denaturasi dan hidrolisis.'],
'pH1 kation,pH6 zwitterion,pH12 anion. pI=(2.34+9.60)/2=5.97; muatan bersih nol masih NH3+/COO-.8residu7ikatan. Denaturasi bukan pemutusan semua ikatan peptida.',
[q('Gugus penghubung peptida ...',['–CO–NH–','–O–O–','C=C saja','NaCl'],0),q('Rantai 8 residu memiliki ...',['8 ikatan peptida','7 ikatan peptida','9','16'],1),q('Zwitterion memiliki ...',['tidak ada muatan lokal','muatan + dan −','hanya +','hanya −'],1),q('pI glisina model ...',['2,34','9,60','5,97','14'],2),q('Denaturasi terutama mengubah ...',['nomor atom','struktur lipatan','seluruh inti','unsur C jadi N'],1)]);
add('bio-enzim','Enzim_dan_Kinetika_Sederhana','Enzim dan Kinetika Sederhana','enzyme',[
['Katalis biologis','Enzim mempercepat reaksi dengan menurunkan penghalang aktivasi dan tidak mengubah kesetimbangan termodinamika. Banyak enzim adalah protein, tetapi RNA katalitik juga ada. Kekhususan bergantung struktur situs aktif.'],
['Kejenuhan','Model Michaelis–Menten v=Vmax[S]/(Km+[S]) menggambarkan laju awal terhadap substrat untuk mekanisme yang memenuhi asumsi model. Ketika [S]=Km, v=Vmax/2. Vmax sebanding jumlah enzim aktif pada kondisi sama.'],
['Inhibisi kompetitif','Model kompetitif memakai Km tampak=Km(1+[I]/Ki), sedangkan Vmax tetap. Pada konsentrasi substrat terbatas laju turun; pada substrat sangat tinggi laju mendekati Vmax. Ini bukan model untuk semua inhibitor.'],
['Batas penggunaan','Grafik ini bukan perjalanan reaksi terhadap waktu: sumbu mendatar adalah konsentrasi substrat. Suhu, pH, denaturasi dan penghabisan substrat tidak dimodelkan. Parameter adalah latihan dalam satuan konsisten, bukan diagnosis atau data enzim tertentu.']],
[['substrate','Substrat (mM)',0,20,2,0.5],['km','Km (mM)',0.5,5,2,0.5],['vmax','Vmax (µmol/menit)',10,100,60,10],['inhibitor','Inhibitor (mM), Ki=1 mM',0,5,0,0.5]],
'Bandingkan laju dengan dan tanpa inhibitor pada [S]=Km. Naikkan substrat dan amati kejenuhan.',
['Hitung v saat Vmax60, Km2, [S]2 tanpa inhibitor.','Hitung Km tampak dan v pada kondisi sama dengan [I]2 dan Ki1.','Mengapa grafik laju–substrat tidak boleh dibaca sebagai grafik konsentrasi–waktu?'],
'v30. I2/Ki1 =>Kmapp6,v15. Kompetitif Vmax tetap. Sumbu S konsentrasi substrat untuk pengukuran laju awal terpisah, bukan waktu.',
[q('Saat [S]=Km tanpa inhibitor, v ...',['Vmax','Vmax/2','nol','2Vmax'],1),q('Inhibitor kompetitif ideal ...',['menurunkan Vmax','menaikkan Km tampak','mengubah K reaksi','menghabiskan enzim'],1),q('Sumbu x simulasi adalah ...',['waktu','suhu','substrat','pH'],2),q('Enzim mengubah ...',['laju reaksi','kesetimbangan akhir pada kondisi sama','jumlah atom','konservasi massa'],0),q('Pada substrat sangat tinggi, v mendekati ...',['Km','nol','Vmax','Ki'],2)]);
add('bio-lipid','Lipid_Lemak_dan_Sabun','Lipid, Lemak, dan Sabun','lipid',[
['Trigliserida','Trigliserida adalah triester gliserol dengan tiga asam lemak. Asam lemak jenuh tidak memiliki C=C pada rantai; tak jenuh memilikinya. Ikatan cis dapat menekuk rantai dan mengurangi kerapatan pengemasan, tetapi titik leleh juga dipengaruhi panjang rantai dan komposisi.'],
['Hidrogenasi','Setiap C=C mengonsumsi satu H₂ untuk menjadi ikatan tunggal pada hidrogenasi lengkap ideal. Simulasi memakai total C=C per molekul trigliserida, bukan per rantai. Hidrogenasi parsial nyata dapat membentuk isomer trans; model ini tidak memprediksi komposisinya.'],
['Penyabunan','Satu mol trigliserida bereaksi dengan tiga mol NaOH menghasilkan satu mol gliserol dan tiga mol garam natrium asam lemak. Produk garam amfifilik memiliki kepala hidrofilik dan ekor hidrofobik. Pembentukan misel membantu mendispersikan minyak.'],
['Batas model','Kebutuhan NaOH ditentukan tiga ikatan ester, bukan banyaknya C=C. Sabun dapat membentuk endapan dengan ion air sadah. Model stoikiometri ini bukan resep pembuatan sabun; kemurnian bahan dan basa berlebih tidak dihitung.']],
[['mol','Trigliserida (mol)',0.1,2,1,0.1],['double','Total C=C per molekul',0,9,3,1]],
'Ubah jumlah C=C pada jumlah trigliserida tetap. Bandingkan kebutuhan H₂ dengan NaOH.',
['Untuk 0,5 mol trigliserida dengan total 3 C=C, hitung kebutuhan H₂ dan NaOH.','Mengapa perubahan jumlah C=C tidak mengubah kebutuhan NaOH per mol trigliserida?','Hubungkan struktur amfifilik sabun dengan dispersinya terhadap minyak.'],
'0.5mol,total3 C=C =>H2 1.5mol,NaOH1.5mol,gliserol.5,sabun1.5. NaOH memutus3ester; C=C tidak menentukan jumlah ester. Kepala hidrofilik ekor hidrofobik membentuk misel.',
[q('Trigliserida memiliki ...',['1 ester','2 ester','3 ester','9 ester'],2),q('1 mol trigliserida perlu NaOH ...',['1 mol','3 mol','2 mol','0 mol'],1),q('Satu C=C memerlukan H₂ ...',['1 molekul','2 molekul','3 molekul','0'],0),q('Kepala sabun bersifat ...',['hidrofilik','hidrofobik','logam','nonpolar seluruhnya'],0),q('Cis pada rantai tak jenuh dapat ...',['menekuk rantai','menambah ester otomatis','menghilangkan semua H','membentuk protein'],0)]);
add('bio-nukleat','DNA_RNA_dan_Asam_Nukleat','DNA, RNA, dan Asam Nukleat','dna',[
['Nukleotida','Nukleotida terdiri atas basa nitrogen, gula pentosa dan fosfat. Nukleosida tidak memiliki fosfat. Ikatan fosfodiester menghubungkan gula-fosfat dalam satu untai; ikatan hidrogen menghubungkan pasangan basa antarrantai.'],
['DNA dan RNA','DNA memiliki deoksiribosa dan basa A,T,G,C. RNA memiliki ribosa dan umumnya A,U,G,C. DNA beruntai ganda memiliki orientasi antiparalel; pasangan A–T dan G–C berbeda dari urutan kodon translasi.'],
['Pasangan komplemen','Jika untai diberikan 5′→3′, komplemen yang disejajarkan ditulis 3′→5′. Untuk menyajikan komplemen dalam arah 5′→3′ perlu membalik urutannya. Dalam model pasangan Watson–Crick, A–T memiliki 2 ikatan hidrogen dan G–C memiliki 3.'],
['Komposisi dan batas model','Persentase GC dihitung dari jumlah G+C dibagi panjang urutan. Jumlah ikatan hidrogen bukan satu-satunya penentu kestabilan DNA; penumpukan basa, ion dan kondisi lain penting. Simulasi urutan pendek ini tidak menerjemahkan protein atau menghitung suhu leleh.']],[],
'Pilih urutan DNA. Bandingkan komplemen sejajar dengan komplemen yang ditulis 5′→3′ dan hitung GC.',
['Untuk ATGCCA arah 5′→3′, tulis komplemen sejajar beserta arahnya dan reverse complement.','Hitung GC dan jumlah ikatan hidrogen model untuk urutan tersebut.','Bedakan ikatan fosfodiester dan ikatan hidrogen serta komponen DNA/RNA.'],
'ATGCCA:3′TACGGT5′;reverse complement5′TGGCAT3′;GC3/6=50%,H=15. Fosfodiester intrarantai gula-fosfat,H antarbasa.DNAdeoksiribosaT,RNAribosaU.',
[q('Nukleotida terdiri atas ...',['gula,basa,fosfat','asam amino','gliserol saja','basa saja'],0),q('Pasangan G adalah ...',['A','T','C','U'],2),q('Kedua untai DNA ...',['antiparalel','selalu arah sama','tanpa orientasi','ikatan logam'],0),q('RNA umumnya memakai ...',['timin','urasil','gliserol','benzena'],1),q('Ikatan tulang punggung DNA ...',['peptida','ester lemak','fosfodiester','logam'],2)]);
module.exports=topics;
